{
  "hash": "9023102084e9183ef9973146eaafb3c9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Relate 3+ Variables\"\nsubtitle: \"Linear regression: how to run it and report it\"\nauthor:\n  - Allison Anemone\n  - Andrew Silhavy\n  - Vivian Raposo\n  - Serena Suchdeve\n  - Shane McCarty\nabstract: |\n  This chapter teaches researchers to examine a relationship question with a linear regression in R. Researchers start with a simple regression (one predictor and one outcome), learn to read the intercept, the slope, the p-value, and R-squared, and then add more predictors to build a multiple linear regression, including a categorical predictor such as gender. The chapter shows how to check the residuals (the outcome itself need not be normal), how to report a regression in a sentence and in a table, and which common shortcuts to avoid (leaving a category as a number, and cutting a score into two groups). A second Play re-runs a published FRI result, growth mindset predicting support for care-based violence prevention, with gender added as a third variable. In The Lab, researchers run three models with the lab dataset (one predictor, a binary predictor, and a dummy-coded predictor) and check their own answers. In Your Turn, researchers use a copy-ready template and a checklist for their own research question.\nkeywords:\n  - linear regression\n  - multiple regression\n  - lm\n  - predictors\n  - residuals\n  - relationship\ndate: 10.05.2026\ndate-format: \"MM.DD.YYYY\"\nformat:\n  html:\n    css: custom.css\neditor: visual\nexecute:\n  cache: false   # this chapter reads lab_prep.R and the lab dataset; a cache would keep OLD data after they change\n  warning: false\n  message: false\n---\n\n<!-- Single source for the collapsed kickoff reminder at the START of every coding chapter (7 onward). Edit here only. The full routine lives in find-the-ref.qmd (Ref's Quick Checklist). -->\n\n::: {.callout-note .gray collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's kickoff: find the Ref before you code\n\n**Open Project → Open `.qmd` → Run load-library chunk → Run All Chunks Above → code.** If anything looks wrong, use [Ref's Quick Checklist](find-the-ref.qmd#sec-ref-checklist).\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Resources: regression\n\n-   [ModernDive Ch. 5: Basic Regression](https://moderndive.com/v2/regression.html)\n-   [ModernDive Ch. 6: Multiple Regression](https://moderndive.com/v2/multiple-regression.html)\n-   [Documentation for `lm()`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html)\n:::\n\n## How This Chapter Works\n\nYou will go through this chapter three times, with three different datasets.\n\n| Pass | Section | Dataset | What you do |\n|------|-----------|-------------|--------------------------------------------|\n| 1 | [The Play](#the-play) | `pregnancydata` (example, simulated) | **Watch the play.** Read the code and the output, step by step. |\n| 2 | [The Lab](#sec-regression-lab) | lab dataset | **Run the play.** Run two regressions yourself during the R Lab, then check your own work. Labs are not graded. |\n| 3 | [Your Turn](#sec-regression-yourturn) | your team's dataset | **Call your own play.** After you finish all of the R Labs, come back and run the regression for your own research question. |\n\n::: {.callout-tip}\n## Go: Know your route first\n\nThis chapter is the last step on [The Analysis Map](analysis-map.qmd) for a **relationship** question with **three or more variables**: one outcome that is a score, and two or more predictors. Make your scatterplot first in [Visualize a Relationship](visualize-relationship.qmd).\n:::\n\n## 📋 The Play {#the-play}\n\n### Play 1 (simple and multiple linear regression): relate three predictors to perceived barriers\n\n#### Example Data: `pregnancydata`\n\nThe example comes from an FRI Public Health team that surveyed people about health beliefs during pregnancy. One of their questions was: **do people with lower social status perceive more barriers to following health advice during pregnancy, after we account for their age and gender?**\n\n::: {.callout-warning}\n## Caution: This example dataset is simulated\n\nTo protect the people who took the team's survey, the file used in this chapter does **not** contain their answers. It is a *simulated* dataset: a computer generated every row so that the variables and their averages look like the team's data. Use it to learn the play. Do not cite its results.\n:::\n\n| Variable | What it is | Values |\n|-------------|----------------------------------|-----------------------|\n| `BARRIERS` | the **outcome**: perceived barriers (the mean of 9 survey items) | 1 = low to 5 = high |\n| `SSS` | subjective social status (a ladder with 10 rungs) | 1 = bottom to 10 = top |\n| `AGE` | age in years | 18 and up |\n| `GENDER` | gender | 1 = Woman, 2 = Man |\n\n#### Load and Import\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npregnancydata <- read.csv(\"data/pregnancy_beliefs_SIMULATED.csv\")\n\nsummary(pregnancydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      ID                 AGE            GENDER             SSS        \n Length:160         Min.   :18.00   Min.   :-99.000   Min.   :-99.00  \n Class :character   1st Qu.:19.00   1st Qu.:  1.000   1st Qu.:  5.00  \n Mode  :character   Median :22.00   Median :  1.000   Median :  6.00  \n                    Mean   :28.53   Mean   : -0.675   Mean   :  2.35  \n                    3rd Qu.:34.25   3rd Qu.:  1.000   3rd Qu.:  7.00  \n                    Max.   :63.00   Max.   :  2.000   Max.   : 10.00  \n                    NA's   :4                                         \n    BARRIERS    \n Min.   :1.000  \n 1st Qu.:1.670  \n Median :2.220  \n Mean   :2.226  \n 3rd Qu.:2.697  \n Max.   :4.000  \n                \n```\n\n\n:::\n:::\n\n\nLook at the minimum of `SSS` and `GENDER`. A value of -99 is not a real answer. It is the code for \"Prefer not to answer\", and it has to become missing (`NA`) before you analyze anything.\n\n#### Step 1: Get the data ready\n\n\n::: {.cell}\n\n```{.r .cell-code}\npregnancydata <- pregnancydata |>\n  mutate(\n    SSS    = na_if(SSS, -99),                       # -99 becomes NA (missing)\n    GENDER = na_if(GENDER, -99),\n    GENDER = factor(GENDER,                         # tell R that GENDER is a category\n                    levels = c(1, 2),\n                    labels = c(\"Woman\", \"Man\")))\n\nsummary(pregnancydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      ID                 AGE          GENDER         SSS        \n Length:160         Min.   :18.00   Woman:125   Min.   : 2.000  \n Class :character   1st Qu.:19.00   Man  : 32   1st Qu.: 5.000  \n Mode  :character   Median :22.00   NA's :  3   Median : 6.000  \n                    Mean   :28.53               Mean   : 6.299  \n                    3rd Qu.:34.25               3rd Qu.: 7.750  \n                    Max.   :63.00               Max.   :10.000  \n                    NA's   :4                   NA's   :6       \n    BARRIERS    \n Min.   :1.000  \n 1st Qu.:1.670  \n Median :2.220  \n Mean   :2.226  \n 3rd Qu.:2.697  \n Max.   :4.000  \n                \n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Caution: Don't leave a category as a number\n\nIn the data file, `GENDER` is stored as the numbers 1 and 2. If you leave it that way, R treats gender as a *score*, as if a man were \"one unit more\" than a woman. `factor()` tells R that the numbers are labels for groups. Do this for **every** categorical predictor before you run a regression.\n:::\n\n#### Step 2: Look before you test\n\nAlways make the plot first (see [Visualize a Relationship](visualize-relationship.qmd)). `BARRIERS` is a mean of survey items, so points can stack. Jitter them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot1_barriers_sss_scatter <- ggplot(\n  data = pregnancydata,\n  mapping = aes(\n    x = SSS,\n    y = BARRIERS)) +\n  geom_jitter(width = 0.15, height = 0.05, alpha = 0.6) +\n  geom_smooth(method = \"lm\") +\n  xlim(1, 10) +\n  ylim(1, 5) +\n  ggtitle(\"Social Status and Perceived Barriers\") +\n  xlab(\"Subjective social status (1 = bottom rung, 10 = top rung)\") +\n  ylab(\"Perceived barriers (1 = low, 5 = high)\") +\n  theme_bw()\n\nplot1_barriers_sss_scatter\n```\n\n::: {.cell-output-display}\n![Figure 1. Subjective social status and perceived barriers in the simulated pregnancydata dataset. Points are jittered; the line is a linear line of best fit.](regression_files/figure-html/plot1-barriers-sss-scatter-1.png){fig-alt='A scatterplot with subjective social status on the x axis and perceived barriers on the y axis. The line of best fit slopes downward.' width=672}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot1_barriers_sss_scatter.png\", plot = plot1_barriers_sss_scatter, width = 8, height = 5, dpi = 300)\n```\n:::\n\n\nThe line slopes downward: people who place themselves higher on the ladder report fewer barriers. A regression puts a number on that line and tests it.\n\n#### Step 3: One predictor (simple regression)\n\nThe function is `lm()`, which stands for *linear model*. Read the formula `BARRIERS ~ SSS` as \"**`BARRIERS` is predicted by `SSS`**\". The outcome always goes on the left of the `~`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# regmodel1: BARRIERS predicted by SSS alone (simple regression)\nregmodel1 <- lm(BARRIERS ~ SSS, data = pregnancydata)\n\nsummary(regmodel1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = BARRIERS ~ SSS, data = pregnancydata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.39107 -0.50107 -0.05018  0.49349  1.67425 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.04994    0.22107  13.796  < 2e-16 ***\nSSS         -0.13177    0.03392  -3.884 0.000153 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7037 on 152 degrees of freedom\n  (6 observations deleted due to missingness)\nMultiple R-squared:  0.0903,\tAdjusted R-squared:  0.08432 \nF-statistic: 15.09 on 1 and 152 DF,  p-value: 0.0001527\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: callout-tip\n## Go: name every test `ttestmodel1`, `regmodel1`, and say what each number means\n\nDo not call a model `model`. By the end of a report you will have several, and `model` tells nobody which one a table came from. Name each one with the test and a number, nothing else: the number is the order you ran them in, the same order papers use in a regression table (Model 1, Model 2). Then, on the line above every test, write a comment that says what that number means, because `regmodel2` on its own does not:\n\n```r\n# regmodel1: BARRIERS predicted by SSS alone (simple regression)\nregmodel1 <- lm(BARRIERS ~ SSS, data = pregnancydata)\n\n# regmodel2: regmodel1 + AGE + GENDER (multiple regression)\nregmodel2 <- lm(BARRIERS ~ SSS + AGE + GENDER, data = pregnancydata)\n```\n\nOne name for each test in this playbook:\n\n| Test | Name |\n|----|----|\n| Independent-samples t-test | `ttestmodel1` |\n| Mann-Whitney U | `mannmodel1` |\n| Paired-samples t-test | `ptestmodel1` |\n| Wilcoxon signed-rank | `wilcomodel1` |\n| ANOVA, Kruskal-Wallis, ANCOVA | `anovamodel1`, `kruskalmodel1`, `ancovamodel1` |\n| Pearson, Spearman | `pearsonmodel1`, `spearmanmodel1` |\n| Linear regression | `regmodel1`, `regmodel2`, ... |\n\nLowercase, like every object in this playbook; the uppercase names are variables.\n:::\n\nHow to read the output:\n\n-   **`(Intercept)`, Estimate = 3.05.** This is where the line starts: the predicted `BARRIERS` score for a person whose `SSS` is 0. It is rarely interesting by itself.\n-   **`SSS`, Estimate = -0.13.** This is the **slope**, and it is the number you care about. For every one rung higher on the ladder, the predicted `BARRIERS` score goes *down* by 0.13 points. A negative slope is a line that goes down. A positive slope is a line that goes up.\n-   **`Pr(>|t|)`** is the **p-value** for that slope. Here it is less than .001, which is smaller than .05, so the relationship is statistically significant.\n-   **`Multiple R-squared` = 0.09.** `SSS` explains about 9% of the differences between people in `BARRIERS`. In survey research, small values like this are common.\n-   At the bottom, R tells you how many people were left out because of missing answers. Report the number of people who were *in* the model: `nobs(regmodel1)` = 154.\n\n#### Step 4: Three predictors (multiple regression)\n\nTo add predictors, add them to the formula with `+`. This answers the team's real question: is social status still related to barriers **after we account for** age and gender?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# regmodel2: regmodel1 + AGE + GENDER (multiple regression)\nregmodel2 <- lm(BARRIERS ~ SSS + AGE + GENDER, data = pregnancydata)\n\nsummary(regmodel2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = BARRIERS ~ SSS + AGE + GENDER, data = pregnancydata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.50023 -0.48651 -0.02719  0.52032  1.71508 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.050186   0.235938  12.928  < 2e-16 ***\nSSS         -0.126588   0.034820  -3.636 0.000385 ***\nAGE         -0.002173   0.004318  -0.503 0.615577    \nGENDERMan    0.130783   0.142325   0.919 0.359684    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6986 on 144 degrees of freedom\n  (12 observations deleted due to missingness)\nMultiple R-squared:  0.09423,\tAdjusted R-squared:  0.07536 \nF-statistic: 4.993 on 3 and 144 DF,  p-value: 0.002524\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nEach slope now means \"the change in `BARRIERS` for one more unit of this predictor, **when the other predictors stay the same**.\"\n\n-   **`SSS`** (b = -0.13, p < .001): still negative and still significant. Social status is related to barriers even when you compare people of the same age and gender.\n-   **`AGE`** (b = -0.002, p = .616): the slope is almost zero and the p-value is larger than .05. Age is not related to barriers in this sample.\n-   **`GENDERMan`** (b = 0.13, p = .360): for a category, R picks the first group (`Woman`) as the comparison group and reports how different the *other* group is. Men scored 0.13 points higher than women, and that difference is not significant.\n-   **n = 148.** A person is dropped if they are missing **any** variable in the model, so the more predictors you add, the fewer people you keep.\n\n::: {.callout-warning}\n## Caution: Related does not mean caused\n\nA regression on survey data tells you that two things go together. It does not tell you that one *causes* the other. Write \"is related to\", \"is associated with\", or \"predicts\". Do not write \"leads to\", \"affects\", or \"causes\".\n:::\n\n#### Step 5: Check the residuals\n\nA **residual** is how far each person is from the line. A linear regression works best when the residuals are roughly bell-shaped (normal). This is the \"is it normal?\" question from the Analysis Map, asked about the residuals and not about the raw scores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot2_barriers_residuals_histogram <- ggplot(data = data.frame(residual = resid(regmodel2)),\n       mapping = aes(x = residual)) +\n  geom_histogram(bins = 20, fill = \"#005a43\", color = \"white\") +\n  xlab(\"Residual (actual score minus predicted score)\") +\n  ylab(\"Number of people\") +\n  theme_bw()\nplot2_barriers_residuals_histogram\n```\n\n::: {.cell-output-display}\n![Figure 2. Histogram of the residuals from the multiple regression. The shape is roughly bell-shaped.](regression_files/figure-html/plot2-barriers-residuals-histogram-1.png){fig-alt='A histogram of regression residuals centered on zero with a roughly symmetric bell shape.' width=576}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot2_barriers_residuals_histogram.png\", plot = plot2_barriers_residuals_histogram, width = 8, height = 5, dpi = 300)\n```\n:::\n\n\nIf your histogram has one long tail or two humps, talk to your peer mentor and/or Dr. Shane before you report the model.\n\n#### Step 6: Report it\n\nReport the slope (b), the p-value, and the number of people for each predictor, and R-squared for the whole model.\n\n> A multiple linear regression (n = 148) showed that subjective social status was negatively associated with perceived barriers (b = -0.13, p < .001), after accounting for age and gender. Age (b = -0.002, p = .616) and gender (b = 0.13, p = .360) were not significantly associated with perceived barriers. Together, the three predictors explained 9% of the variance in perceived barriers (R² = .09).\n\nYou can also print the coefficients as a table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(summary(regmodel2)$coefficients,\n             digits = 3,\n             caption = \"Table 1. Multiple linear regression predicting perceived barriers.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 1. Multiple linear regression predicting perceived barriers.\n\n|            | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:-----------|--------:|----------:|-------:|------------------:|\n|(Intercept) |    3.050|      0.236|  12.928|              0.000|\n|SSS         |   -0.127|      0.035|  -3.636|              0.000|\n|AGE         |   -0.002|      0.004|  -0.503|              0.616|\n|GENDERMan   |    0.131|      0.142|   0.919|              0.360|\n\n\n:::\n:::\n\n\n### Play 2 (multiple linear regression): relate growth mindset to care-based support, with gender as a third variable\n\n::: {.callout-note collapse=\"true\"}\n## About the dataset: `safety_data.csv` (an FRI Public Health team's data, Cohort 11)\n\nIn fall 2025 an FRI Public Health team (Serena Suchdeve, Vivian Raposo, Caitlin Ngo, Kayla Vo, and Rowen Smith) surveyed Binghamton University students and Broome County residents about community safety: how safe and connected they feel in their neighborhood, how effective they believe different violence-prevention approaches are (care-based approaches such as community programs, education, and mental-health resources; fear-based approaches such as policing and deportation), and whether they hold a growth or a fixed mindset about whether people can change (Dweck's Kind of Person Implicit Theory scale). Their report, [*Mixed-Methods Analysis of Preferences for Community-Based Violence Prevention and Intervention Approaches*](https://vraposo.quarto.pub/mixed-methods-analysis-of-preferences-for-community-based-violence-prevention-and-intervention-approaches/), found that a growth mindset predicted support for care-based community interventions (*b* = .57, *p* = .001, *R*² = .23) but not for fear-based policing. This chapter re-runs part of that analysis so you can see a published FRI result come out of the same code you are learning.\n\nThis is **real data**, de-identified for the playbook: the 75 consenting respondents who completed at least half of the survey, with response IDs, dates, ZIP codes, free-text answers, and the open-ended questions removed. The coded values are exactly as exported, so `-99` (prefer not to say) and `-50` (don't know) are still there for you to recode. Variables used in the chapters:\n\n-   `FIXEDPERSON1_BASIC` … `FIXEDPERSON_ALL_R`: the eight mindset items, on a 1 = Strongly agree to 6 = Strongly disagree scale (note the direction). Items without `_R` state a **fixed** mindset (\"Everyone is a certain kind of person, and there is not much that can be done to really change that\"), so a higher number means more growth mindset; items with `_R` state a **growth** mindset and are reversed. The mean of all eight is the composite `GROWTH` (higher = more growth mindset).\n-   `COMM_FEEL`, `COMM_HELP`, `COMM_NEIGHBORS`, `NOTCOMM_UNSAFE`, `NOTCOMM_RELY`, `NOTCOMM_DISTRUST`: six neighborhood items (1 = Strongly disagree to 6 = Strongly agree); the three `NOTCOMM` items are reversed for the composite `COMMUNITY`.\n-   `EFFECT_CARE_COMM`: \"Community-based interventions are the most effective way to achieve community safety\" (1 to 6), a single item; `EFFECT_FEAR_POLICE`: the same for policing.\n-   `GENDER`: the class coding, 0 = Girl or woman, 1 = Boy or man, 2 = Nonbinary, genderfluid, or genderqueer; `AGE`; `SOCIALSTATUS` (1 to 10).\n\nCite the team's report when you use this dataset: Suchdeve, S., Raposo, V., Ngo, C., Vo, K., & Smith, R. (2025). *Mixed-methods analysis of preferences for community-based violence prevention and intervention approaches*. FRI Public Health, Binghamton University. <https://vraposo.quarto.pub/mixed-methods-analysis-of-preferences-for-community-based-violence-prevention-and-intervention-approaches/>\n:::\n\n\n[Relate 2 Variables](correlation.qmd) Play 3 showed that growth mindset and support for care-based community interventions go together (*ρ* = .42). The team's report went one step further with a regression, and this play goes one step further still by adding **gender** as a third variable, the way their Figure 3 did: one line for women and one for men. The question becomes: does growth mindset predict support for care-based interventions, and is that relationship the same for women and men?\n\n#### Step 1: Import, score, and make gender a factor\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsafetydata <- read.csv(\"data/safety_data.csv\") |>\n  mutate(across(where(is.numeric), ~ replace(.x, .x %in% c(-99, -50), NA))) |>\n  mutate(GROWTH = rowMeans(cbind(FIXEDPERSON1_BASIC, FIXEDPERSON2_DIFF, FIXEDPERSON4_OLD, FIXEDPERSON_CERTAIN,\n                                 7 - FIXEDPERSON3_CHANGE_R, 7 - FIXEDPERSON_ALL_R,\n                                 7 - FIXEDPERSON_ALWAYS_R, 7 - FIXEDPERSON_MATTER_R), na.rm = TRUE)) |>\n  filter(GENDER %in% c(0, 1)) |>                                             # two gender groups for the third variable\n  mutate(GENDER = factor(GENDER, levels = c(0, 1), labels = c(\"Women\", \"Men\"))) |>\n  filter(!is.na(GROWTH), !is.na(EFFECT_CARE_COMM))\n\nnrow(safetydata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 68\n```\n\n\n:::\n\n```{.r .cell-code}\nsafetydata |> count(GENDER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  GENDER  n\n1  Women 44\n2    Men 24\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: Suchdeve et al. (2025); Relate 2 Variables (Play 3)\n#explanation: the same composite as the correlation chapter; GENDER becomes a labeled factor with women first, so the regression's gender slope reads \"men compared with women\"\n```\n:::\n\n\n#### Step 2: Look: one line per gender\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot3_care_growth_gender_scatter <- ggplot(safetydata, aes(x = GROWTH, y = EFFECT_CARE_COMM, color = GENDER, fill = GENDER)) +\n  geom_jitter(width = 0.05, height = 0.15, alpha = 0.6, size = 2) +\n  geom_smooth(method = \"lm\", alpha = 0.15) +\n  scale_x_continuous(breaks = 1:6, limits = c(1, 6)) +\n  scale_y_continuous(breaks = 1:6, limits = c(0.7, 6.3),\n                     labels = c(\"Strongly\\ndisagree\", \"Disagree\", \"Slightly\\ndisagree\", \"Slightly\\nagree\", \"Agree\", \"Strongly\\nagree\")) +\n  scale_color_manual(values = c(\"Women\" = \"#8d14c1\", \"Men\" = \"#f4b400\")) +\n  scale_fill_manual(values = c(\"Women\" = \"#8d14c1\", \"Men\" = \"#f4b400\")) +\n  labs(x = \"Growth mindset (1 = fixed, 6 = growth)\",\n       y = \"Community-based interventions are\\nthe most effective way to achieve safetydata\",\n       color = \"Gender\", fill = \"Gender\",\n       title = \"Growth mindset and care-based support, by gender\") +\n  theme_bw(base_size = 13) +\n  theme(legend.position = \"top\")\n\nplot3_care_growth_gender_scatter\n```\n\n::: {.cell-output-display}\n![Figure 3. Support for care-based community interventions against growth mindset, by gender (Cohort 11 community safetydata data, n = 68). Points are jittered; each line is the line of best fit for that gender, with its 95% confidence band.](regression_files/figure-html/plot3-care-growth-gender-scatter-1.png){fig-alt='A scatterplot with growth mindset on the x axis and agreement that community-based interventions are the most effective way to achieve safetydata on the y axis. Points and two rising lines of best fit, purple for women and gold for men, with overlapping confidence bands; both lines slope upward at a similar angle.' width=672}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot3_care_growth_gender_scatter.png\", plot = plot3_care_growth_gender_scatter, width = 8, height = 5, dpi = 300)\n\n#source: Visualize a Relationship (Play 2)\n#explanation: color = GENDER inside aes() gives each gender its own points and its own geom_smooth() line; the two lines rising together is what \"the relationship is the same for women and men\" looks like\n```\n:::\n\n\nThe two lines rise at almost the same angle and their bands overlap along their whole length. That picture predicts what the regression will say: a growth-mindset slope that matters, and a gender difference that does not.\n\n#### Step 3: The regression with two predictors\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# regmodel3: support for care-based interventions predicted by GROWTH and GENDER\nregmodel3 <- lm(EFFECT_CARE_COMM ~ GROWTH + GENDER, data = safetydata)\nsummary(regmodel3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = EFFECT_CARE_COMM ~ GROWTH + GENDER, data = safetydata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.7663 -0.6097  0.1350  0.6319  1.6987 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   2.0848     0.6133   3.399  0.00116 ** \nGROWTH        0.6114     0.1365   4.479  3.1e-05 ***\nGENDERMen     0.2867     0.2583   1.110  0.27123    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9863 on 65 degrees of freedom\nMultiple R-squared:  0.2359,\tAdjusted R-squared:  0.2123 \nF-statistic: 10.03 on 2 and 65 DF,  p-value: 0.0001596\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: https://www.datacamp.com/tutorial/multiple-linear-regression-r-tutorial\n#explanation: one continuous predictor and one factor; the GENDERMen row is the difference between men and women at the same level of growth mindset\n```\n:::\n\n\nRead the two predictor rows. `GROWTH` is the slope: for each one-point increase in growth mindset, support for care-based interventions rises by about half a point on the 1-to-6 scale, holding gender constant. `GENDERMen` is the gender difference *at the same growth mindset*: positive means men a little higher, but its p-value says the difference could easily be zero. `Multiple R-squared` is the share of the variation in support that the two predictors explain together.\n\n#### Step 4: Check the residuals, not the outcome\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot4_care_residuals_histogram <- ggplot(data.frame(residual = resid(regmodel3)), aes(x = residual)) +\n  geom_histogram(bins = 15, fill = \"#005a43\", color = \"white\") +\n  labs(x = \"Residual (actual score minus predicted score)\", y = \"Number of people\") +\n  theme_bw()\nplot4_care_residuals_histogram\n```\n\n::: {.cell-output-display}\n![Figure 4. Histogram of the residuals from the two-predictor model. Roughly bell-shaped, with a slightly longer left tail.](regression_files/figure-html/plot4-care-residuals-histogram-1.png){fig-alt='A histogram of regression residuals centered on zero, roughly symmetric, with a few more values on the negative side.' width=576}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot4_care_residuals_histogram.png\", plot = plot4_care_residuals_histogram, width = 8, height = 5, dpi = 300)\n\nshapiro.test(resid(regmodel3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  resid(regmodel3)\nW = 0.96869, p-value = 0.08486\n```\n\n\n:::\n\n```{.r .cell-code}\n#explanation: the outcome is a single 1-to-6 item and is not normal; the regression does not need it to be. What it needs is roughly normal residuals, and these pass\n```\n:::\n\n\nThis is the point the Analysis Map's regression box makes: `EFFECT_CARE_COMM` is one Likert item, and its own histogram is nothing like a bell, yet the residuals are acceptable, so the model stands. Had the residual histogram shown a long tail or two humps, the fix would be a different model, not a different outcome.\n\n#### Step 5: Report it, and compare with the published result\n\n\n\n> A multiple linear regression (n = 68) showed that growth mindset was positively associated with the belief that community-based interventions are the most effective way to achieve community safety (*b* = 0.61, *p* < .001), after accounting for gender. Men and women did not differ at the same level of growth mindset (*b* = 0.29, *p* = .271). The model explained 24% of the variation in support (*R*² = .24) (Figure 3).\n\nSuchdeve et al. (2025) reported *b* = .57 for growth mindset with perceived community safety as the second predictor, in a sample of 54; here the slope is 0.61 with gender as the second predictor, in a sample of 68. Same data, same direction, same size of effect, with a different second predictor and slightly different exclusion rules: that is what a result that holds up looks like, and the small difference is a reminder to say in Methods exactly whom you excluded and why.\n\n::: callout-tip\n## Go: a slope for each group is an interaction, and that is a different model\n\nFigure 3 draws a separate line for women and men, but the model in Step 3 fits **one** slope for growth mindset and shifts the line up or down by gender. That is the right model when the lines are parallel, as they are here. If the lines had crossed or fanned apart, the question would be whether the *slope* differs by gender, which is an **interaction** (`GROWTH * GENDER` in the formula). Interactions are beyond this playbook; if your plot shows clearly non-parallel lines, bring it to your peer mentor and/or Dr. Shane.\n:::\n\n::: {.callout-warning}\n## Caution: Don't cut your score into two groups\n\nIt is tempting to turn a score into \"high\" and \"low\" (or 0 and 1) and then run a regression on the 0s and 1s. Don't. You throw away most of the information in your score, the cut point is arbitrary, and small groups give unstable results. Keep your outcome as a score and use `lm()`. If your outcome really *is* a category (yes or no), `lm()` is the wrong tool: you need a logistic regression, which is not covered in this playbook. Talk to your peer mentor and/or Dr. Shane.\n:::\n\n\n\n## 🏈 The Lab {#sec-regression-lab}\n\nYou watched the play above with the simulated `pregnancydata` dataset (Pass 1). Now run three plays yourself with the **lab dataset**, a survey about what people believe about mental health.\n\n:::::: {.ref .ref-tip}\n::: ref-face\n![](images/ref.svg){fig-alt=\"Ref the raccoon\"}\n:::\n\n::: ref-say\n**Ref's kickoff.** This lab is not graded, so I am here to help you check your own work. Try each play **before** you open my check or the solution. If your answer does not match, that is not a penalty. It is how you find out what to fix.\n:::\n::::::\n\n| Lab play | What is new |\n|----------------|------------------------------------------------|\n| Draw Left | one predictor: read a slope, a p-value, and R-squared |\n| Draw Right | add a **binary** predictor (two groups) |\n| Draw Middle | add a **dummy-coded** predictor (five groups) |\n\nAll three plays use the same outcome: positive mental well-being (`WELLBEING`, the average of 8 items, 1 to 5). The first predictor is always perceived social support (`SUPPORT`, the average of 8 items, 1 to 5).\n\n**Before you start**\n\n1.  Open your RStudio Project and your lab `.qmd` file.\n2.  Load the clean lab data by running this chunk. It runs the cleaning script you built in the earlier labs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"lab_prep.R\")   # creates mh_clean\nnrow(mh_clean)         # how many people are in the clean dataset?\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's check: how many rows?\n\n`nrow(mh_clean)` should be **188**.\n:::\n\n### Lab Play 1 (simple regression): Draw Left, relate social support to well-being\n\n**Research question:** Do people with more social support (`SUPPORT`) report higher well-being (`WELLBEING`)?\n\n**Your task:** Make a scatterplot with `SUPPORT` on the x axis and `WELLBEING` on the y axis, with a line of best fit. Then run the simple regression with `lm()` and `summary()`. Write down the slope for `SUPPORT`, its p-value, R-squared, and the number of people in the model.\n\n::: {.callout-tip collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's check: what should you get?\n\n\n::: {.cell}\n\n:::\n\n\n-   Your line of best fit should go **up**: more support, higher well-being.\n-   Slope for `SUPPORT`: **b = 0.40**. For every one point higher in social support, predicted well-being is 0.40 points higher.\n-   p-value: **p < .001**, so the relationship is statistically significant.\n-   R-squared: **0.16**. Social support explains about 16% of the differences in well-being.\n-   People in the model: **n = 188**.\n:::\n\n::: {.callout-note .gray collapse=\"true\"}\n## 👀 See the solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mh_clean,\n       mapping = aes(x = SUPPORT, y = WELLBEING)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\") +\n  xlab(\"Perceived social support (1 to 5)\") +\n  ylab(\"Positive mental well-being (1 to 5)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Figure 5. Social support and well-being in the lab dataset. The line is a linear line of best fit.](regression_files/figure-html/lab-solution-play1-1.png){fig-alt='A scatterplot with social support on the x axis and well-being on the y axis. The line of best fit slopes upward.' width=672}\n:::\n\n```{.r .cell-code}\n# regmodel4: WELLBEING predicted by SUPPORT alone\nregmodel4 <- lm(WELLBEING ~ SUPPORT, data = mh_clean)\n\nsummary(regmodel4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = WELLBEING ~ SUPPORT, data = mh_clean)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.63903 -0.39229  0.01805  0.43951  1.69087 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.92051    0.22781    8.43 9.33e-15 ***\nSUPPORT      0.40436    0.06717    6.02 9.13e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6194 on 186 degrees of freedom\nMultiple R-squared:  0.163,\tAdjusted R-squared:  0.1585 \nF-statistic: 36.24 on 1 and 186 DF,  p-value: 9.129e-09\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(regmodel4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 188\n```\n\n\n:::\n:::\n\n:::\n\n### Lab Play 2 (multiple regression): Draw Right, add racialized identity as a binary predictor\n\n**Research question:** After we account for social support, does well-being differ between People of Color and White respondents?\n\nThe survey asked one select-all question about racial/ethnic identity. In [Transforming Your Data](dplyr.qmd) you combined its checkbox columns (`RACIALIZED_1` to `RACIALIZED_99`) into two variables, and `lab_prep.R` now carries both:\n\n| Variable | Groups |\n|----|----|\n| `RACIALIZED_6CAT` | White, Asian, Black, Hispanic or Latine, Another identity, Two or more (a factor) |\n| `RACIALIZED_01` | 0 = racialized as white, 1 = racialized as a person of color (everyone who checked any other box, including \"Two or more\") |\n\nThe name is `RACIALIZED`, not `RACE`, on purpose: the survey did not measure a trait inside the person, it recorded how people are sorted and sort themselves within a system of racial classification ([Data Equity](data-equity.qmd)). Read every coefficient below that way: \"people racialized as Black,\" not \"being Black.\"\n\nA **binary** predictor has two groups, coded 0 and 1. **Your task:**\n\n1.  Check the variable before you use it: `count(RACIALIZED_6CAT, RACIALIZED_01)`. Every White row should have a 0, every other row a 1, and Prefer not to say should be `NA`.\n2.  Run `lm(WELLBEING ~ SUPPORT + RACIALIZED_01)`.\n3.  Read the `RACIALIZED_01` row. Because the variable is 0/1, its slope is the difference between the group coded 1 and the group coded 0, at the same level of social support.\n\n::: {.callout-tip collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's check: what should you get?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| RACIALIZED_01|  n|\n|-------------:|--:|\n|             0| 94|\n|             1| 91|\n|            NA|  3|\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|              | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:-------------|--------:|----------:|-------:|------------------:|\n|(Intercept)   |    2.095|      0.228|   9.205|              0.000|\n|SUPPORT       |    0.399|      0.066|   6.056|              0.000|\n|RACIALIZED_01 |   -0.305|      0.089|  -3.429|              0.001|\n\n\n:::\n:::\n\n\n-   The row is named `RACIALIZED_01`, and there is only one row for it, because a 0/1 variable needs only one slope. The group coded 0 (White) is the comparison group.\n-   **b = -0.30, p < .001**: at the same level of social support, People of Color scored 0.30 points lower in well-being than White respondents.\n-   `SUPPORT` is still positive and significant (b = 0.40, p < .001).\n-   People in the model: **n = 185**. That is 3 fewer than in Lab Play 1, because 3 people chose \"Prefer Not To Say\".\n:::\n\n::: {.callout-note .gray collapse=\"true\"}\n## 👀 See the solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmh_clean |>\n  count(RACIALIZED_6CAT, RACIALIZED_01)   # ALWAYS check a variable before you model it\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 3\n  RACIALIZED_6CAT    RACIALIZED_01     n\n  <fct>                      <dbl> <int>\n1 White                          0    94\n2 Asian                          1    19\n3 Black                          1    31\n4 Hispanic or Latine             1    17\n5 Another identity               1     5\n6 Two or more                    1    19\n7 <NA>                          NA     3\n```\n\n\n:::\n\n```{.r .cell-code}\n# regmodel5: regmodel4 + RACIALIZED_01 (two groups)\nregmodel5 <- lm(WELLBEING ~ SUPPORT + RACIALIZED_01, data = mh_clean)\n\nsummary(regmodel5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = WELLBEING ~ SUPPORT + RACIALIZED_01, data = mh_clean)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.78946 -0.41134  0.03634  0.45888  1.53404 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    2.09510    0.22760   9.205  < 2e-16 ***\nSUPPORT        0.39867    0.06583   6.056 7.82e-09 ***\nRACIALIZED_01 -0.30462    0.08883  -3.429 0.000749 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.604 on 182 degrees of freedom\n  (3 observations deleted due to missingness)\nMultiple R-squared:  0.2106,\tAdjusted R-squared:  0.2019 \nF-statistic: 24.27 on 2 and 182 DF,  p-value: 4.53e-10\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(regmodel5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 185\n```\n\n\n:::\n:::\n\n:::\n\n::: {.callout-warning}\n## Caution: A group difference is not an explanation\n\nThis model tells you that two groups differ. It does not tell you why. In public health, differences between racial and ethnic groups point to differences in people's conditions and experiences (for example, discrimination or access to care). They are not caused by the identity itself. Write \"scored lower than\", and use your literature review to discuss why. To see more on who is counted, who decides, and who benefits when we compare groups, read [Data Equity](data-equity.qmd).\n:::\n\n### Lab Play 3 (multiple regression): Draw Middle, add racialized identity as a six-group predictor\n\n**Research question:** Two groups hide a lot. Does the difference in well-being look the same for every racial/ethnic group?\n\nA predictor with three or more groups has to be **dummy coded**: one 0/1 column for every group except the comparison group. You do not need to make those columns. When the predictor is a `factor()`, `lm()` makes them for you, and you get one row in the output for each group (compared with the first level).\n\n**Your task:**\n\n1.  Count the people in each `RACIALIZED_6CAT` group with `count()`. Notice which groups are small.\n2.  Check that `RACIALIZED_6CAT` is a factor whose first level is `\"White\"`: `levels(mh_clean$RACIALIZED_6CAT)`. The first level is the comparison group.\n3.  Run `lm(WELLBEING ~ SUPPORT + RACIALIZED_6CAT)`, make a histogram of the residuals, and write one sentence that reports the result.\n\n::: {.callout-tip collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's check: what should you get?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|RACIALIZED_6CAT    |  n|\n|:------------------|--:|\n|White              | 94|\n|Asian              | 19|\n|Black              | 31|\n|Hispanic or Latine | 17|\n|Another identity   |  5|\n|Two or more        | 19|\n|NA                 |  3|\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|                                  | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:---------------------------------|--------:|----------:|-------:|------------------:|\n|(Intercept)                       |    2.062|      0.234|   8.800|              0.000|\n|SUPPORT                           |    0.409|      0.068|   6.019|              0.000|\n|RACIALIZED_6CATAsian              |   -0.348|      0.153|  -2.273|              0.024|\n|RACIALIZED_6CATBlack              |   -0.314|      0.127|  -2.484|              0.014|\n|RACIALIZED_6CATHispanic or Latine |   -0.174|      0.160|  -1.084|              0.280|\n|RACIALIZED_6CATAnother identity   |   -0.180|      0.280|  -0.644|              0.520|\n|RACIALIZED_6CATTwo or more        |   -0.395|      0.155|  -2.551|              0.012|\n\n\n:::\n:::\n\n\n-   You should see **five** `RACIALIZED_6CAT` rows, one for every group except White. R adds the group name to the variable name (`RACIALIZED_6CATAsian`). Each row compares that group with White respondents, at the same level of social support. That is dummy coding, and R did it for you because the variable is a factor.\n-   Asian (b = -0.35, p = .024) and Black (b = -0.31, p = .014) respondents scored significantly lower than White respondents. Hispanic or Latine respondents did not differ significantly (b = -0.17, p = .280). The binary variable in Lab Play 2 hid this.\n-   \"Another identity\" (b = -0.18, p = .520) has only 5 people. With a group this small, a real difference is hard to detect. Report the count, and do not read much into this row.\n-   People in the model: **n = 185**. R-squared: **0.22**.\n-   Your residual histogram should be roughly bell-shaped and centered on zero.\n:::\n\n::: {.callout-note .gray collapse=\"true\"}\n## 👀 See the solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmh_clean |>\n  count(RACIALIZED_6CAT)             # which groups are small?\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n  RACIALIZED_6CAT        n\n  <fct>              <int>\n1 White                 94\n2 Asian                 19\n3 Black                 31\n4 Hispanic or Latine    17\n5 Another identity       5\n6 Two or more           19\n7 <NA>                   3\n```\n\n\n:::\n\n```{.r .cell-code}\nlevels(mh_clean$RACIALIZED_6CAT)     # \"White\" must be first: it is the comparison group\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"White\"              \"Asian\"              \"Black\"             \n[4] \"Hispanic or Latine\" \"Another identity\"   \"Two or more\"       \n```\n\n\n:::\n\n```{.r .cell-code}\n# regmodel6: regmodel4 + RACIALIZED_6CAT (six groups, dummy coded by R)\nregmodel6 <- lm(WELLBEING ~ SUPPORT + RACIALIZED_6CAT, data = mh_clean)\n\nsummary(regmodel6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = WELLBEING ~ SUPPORT + RACIALIZED_6CAT, data = mh_clean)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.79868 -0.45608  0.01717  0.43928  1.53604 \n\nCoefficients:\n                                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                         2.0620     0.2343   8.800 1.17e-15 ***\nSUPPORT                             0.4086     0.0679   6.019 9.79e-09 ***\nRACIALIZED_6CATAsian               -0.3477     0.1530  -2.273   0.0242 *  \nRACIALIZED_6CATBlack               -0.3144     0.1266  -2.484   0.0139 *  \nRACIALIZED_6CATHispanic or Latine  -0.1738     0.1603  -1.084   0.2797    \nRACIALIZED_6CATAnother identity    -0.1802     0.2799  -0.644   0.5204    \nRACIALIZED_6CATTwo or more         -0.3952     0.1549  -2.551   0.0116 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6082 on 178 degrees of freedom\n  (3 observations deleted due to missingness)\nMultiple R-squared:  0.2171,\tAdjusted R-squared:  0.1908 \nF-statistic: 8.229 on 6 and 178 DF,  p-value: 7.214e-08\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(regmodel6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 185\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = data.frame(residual = resid(regmodel6)),\n       mapping = aes(x = residual)) +\n  geom_histogram(bins = 20, fill = \"#005a43\", color = \"white\") +\n  xlab(\"Residual (actual score minus predicted score)\") +\n  ylab(\"Number of people\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Figure 6. Histogram of the residuals from the lab regression.](regression_files/figure-html/lab-solution-play3-1.png){fig-alt='A histogram of regression residuals from the lab dataset, centered on zero and roughly bell-shaped.' width=576}\n:::\n:::\n\n\nA multiple linear regression (n = 185) showed that perceived social support was positively associated with well-being (b = 0.41, p < .001), after accounting for racial/ethnic identity. Compared with White respondents, Asian (b = -0.35, p = .024) and Black (b = -0.31, p = .014) respondents reported lower well-being; Hispanic or Latine respondents (p = .280) and respondents with another identity (n = 5; p = .520) did not differ significantly (R² = .22).\n:::\n\n::: {.callout-warning collapse=\"true\" icon=\"false\"}\n## ![](images/ref-whistle.svg){.ref-mini fig-alt=\"Ref the raccoon blowing his whistle\"} Ref's call: fouls to check if your numbers do not match\n\n-   **Your slope is for the wrong variable** → the outcome goes on the **left** of the `~`. `WELLBEING ~ SUPPORT`, not `SUPPORT ~ WELLBEING`.\n-   **One row named `RACIALIZED_6CAT` with a single slope** → the variable is not a factor. R treated the groups as a score. Rebuild it with `factor()` as in [Transforming Your Data](dplyr.qmd). This gives you a wrong answer without any error message.\n-   **Your comparison group is not White** → R uses the **first** level as the comparison group. If you leave out `levels =`, R sorts the groups by the alphabet.\n-   **A group is missing from `count()`** → look for a typo in `case_when()`. Any answer you do not list becomes `NA`.\n-   **Your n is 188** → that is the number of rows in the dataset, not the number of people in the model. Use `nobs()`.\n-   **`object 'WELLBEING' not found`** → `WELLBEING` and `SUPPORT` are created in `lab_prep.R`. Run `source(\"lab_prep.R\")` first.\n-   **`could not find function \"ggplot\"`** → run your load-library chunk.\n:::\n\n:::::: {.ref .ref-tip}\n::: ref-face\n![](images/ref.svg){fig-alt=\"Ref the raccoon\"}\n:::\n\n::: ref-say\n**Ref's final whistle.** That is the end of the lab. Save your `.qmd`, render it, and back up your `.qmd` and `.R` files to the **R Labs** folder in your ELN before you quit RStudio.\n:::\n::::::\n\n## 🏆 Your Turn {#sec-regression-yourturn}\n\n::: {.callout-note .gray icon=\"false\"}\n## There is no Ref. It's game time, your turn!\n\nNobody has analyzed your team's data before, so there is no answer to check against. Copy the play, change every word that starts with `SWAP`, and use the checklist at the end of this section to check your own work. It is the same checklist your peer mentor and Dr. Shane use.\n:::\n\nOnce you finish all of the R Labs, come back here with **your team's dataset** and run the regression for your relationship research question.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. every categorical predictor must be a factor (skip this if you have none)\nmydata <- cleandata |>                         # cleandata = your cleaned data (Import Data Once); mydata = this analysis\n  mutate(SWAPGROUP = factor(SWAPGROUP,           # SWAP: your categorical predictor\n                                levels = c(1, 2),               # SWAP: its codes\n                                labels = c(\"SWAPLABEL1\", \"SWAPLABEL2\")))  # SWAP: its labels; the FIRST one is the comparison group\n\n# 2. run the model: SWAPOUTCOME ~ SWAPPREDICTOR1 + SWAPPREDICTOR2 + ...\n# regmodel1: SWAP: one line that says what this model predicts and from what\nregmodel1 <- lm(SWAPOUTCOME ~ SWAPPREDICTOR1 + SWAPPREDICTOR2 + SWAPGROUP,   # SWAP every name; regmodel2 for your next model\n                  data = mydata)\n\nsummary(regmodel1)      # slopes (Estimate), p-values (Pr(>|t|)), and R-squared\nnobs(regmodel1)         # the number of people in the model\n\n# 3. check the residuals\nggplot(data = data.frame(residual = resid(regmodel1)),\n       mapping = aes(x = residual)) +\n  geom_histogram(bins = 20) +\n  theme_bw()\n\n# 4. a table for your report\nknitr::kable(summary(regmodel1)$coefficients, digits = 3,\n             caption = \"Table 1. SWAP: a caption that can stand alone.\")\n```\n:::\n\n\nThen write your results sentence. Use this pattern, and say whether your hypothesis was supported.\n\n> A multiple linear regression (n = \\_\\_\\_) showed that \\_\\_\\_\\_\\_\\_ was \\_\\_\\_\\_\\_\\_ (positively / negatively / not significantly) associated with \\_\\_\\_\\_\\_\\_ (b = \\_\\_\\_, p = \\_\\_\\_), after accounting for \\_\\_\\_\\_\\_\\_. The predictors explained \\_\\_\\_% of the variance in \\_\\_\\_\\_\\_\\_ (R² = \\_\\_\\_).\n\n### Checklist for your RD Report and Final Report\n\n::: {.callout-note .gray collapse=\"true\"}\n## Open the regression checklist\n\n<!-- Single source for the regression checklist. Included in Relate 3+ Variables (\"Your Turn\"), and later in the Final Report Checklist page. Edit it here once; every place updates. -->\n\n\n| Criteria | Ask yourself |\n|------------|--------------------------------------------------------|\n| **Right test** | Does the Analysis Map lead here (one continuous outcome, two or more predictors)? |\n| **Missing codes** | Were codes such as -99 and -50 changed to `NA` before the model was run? |\n| **Categorical predictors** | Is every categorical predictor a `factor()` with labels, not a number? Does your text name the comparison group? |\n| **Outcome kept whole** | Is the outcome the full score (not cut into \"high\" and \"low\")? |\n| **Plot first** | Is there a scatterplot of the outcome and your main predictor before the model? |\n| **Model statement** | Does the text say which test was run, the outcome, and every predictor? |\n| **Each predictor** | Do you report *b* and *p* for every predictor, including the ones that were not significant? |\n| **Sample size** | Is *n* reported from `nobs()`, not from the number of rows in the dataset? |\n| **R-squared** | Is R-squared reported and explained in plain words (percent of the differences in the outcome)? |\n| **Residuals** | Is there a histogram of the residuals, and one sentence on its shape? |\n| **Interpretation** | Does the text connect the result to your hypothesis, with \"holding the other predictors constant\"? |\n| **No causal words** | Did you avoid \"causes\", \"leads to\", \"impacts\", and \"effect of\"? |\n| **Table** | Is there a regression table made with `kable()`, with a caption starting \"Table 1.\"? |\n| **Inline numbers** | Do the numbers in your sentences come from inline R code, not typed by hand? |\n| **Referenced in text** | Does your results paragraph point to the table and the figure? |\n\n:::\n\n<!-- Single source for the collapsed final-whistle reminder at the END of every coding chapter (7 onward). Edit here only. The full routine lives in find-the-ref.qmd (Ref's Quick Checklist). -->\n\n::: {.callout-note .gray collapse=\"true\" icon=\"false\"}\n## ![](images/ref-whistle.svg){.ref-mini fig-alt=\"Ref the raccoon blowing his whistle\"} Ref's final whistle: before you quit RStudio\n\n**Save → Render → Back up to ELN → Quit, Don't Save workspace.** Details: [Ref's Quick Checklist](find-the-ref.qmd#sec-ref-checklist).\n:::\n\n",
    "supporting": [
      "regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}