{
  "hash": "2b2c47579fb92c809195afa19d60f320",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Compare 2 Groups\"\nsubtitle: \"Independent-samples t-test (normal) and Mann-Whitney U (non-normal)\"\nauthor:\n  - Anna Vishnevetsky\n  - Yoomin (Ashley) Kim\n  - Erica Sava\nabstract: |\n  This chapter is the Analysis Map's \"compare 2 groups\" row: two groups of different people and one continuous outcome. Researchers learn when the independent-samples t-test is the right test and when it is not (the paired design is a different chapter), how to look at the two groups before testing (a density plot made in one line with ggpubr, or a violin and raincloud plot built layer by layer in ggplot2), how to check the assumptions and choose between the Welch t-test (normal data) and the Mann-Whitney U test (data that are not normal, or a single rating), how to report the result with an effect size, and how to catch the data problems that show up before any test can run. Two Plays use synthetic versions of real FRI team datasets (Veggie Meter skin-carotenoid scores by biological sex, and cooking self-efficacy composites by gender before a cooking workshop) and a third uses the Cohort 10 health status data to compare self-rated health by minoritized status with the Mann-Whitney U test. The Lab runs the same comparisons on the lab dataset with Ref's checks, and Your Turn gives the template for the team dataset.\nkeywords:\n  - t-test\n  - independent samples\n  - Welch\n  - Mann-Whitney U\n  - Wilcoxon rank-sum\n  - Cohen's d\n  - ggpubr\n  - violin plot\n  - raincloud plot\ndate: 10.04.2026\ndate-format: \"MM.DD.YYYY\"\nformat: html\neditor: visual\nexecute:\n  warning: false\n  message: false\n  cache: false\n---\n\n<!-- Single source for the collapsed kickoff reminder at the START of every coding chapter (7 onward). Edit here only. The full routine lives in find-the-ref.qmd (Ref's Quick Checklist). -->\n\n::: {.callout-note .gray collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's kickoff: find the Ref before you code\n\n**Open Project → Open `.qmd` → Run load-library chunk → Run All Chunks Above → code.** If anything looks wrong, use [Ref's Quick Checklist](find-the-ref.qmd#sec-ref-checklist).\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Resources: `ggpubr` (new in this chapter), `ggplot2`, and `see`\n\n`ggpubr` is ggplot2 with the layers already assembled: one function call gives a finished, publication-style plot. Use it when you want the standard picture fast. Drop back to ggplot2 when you want to control every layer.\n\n-   [`ggpubr` home page](https://rpkgs.datanovia.com/ggpubr/) and the [`ggpubr` cheat sheet (PDF)](https://rpkgs.datanovia.com/ggpubr/ggpubr-cheatsheet.pdf)\n-   [`ggdensity()`](https://rpkgs.datanovia.com/ggpubr/reference/ggdensity.html): the density plot used in Play 1\n-   [`ggviolin()`](https://rpkgs.datanovia.com/ggpubr/reference/ggviolin.html) and [`ggboxplot()`](https://rpkgs.datanovia.com/ggpubr/reference/ggboxplot.html): one-line violin and box plots\n-   [`geom_violin()` in ggplot2](https://ggplot2.tidyverse.org/reference/geom_violin.html), used in Play 2\n-   [`geom_violinhalf()` in the `see` package](https://easystats.github.io/see/reference/geom_violinhalf.html), the half violin of a raincloud plot\n-   [Raincloud plots with ggplot2 (Cédric Scherer)](https://z3tt.github.io/Rainclouds/) and [Allen et al. (2019), the raincloud paper](https://doi.org/10.12688/wellcomeopenres.15191.2)\n-   [R for Data Science, Ch. 10: Exploratory data analysis](https://r4ds.hadley.nz/eda.html) (distributions by group)\n:::\n\n::: callout-important\n## Important: two packages to install once\n\n`ggpubr` and `see` are on the `install.R` list ([R Packages](library.qmd)). If `library(ggpubr)` says `there is no package called 'ggpubr'`, source `install.R` again.\n:::\n\n## When is this the right test?\n\nYou have **two groups of different people** and **one continuous outcome**, and you want to know whether the two groups differ on average. Three examples: 1) male and female participants on their Veggie Meter score, 2) people who have had mental health treatment and people who have not on their well-being, and 3) People of Color and White participants on their experiences of harm in health care. On [The Analysis Map](analysis-map.qmd) that is the *compare 2 groups* row, and the test is the **independent-samples t-test**.\n\nTwo things decide whether you are on this row:\n\n-   **The group variable has exactly two levels.** Usually it is a `_01` variable from the survey (`TREATED_01`, `KNOWS_01`) or a `_01CAT` you made in [Transforming Your Data](dplyr.qmd) (`RACIALIZED_01`, `DISTRESS_01`). Three or more groups is the next row, [Compare 3+ Groups](ANOVA.qmd).\n-   **The two groups are different people.** If the same people were measured twice, before and after something, that is a **paired** design: the differences live *within* each person, and the test is the paired t-test ([Compare 1 Group, Pre/Post](violin.qmd), for Teams 3 and 5). Running an independent-samples test on pre/post data is the most common wrong turn on the map, so decide this first.\n\nThe outcome should be a score, not a category: a composite from 1 to 5, a Veggie Meter number, an age. If the outcome is yes/no, you need a different test (a chi-square), and your peer mentor and/or Dr. Shane can point you to it.\n\nOnce you are on this row, the shape of the outcome picks the test, exactly as the two lines in each Analysis Map box say:\n\n| Test | Use it when | R function | Report |\n|----|----|----|----|\n| [**Independent-samples t-test** (parametric)]{.normal} | the outcome is roughly normal in each group, or each group has 30 or more people | `t.test()` | *M*, *SD*, *t*(df), *p*, Cohen's *d* |\n| [**Mann-Whitney U test** (non-parametric)]{.nonnormal} | the outcome is skewed, a group is small, or the outcome is a single rating with a few levels (1 to 5) | `wilcox.test()` | *Mdn*, *U*, *p*, *r* |\n\nPlay 1 and Play 2 are the [parametric]{.normal} case; Play 3 is the [non-parametric]{.nonnormal} case. [Compare 1 Group, Pre/Post](violin.qmd) and [Compare 3+ Groups](ANOVA.qmd) follow the same two-line structure.\n\n## 📋 The Play\n\nTwo plays, two teams, two ways to draw the same picture. Play 1 uses `ggpubr`, which makes the standard plot in one call. Play 2 builds a violin and raincloud plot in `ggplot2`, layer by layer. The test is the same in both.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)   # dplyr, tidyr, ggplot2\nlibrary(readxl)\nlibrary(psych)       # scoreItems() for the composites in Play 2\nlibrary(ggpubr)      # ggdensity() in Play 1\nlibrary(see)         # geom_violinhalf() in Play 2\nlibrary(knitr)\n```\n:::\n\n\n### Play 1 ([independent-samples t-test]{.normal}): compare male and female participants on Veggie Meter score, with a `ggpubr` density plot\n\n::: {.callout-note collapse=\"true\"}\n## About the dataset: `veggiescore_SYNTHETIC.xlsx`\n\nIn fall 2025 a team in the FRI Public Health stream measured fruit and vegetable intake with the **Veggie Meter®**, a device that estimates skin carotenoids from a finger scan and returns a score of roughly 100 to 800. The convenience sample was Binghamton University students on campus and Broome County residents at a farmers market, scanned in September and October 2025.\n\nThe file in this chapter is **synthetic**: every row was generated by a seeded script (`make_play_datasets.py`) and no row describes a real person, which is why it can be published with the playbook. It keeps what makes the real export a good teaching case: the same variables, the same approximate group means and spreads (male participants scoring higher on average, with a small to medium difference), the same share of declines and blanks on `SEX`, and the same kinds of junk in `VEGGIESCORE` that the real scanner sheet had (two typed words, a scanner read-out pasted twice, a handful of impossible numbers). What differs: the real file had 309 rows with the team's actual participant passwords, timestamps, and Qualtrics metadata, which are not here, and the real `CONSUMPTION` and `LOCATION` answers were replaced by seeded ones with the same distribution. The t-test result is of the same size and direction as the team's, not the team's number.\n:::\n\n::: callout-important\n## Important: biological sex is not gender identity\n\nBiological sex and gender identity are not the same thing, and the standardized class variables used in this playbook measure gender identity (`GENDER`, [Name and Recode Variables in Qualtrics](qualtrics.qmd)), not biological sex. This study used **biological sex** because the Veggie Meter's reference distributions are reported by biological sex, so the team needed the same variable to compare their sample with the norms. The variable is therefore named `SEX`, coded 0 = male and 1 = female, and the groups are called male and female participants below, not men and women, which are gender terms. When you compare groups in your own data, say which construct you measured and why.\n:::\n\n#### Step 1: Import and look before you clean\n\n\n::: {.cell}\n\n```{.r .cell-code}\nveggiedata <- read_excel(\"data/veggiescore_SYNTHETIC.xlsx\")\n\nnrow(veggiedata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 300\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(veggiedata$VEGGIESCORE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Length     Class      Mode \n      300 character character \n```\n\n\n:::\n\n```{.r .cell-code}\nveggiedata |> count(SEX)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n    SEX     n\n  <dbl> <int>\n1   -99     6\n2     0   116\n3     1   154\n4    NA    24\n```\n\n\n:::\n:::\n\n\nTwo problems are visible already. `summary()` of `VEGGIESCORE` prints `Length` and `Class :character` instead of a minimum and a maximum: the column came in as **text**, because a few cells contain words ([Import Data Once](import-once.qmd), Lab Play 5). And `SEX` has values other than 0 and 1: `-99` (prefer not to say) and `NA` (skipped).\n\nThese problems are not invented for the exercise. The real export from the Veggie Meter team had exactly these flaws: the scanner's results were typed into a spreadsheet by hand, so a few cells held a word instead of a number, a scanner read-out was pasted into the score column, and a handful of failed scans produced impossible numbers. The synthetic file reproduces each kind of flaw (with made-up values) so that you practice the cleaning decisions on the kind of mess a real team dataset has.\n\n#### Step 2: Clean, and decide the rules out loud\n\n\n::: {.cell}\n\n```{.r .cell-code}\nveggiedata <- veggiedata |>\n  mutate(VEGGIESCORE = as.numeric(VEGGIESCORE))      # words become NA; numbers stay numbers\n\nsummary(veggiedata$VEGGIESCORE)                           # now you can see the range\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.      NA's \n1.000e+00 2.430e+02 3.120e+02 2.343e+07 3.740e+02 6.465e+09        24 \n```\n\n\n:::\n:::\n\n\nNow `summary()` shows the range, and it is wrong at both ends: a minimum of 1 and a maximum in the billions. No skin-carotenoid scan produces those numbers; they are the pasted read-out and the failed scans described above. The cleaning rule has to come from what the instrument can measure, not from the data: the Veggie Meter's plausible range is about 100 to 800, so keep scores in that range. And a two-group test needs two groups, so keep only the people with `SEX` coded 0 or 1. Write both rules in your Methods, with the number of people each one removed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nveggiedata_clean <- veggiedata |>\n  filter(VEGGIESCORE >= 100, VEGGIESCORE <= 800,      # plausible scores only\n         SEX %in% c(0, 1)) |>                          # the two groups (drops -99 and NA)\n  mutate(SEX = factor(SEX, levels = c(0, 1), labels = c(\"Male\", \"Female\")))\n\nnrow(veggiedata_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 238\n```\n\n\n:::\n\n```{.r .cell-code}\nveggiedata_clean |>\n  group_by(SEX) |>\n  summarise(n = n(), mean = mean(VEGGIESCORE), sd = sd(VEGGIESCORE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  SEX        n  mean    sd\n  <fct>  <int> <dbl> <dbl>\n1 Male     105  323.  91.3\n2 Female   133  298.  80.6\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: R4DS Ch. 3 https://r4ds.hadley.nz/data-transform.html\n#explanation: text scores become numbers; impossible scores and people without a group are removed; the group variable becomes a labeled factor\n```\n:::\n\n\nWrite the rule in your Methods: \"Scores outside the instrument's range (100 to 800) were excluded (n = 9), as were participants who did not report biological sex (n = 30).\" The numbers you excluded are part of the result.\n\n#### Step 3: Look at the two groups: `ggdensity()`\n\nA **density plot** is a smoothed histogram. With two groups it shows, in one picture, whether the groups overlap and where their centers sit. In `ggpubr` it is one call, with the group mean drawn as a dashed line and every person as a tick on the axis (`rug = TRUE`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot1_veggiescore_sex_density <- ggdensity(veggiedata_clean, x = \"VEGGIESCORE\",\n                             color = \"SEX\", fill = \"SEX\",\n                             palette = c(\"#ff8c6b\", \"#e8a7d0\"),\n                             add = \"mean\", rug = TRUE,\n                             xlab = \"Veggie Meter score\", ylab = \"Density\",\n                             title = \"Veggie Meter scores by biological sex\") +\n  scale_x_continuous(breaks = seq(100, 800, by = 100))\n\nplot1_veggiescore_sex_density\n```\n\n::: {.cell-output-display}\n![Figure 1. Veggie Meter scores for male and female participants (synthetic data, n = 238). Dashed lines are group means; ticks along the x axis are individual scores.](compare2groups_files/figure-html/plot1-veggiescore-sex-density-1.png){fig-alt='Two overlapping density curves of Veggie Meter scores, orange for male and pink for female participants. Both are roughly bell shaped. The male curve and its dashed mean line sit slightly to the right of the female curve.' width=768}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot1_veggiescore_sex_density.png\", plot = plot1_veggiescore_sex_density,\n       width = 8, height = 5, dpi = 300)\n\n#source: ggpubr documentation https://rpkgs.datanovia.com/ggpubr/reference/ggdensity.html\n#explanation: one density curve per group, with the mean of each group as a dashed line and each person's score as a rug tick\n```\n:::\n\n\nThe curves overlap a lot, and the male participants' mean is a little to the right. That is what a small difference looks like. The test tells you whether a difference this size is more than chance would produce.\n\n#### Step 4: Check the assumptions\n\nThe t-test assumes the outcome is roughly normal **within each group** (less important when each group has 30 or more people) and does not assume equal variances if you use the Welch version, which is R's default. Check normality the way [Describe Your Variables](describe.qmd) showed: a histogram or Q-Q plot per group and the Shapiro-Wilk test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nveggiedata_clean |>\n  group_by(SEX) |>\n  summarise(shapiro_p = shapiro.test(VEGGIESCORE)$p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  SEX    shapiro_p\n  <fct>      <dbl>\n1 Male       0.379\n2 Female     0.200\n```\n\n\n:::\n:::\n\n\nBoth p-values are above .05, so there is no evidence against normality in either group. If one had been below .05 with a small group, you would run the non-parametric test in Step 6 as well and report both.\n\n#### Step 5: The independent-samples t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ttestmodel1: VEGGIESCORE by SEX (Welch t-test)\nttestmodel1 <- t.test(VEGGIESCORE ~ SEX, data = veggiedata_clean)   # Welch t-test (var.equal = FALSE is the default)\nttestmodel1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  VEGGIESCORE by SEX\nt = 2.1961, df = 209.01, p-value = 0.02919\nalternative hypothesis: true difference in means between group Male and group Female is not equal to 0\n95 percent confidence interval:\n  2.543265 47.169016\nsample estimates:\n  mean in group Male mean in group Female \n            322.9238             298.0677 \n```\n\n\n:::\n\n```{.r .cell-code}\n#source: https://www.datacamp.com/tutorial/t-tests-r-tutorial\n#explanation: the formula means \"VEGGIESCORE split by SEX\"; Welch's version does not assume the two groups have equal spread\n```\n:::\n\n\nRead four things from the output: the two group means at the bottom; **t**, the difference in means divided by its standard error; **df**, the degrees of freedom (Welch's are not a whole number); and the **p-value**. Here p is below .05, so the difference is unlikely to be chance alone.\n\n#### Step 6: Effect size, and a check with the Mann-Whitney U\n\nA p-value says whether the difference is detectable, not whether it is big. **Cohen's d** is the difference in means in standard-deviation units: about 0.2 is small, 0.5 medium, 0.8 large.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohens_d <- function(x, y) (mean(x) - mean(y)) / sqrt((var(x) + var(y)) / 2)\n\nmale   <- veggiedata_clean$VEGGIESCORE[veggiedata_clean$SEX == \"Male\"]\nfemale <- veggiedata_clean$VEGGIESCORE[veggiedata_clean$SEX == \"Female\"]\ncohens_d(male, female)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2887757\n```\n\n\n:::\n\n```{.r .cell-code}\nwilcox.test(VEGGIESCORE ~ SEX, data = veggiedata_clean)   # Mann-Whitney U (R calls it the Wilcoxon rank sum test); Play 3 explains it\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  VEGGIESCORE by SEX\nW = 7938, p-value = 0.07016\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: Cohen (1988); R documentation ?wilcox.test\n#explanation: d is the mean difference divided by the pooled standard deviation; the Mann-Whitney U test compares the groups by rank, without assuming normality\n```\n:::\n\n\nThe two tests disagree: the Welch t-test is significant (*p* = .029) and the Mann-Whitney U test is not (*p* = .070). That is not a mistake. The t-test compares means and the Mann-Whitney U test compares the whole distributions by rank, and when the data are close to normal the t-test has more power to detect a difference. With a small effect (*d* = 0.29, about a quarter of a standard deviation) and about 240 people, the evidence sits near the .05 threshold, so a slightly less powerful test lands on the other side of it. Report the test your assumption checks point to (here the Shapiro-Wilk results support the t-test), name the effect size, and do not describe a *p* of .029 as strong evidence of a large difference.\n\n\n\n#### Step 7: Report it\n\nOne sentence with the means, the test, and the effect size, plus the figure. In APA style:\n\n> Male participants (*M* = 322.9, *SD* = 91.3, *n* = 105) had higher Veggie Meter scores than female participants (*M* = 298.1, *SD* = 80.6, *n* = 133), Welch *t*(209.0) = 2.20, *p* = .029, *d* = 0.29, a small effect (Figure 1).\n\nEvery number in that sentence comes from Steps 2, 5, and 6, and the sentence says which groups, how many, which direction, and how big.\n\n### Play 2 ([independent-samples t-tests]{.normal}): compare women and men on three cooking self-efficacy scales, with `ggplot2` violin and raincloud plots\n\n::: {.callout-note collapse=\"true\"}\n## About the dataset: `foodsecurity_SYNTHETIC.xlsx`\n\nIn fall 2025 another FRI Public Health team studied cooking skills and food security among Binghamton students: a pretest survey, a hands-on cooking workshop, and the same survey again two weeks later. The survey measured cooking self-efficacy with three short scales (confidence, food safety, nutrition; 1 = strongly disagree to 6 = strongly agree), plus cooking knowledge, barriers to cooking, food insecurity, and open-ended questions about culture and gender.\n\nThe file here is **synthetic**, generated by the same seeded script as Play 1's, so it can be public. It keeps the real survey's variables and response scales, the pretest item means, the share of -99 and -50 codes, the gender mix (mostly women), and the long pre/post layout linked by `PASSWORD`. Two things are different on purpose. The real export had only 45 responses and almost no one could be linked from pretest to posttest, so a paired analysis was impossible; the synthetic file has 72 pretest and 60 posttest rows with 59 people matched, a few dropouts, one duplicate, and two mistyped passwords, so that [Compare 1 Group, Pre/Post](violin.qmd) can use the same file. And the variables were renamed to the class conventions (`GENDER` 0 to 3, `RACIALIZED` as select-all columns, `_01` for yes/no, `_QUAL` for open text) where the real survey predated them. Every open-ended answer is a short invented phrase.\n:::\n\nThis play uses only the **pretest** rows, because the question is a two-group one: before the workshop, did women and men differ in cooking self-efficacy? The file is in long format with both time points, so the first step is to keep one row per person.\n\n#### Step 1: Import, clean, and keep the pretest\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoodsecuritydata <- read_excel(\"data/foodsecurity_SYNTHETIC.xlsx\")\n\nfoodsecuritydata[foodsecuritydata == -99] <- NA      # prefer not to say -> missing\nfoodsecuritydata[foodsecuritydata == -50] <- NA      # don't know -> missing\n\nfoodsecuritydata_pre <- foodsecuritydata |>\n  mutate(PASSWORD = tolower(trimws(PASSWORD))) |>    # clean the linking code (Pre/Post Data)\n  filter(TIME == 0) |>                                # pretest only\n  distinct(PASSWORD, .keep_all = TRUE)                # one row per person (drops the duplicate submission)\n\nnrow(foodsecuritydata_pre)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 72\n```\n\n\n:::\n\n```{.r .cell-code}\nfoodsecuritydata_pre |> count(GENDER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  GENDER     n\n   <dbl> <int>\n1      0    46\n2      1    18\n3      2     5\n4      3     1\n5     NA     2\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: Import Data Once; Pre/Post Data\n#explanation: missing codes become NA; the pretest rows are kept, one per person\n```\n:::\n\n\n`GENDER` has four levels, but two of them have a handful of people. A two-group test needs two groups, so this play compares women (0) and men (1) and sets the others aside, and says so.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoodsecuritydata_pre2 <- foodsecuritydata_pre |>\n  filter(GENDER %in% c(0, 1)) |>\n  mutate(GENDER = factor(GENDER, levels = c(0, 1), labels = c(\"Women\", \"Men\")))\n\nfoodsecuritydata_pre2 |> count(GENDER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  GENDER     n\n  <fct>  <int>\n1 Women     46\n2 Men       18\n```\n\n\n:::\n\n```{.r .cell-code}\n#explanation: the two groups to compare, as a labeled factor with the comparison group (women) first\n```\n:::\n\n\n#### Step 2: Make the three composites\n\nThe outcome is not one column but three scales. [Creating Composites](composite.qmd) showed `scoreItems()`; here it is again, with the alphas for the Methods section.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neff_keys <- list(\n  EFF_CONF  = c(\"EFFCONF1\", \"EFFCONF2\", \"EFFCONF3\", \"EFFCONF4\"),\n  EFF_SAFE  = c(\"EFFSAFE1\", \"EFFSAFE2\", \"EFFSAFE3\", \"EFFSAFE4\"),\n  EFF_NUTRI = c(\"EFFNUTRI1\", \"EFFNUTRI2\", \"EFFNUTRI3\"))\n\neff_scores <- scoreItems(eff_keys, foodsecuritydata_pre2, impute = \"none\")\nround(eff_scores$alpha, 2)                                   # reliability of each scale\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      EFF_CONF EFF_SAFE EFF_NUTRI\nalpha     0.59      0.7      0.79\n```\n\n\n:::\n\n```{.r .cell-code}\nfoodsecuritydata_pre2 <- foodsecuritydata_pre2 |>\n  mutate(EFF_CONF  = eff_scores$scores[, \"EFF_CONF\"],\n         EFF_SAFE  = eff_scores$scores[, \"EFF_SAFE\"],\n         EFF_NUTRI = eff_scores$scores[, \"EFF_NUTRI\"])\n\n#source: Creating Composites; psych package (Revelle)\n#explanation: three keys, three averaged scores added to the data, and Cronbach's alpha for each\n```\n:::\n\n\n#### Step 3: One long table for the plot\n\nA plot that shows all three scales side by side needs them in **one** column, with a second column saying which scale each score belongs to. That is `pivot_longer()` from [Pre/Post Data](prepost.qmd).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoodsecuritydata_pre_long <- foodsecuritydata_pre2 |>\n  select(PASSWORD, GENDER, EFF_CONF, EFF_SAFE, EFF_NUTRI) |>\n  pivot_longer(cols = c(EFF_CONF, EFF_SAFE, EFF_NUTRI),\n               names_to = \"SCALE\", values_to = \"SCORE\") |>\n  mutate(SCALE = factor(SCALE, levels = c(\"EFF_CONF\", \"EFF_SAFE\", \"EFF_NUTRI\"),\n                        labels = c(\"Confidence\", \"Safety\", \"Nutrition\")))\n\nhead(foodsecuritydata_pre_long)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  PASSWORD  GENDER SCALE      SCORE\n  <chr>     <fct>  <fct>      <dbl>\n1 river3248 Women  Confidence  4   \n2 river3248 Women  Safety      4.5 \n3 river3248 Women  Nutrition   4.33\n4 sunny8796 Men    Confidence  4.5 \n5 sunny8796 Men    Safety      5   \n6 sunny8796 Men    Nutrition   3.33\n```\n\n\n:::\n:::\n\n\n#### Step 4: Violin plot, built in layers\n\nA **violin plot** is a box plot with the distribution drawn around it: the width at each height is how many people scored there (a smoothed histogram turned on its side). Add the box plot inside it for the median and quartiles, and the raw points so that the reader can see how many people are behind each shape.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot2_efficacy_gender_violin <- ggplot(foodsecuritydata_pre_long, aes(x = SCALE, y = SCORE, fill = GENDER)) +\n  geom_violin(trim = TRUE, alpha = 0.6, position = position_dodge(width = 0.8)) +\n  geom_boxplot(width = 0.12, outlier.shape = NA, position = position_dodge(width = 0.8)) +\n  geom_jitter(position = position_jitterdodge(jitter.width = 0.12, dodge.width = 0.8),\n              alpha = 0.4, size = 1.2) +\n  scale_fill_manual(values = c(\"Women\" = \"#8d14c1\", \"Men\" = \"#f4b400\")) +\n  scale_y_continuous(breaks = 1:6, limits = c(1, 6)) +\n  labs(x = \"Cooking self-efficacy scale\", y = \"Score (1 = strongly disagree, 6 = strongly agree)\",\n       fill = \"Gender\", title = \"Cooking self-efficacy before the workshop, by gender\") +\n  theme_minimal(base_size = 13)\n\nplot2_efficacy_gender_violin\n```\n\n::: {.cell-output-display}\n![Figure 2. Cooking self-efficacy before the workshop, by gender (synthetic data). Violins show the distribution, boxes the median and quartiles, points the individual scores.](compare2groups_files/figure-html/plot2-efficacy-gender-violin-1.png){fig-alt='Three pairs of violin plots, one pair for each self-efficacy scale, with women in purple and men in yellow. Each violin has a narrow box plot inside and jittered points. The men\\'s violins sit slightly higher on confidence.' width=864}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot2_efficacy_gender_violin.png\", plot = plot2_efficacy_gender_violin, width = 8, height = 5, dpi = 300)\n\n#source: ggplot2 documentation https://ggplot2.tidyverse.org/reference/geom_violin.html\n#explanation: three layers on one plot: the violin (distribution), the box (median and quartiles), the jittered points (every person); position_dodge puts the two genders side by side within each scale\n```\n:::\n\n\n::: callout-tip\n## Go: reading a violin\n\nWide at the top means many people scored high. Two bulges mean two kinds of people. A long thin tail means a few people far from the rest. A violin tells you whether the groups differ in **shape**, not only in their average, which is something a bar chart of means cannot show.\n:::\n\n#### Step 5: Raincloud plot\n\nA **raincloud plot** is the same information with the layers pulled apart so that none hides another: a half violin (the cloud), the box plot beside it, and the raw points below (the rain). `geom_violinhalf()` comes from the `see` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot3_efficacy_gender_raincloud <- ggplot(foodsecuritydata_pre_long, aes(x = SCALE, y = SCORE, fill = GENDER)) +\n  geom_violinhalf(position = position_dodge(width = 0.8), alpha = 0.6, trim = TRUE) +\n  geom_boxplot(width = 0.1, outlier.shape = NA, position = position_dodge(width = 0.8)) +\n  geom_point(aes(color = GENDER),\n             position = position_jitterdodge(jitter.width = 0.08, dodge.width = 0.8, seed = 1),\n             alpha = 0.5, size = 1.2) +\n  scale_fill_manual(values = c(\"Women\" = \"#8d14c1\", \"Men\" = \"#f4b400\")) +\n  scale_color_manual(values = c(\"Women\" = \"#8d14c1\", \"Men\" = \"#f4b400\"), guide = \"none\") +\n  scale_y_continuous(breaks = 1:6, limits = c(1, 6)) +\n  labs(x = \"Cooking self-efficacy scale\", y = \"Score (1 to 6)\", fill = \"Gender\",\n       title = \"Cooking self-efficacy before the workshop, by gender (raincloud)\") +\n  theme_minimal(base_size = 13)\n\nplot3_efficacy_gender_raincloud\n```\n\n::: {.cell-output-display}\n![Figure 3. The same data as Figure 2 as a raincloud plot: half violins (the cloud), box plots, and individual scores (the rain).](compare2groups_files/figure-html/plot3-efficacy-gender-raincloud-1.png){fig-alt='For each of the three scales, half-violin shapes for women and men are nudged to the right, narrow box plots sit in the middle, and jittered points are nudged to the left.' width=864}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot3_efficacy_gender_raincloud.png\", plot = plot3_efficacy_gender_raincloud, width = 8, height = 5, dpi = 300)\n\n#source: see package https://easystats.github.io/see/reference/geom_violinhalf.html; Allen et al. (2019)\n#explanation: a half violin instead of a full one, so the box and the points have room beside it\n```\n:::\n\n\n#### Step 6: One t-test per scale, then report\n\nThree outcomes means three tests. Run them the same way as Play 1, and report each with its means and effect size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ttestmodel2: EFF_CONF by GENDER\nttestmodel2  <- t.test(EFF_CONF  ~ GENDER, data = foodsecuritydata_pre2)\n# ttestmodel3: EFF_SAFE by GENDER\nttestmodel3  <- t.test(EFF_SAFE  ~ GENDER, data = foodsecuritydata_pre2)\n# ttestmodel4: EFF_NUTRI by GENDER\nttestmodel4 <- t.test(EFF_NUTRI ~ GENDER, data = foodsecuritydata_pre2)\n\nttestmodel2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  EFF_CONF by GENDER\nt = -1.0545, df = 31.535, p-value = 0.2996\nalternative hypothesis: true difference in means between group Women and group Men is not equal to 0\n95 percent confidence interval:\n -0.6824042  0.2170257\nsample estimates:\nmean in group Women   mean in group Men \n           4.179348            4.412037 \n```\n\n\n:::\n\n```{.r .cell-code}\n#explanation: Welch t-test for each composite; print the other two the same way\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Table 1. Cooking self-efficacy by gender before the workshop: Welch t-tests (synthetic data).\n\n|Scale     |Women M (SD) |Men M (SD)  |t     |df   |p    |d     |\n|:---------|:------------|:-----------|:-----|:----|:----|:-----|\n|EFF_CONF  |4.18 (0.80)  |4.41 (0.79) |-1.05 |31.5 |.300 |-0.29 |\n|EFF_SAFE  |4.60 (0.81)  |4.47 (0.83) |0.54  |30.3 |.593 |0.15  |\n|EFF_NUTRI |4.44 (0.99)  |4.45 (0.95) |-0.04 |32.2 |.965 |-0.01 |\n\n\n:::\n:::\n\n\nWhen you have several tests like this, a table is clearer than three sentences, and one sentence then summarizes the table: which scales differed, in which direction, and how large the differences were. Here the answer is that none did: all three p-values are well above .05 and the effect sizes are small, so before the workshop women and men reported similar cooking self-efficacy. A null result is a result; report it with the same numbers. With three tests you have three chances for a false positive; say so, or use a stricter alpha (.05 ÷ 3 ≈ .017), and your peer mentor and/or Dr. Shane can help you decide.\n\n::: callout-warning\n## Caution: the n behind the plot\n\nPlay 2 has 18 men. A violin drawn from a group that small is a smoothed curve through a few points, and it can look like a shape that is not there. Always print `count()` by group before you trust the picture, and report the n of each group in the caption.\n:::\n\n### Play 3 ([Mann-Whitney U test]{.nonnormal}): compare minoritized and non-minoritized participants on self-rated health\n\nPlays 1 and 2 had outcomes that were roughly normal, so the t-test was the right line of the Analysis Map box. This play is the other line. The outcome is **one question**, not a composite: \"In general, would you say your health is…\" with five answers from Poor (1) to Excellent (5). A 1-to-5 rating with most people on 3 and 4 cannot be normal, and its mean (3.4, say) is not a value anyone chose. The **Mann-Whitney U test** compares two groups without assuming normality: it ranks every person's score from lowest to highest, pools the ranks, and asks whether one group's ranks tend to be higher than the other's. The question here is whether people who are minoritized rate their health differently from people who are not.\n\n::: {.callout-note collapse=\"true\"}\n## About the dataset: `health_status_data.csv` (the Cohort 10 class dataset)\n\nEvery FRI Public Health team in **Cohort 10** asked the same self-rated health question, *Would you say your health in general is excellent, very good, good, fair, or poor?*, along with the class variables of that year (age, sex, racialized identity, perceived income, and the MacArthur ladder of subjective social status). The five team datasets were merged into one file of 343 respondents so that health status could be examined across the whole class. `SAMPLE_ID` says which team's study a person came from.\n\nThis is **real data**, already cleaned and de-identified: no response IDs, passwords, dates, or open-ended answers, and the five team samples differ in whom they recruited (students, families, farmers-market visitors), which is why the chapters filter by age. The variable names predate the class naming rules, so the Play renames them: `HEALTH_STATUS` becomes `HEALTHSTATUS` (1 = Poor … 5 = Excellent); `SSS` is subjective social status (1 to 10); `SEX` is biological sex (0 = male, 1 = female); and `RACIALIZED_IDENTITY` (1 = identified as white only, 0 = any other identity) becomes `MINORITIZED_01` (1 = minoritized, 0 = not), named for the 1 the way a `_01` variable should be. The other columns (`RG_…`, `RI_…`, `PoorFairHealth`, `ExcellentHealth`) are earlier recodes of the same questions and are not used here.\n:::\n\n\n#### Step 1: Import and recode, as in Visualize a Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealthstatusdata <- read.csv(\"data/health_status_data.csv\") |>\n  rename(HEALTHSTATUS = HEALTH_STATUS) |>\n  mutate(\n    MINORITIZED = factor(if_else(RACIALIZED_IDENTITY == 1, 0, 1),\n                         levels = c(0, 1), labels = c(\"Not minoritized\", \"Minoritized\")),\n    SEX         = factor(SEX, levels = c(0, 1), labels = c(\"Male\", \"Female\"))) |>\n  filter(!is.na(HEALTHSTATUS), !is.na(MINORITIZED))\n\nhealthstatusdata |> count(MINORITIZED)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      MINORITIZED   n\n1 Not minoritized 223\n2     Minoritized 120\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: Visualize a Comparison (Play 2)\n#explanation: the same two recodes as the earlier chapters; this play keeps every age because the question is about the whole sample\n```\n:::\n\n\n#### Step 2: Look at the two distributions\n\nA density curve is the wrong picture for five possible values. Count how many people in each group chose each answer and plot the **proportions**, so a bigger group does not look like a healthier one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth_props <- healthstatusdata |>\n  count(MINORITIZED, HEALTHSTATUS) |>\n  group_by(MINORITIZED) |>\n  mutate(prop = n / sum(n)) |>\n  ungroup()\n\nplot4_health_minoritized_barplot <- ggplot(health_props, aes(x = factor(HEALTHSTATUS), y = prop, fill = MINORITIZED)) +\n  geom_col(position = position_dodge(width = 0.8), width = 0.75) +\n  scale_x_discrete(labels = c(\"1\" = \"Poor\", \"2\" = \"Fair\", \"3\" = \"Good\", \"4\" = \"Very good\", \"5\" = \"Excellent\")) +\n  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +\n  scale_fill_manual(values = c(\"Not minoritized\" = \"#8d14c1\", \"Minoritized\" = \"#f4b400\")) +\n  labs(x = \"Self-rated health\", y = \"Share of group\", fill = NULL,\n       title = \"Self-rated health by minoritized status\") +\n  theme_bw(base_size = 13) +\n  theme(legend.position = \"top\")\n\nplot4_health_minoritized_barplot\n```\n\n::: {.cell-output-display}\n![Figure 4. Self-rated health by minoritized status (Cohort 10 data, n = 343). Bars are the share of each group choosing each answer.](compare2groups_files/figure-html/plot4-health-minoritized-barplot-1.png){fig-alt='Two sets of five bars, one per group, for Poor through Excellent. Both groups peak at Good and Very good; the Minoritized bars are much taller at Fair and shorter at Excellent.' width=672}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot4_health_minoritized_barplot.png\", plot = plot4_health_minoritized_barplot, width = 8, height = 5, dpi = 300)\n\n#source: https://ggplot2.tidyverse.org/reference/geom_bar.html\n#explanation: count() then a proportion within each group; position_dodge puts the two groups side by side at each answer\n```\n:::\n\n\nThe minoritized group's bars sit a step to the left: four times the share at Fair, and smaller shares at Good, Very good, and Excellent. That is the pattern the test will check.\n\n#### Step 3: Why not a t-test?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealthstatusdata |>\n  group_by(MINORITIZED) |>\n  summarise(n = n(), median = median(HEALTHSTATUS), mean = mean(HEALTHSTATUS),\n            shapiro_p = shapiro.test(HEALTHSTATUS)$p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  MINORITIZED         n median  mean shapiro_p\n  <fct>           <int>  <dbl> <dbl>     <dbl>\n1 Not minoritized   223      4  3.62  1.05e-12\n2 Minoritized       120      3  3.26  1.01e- 7\n```\n\n\n:::\n\n```{.r .cell-code}\n#explanation: Shapiro-Wilk p far below .05 in both groups, as it must be for a five-point rating; the median is the summary to report\n```\n:::\n\n\nBoth Shapiro-Wilk p-values are far below .05. With groups this large a t-test would give a similar p-value (the t-test is robust to non-normality when n is big), but it would make you report means of a five-point rating, and a mean of 3.6 does not describe anyone. The Mann-Whitney U test matches the data: it uses ranks and reports medians.\n\n#### Step 4: The Mann-Whitney U test and its effect size\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# mannmodel1: HEALTHSTATUS by MINORITIZED (Mann-Whitney U)\nmannmodel1 <- wilcox.test(HEALTHSTATUS ~ MINORITIZED, data = healthstatusdata)\nmannmodel1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  HEALTHSTATUS by MINORITIZED\nW = 16134, p-value = 0.0009154\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# effect size r, from the test's normal approximation\nn_health <- nrow(healthstatusdata)\nz_health <- qnorm(mannmodel1$p.value / 2)\nr_health <- abs(z_health) / sqrt(n_health)\nr_health\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1790102\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: R documentation ?wilcox.test; Fritz, Morris, & Richler (2012) for r\n#explanation: R names this test the Wilcoxon rank sum test and reports the statistic as W; W is the Mann-Whitney U. r = |Z| / sqrt(N); .1 small, .3 medium, .5 large\n```\n:::\n\n\nThree things to know about the output. R calls the test the **Wilcoxon rank sum test**, which is the same test as the Mann-Whitney U under another name; report it as Mann-Whitney U, as the Analysis Map does. The statistic `W` is *U*. And the warning \"cannot compute exact p-value with ties\" is expected when many people share the same score; R switches to a normal approximation, which is what you want here. The effect size for a rank test is *r*, computed from the Z behind the p-value: .1 is small, .3 medium, .5 large.\n\n#### Step 5: Report it\n\n\n\nA Mann-Whitney sentence reports **medians** (and the n of each group), *U*, *p*, and *r*, and names the direction:\n\n> Minoritized participants rated their health lower (*Mdn* = 3, Good; *n* = 120) than participants who were not minoritized (*Mdn* = 4, Very good; *n* = 223), Mann-Whitney *U* = 16,133.5, *p* < .001, *r* = 0.18, a small effect (Figure 3).\n\n::: callout-tip\n## Go: which line of the box am I on?\n\nAsk two questions about the outcome. Is it a **composite or a continuous measurement** (a mean of several items, a Veggie Meter score, minutes, dollars)? Then start with the t-test, check normality within each group, and switch to Mann-Whitney U only if a group is small and clearly skewed. Is it a **single rating with a handful of levels**, or a count with a long tail (days per week, number of visits)? Then go straight to Mann-Whitney U and report medians. When you cannot decide, run both, as Play 1 did; if they agree, report the one that matches the data, and if they disagree, say so.\n:::\n\n## 🏈 The Lab {#sec-compare2-lab}\n\n:::::: {.ref .ref-tip}\n::: ref-face\n![](images/ref.svg){fig-alt=\"Ref the raccoon\"}\n:::\n\n::: ref-say\n**Ref's kickoff.** Two comparisons on the lab data: well-being by whether a person has had mental health treatment (`MH_TREATED`, 0/1), drawn with `ggdensity()`, then stigma by racialized identity (`RACIALIZED_01`), drawn as a violin. Run `source(\"lab_prep.R\")` first. Try each play before you open my check.\n:::\n::::::\n\n\n\n**Before you start.** Open your lab `.qmd`, run your load-library chunk (`ggpubr` and `see` must be loaded), and run `source(\"lab_prep.R\")` so that `mh_clean` is in your environment. `WELLBEING` and `STIGMA` are already composites (made in `lab_prep.R`); `RACIALIZED_01` is from [Transforming Your Data](dplyr.qmd).\n\n### Lab Play 1 ([t-test]{.normal}): compare people with and without mental health treatment on well-being, with `ggdensity()`\n\nKeep people with `MH_TREATED` of 0 or 1, make it a factor (`No treatment` first), count the groups, draw the density plot with group means, check normality per group, run the Welch t-test and Cohen's d, and write the sentence.\n\n::: {.callout-tip collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's check: what should you find?\n\n-   **110** people with no treatment history and **75** with treatment.\n-   Means: no treatment 3.26 (SD 0.68), treatment 3.23 (SD 0.65). Shapiro-Wilk p = 0.747 and 0.064.\n-   Welch *t*(163.8) = 0.30, *p* = .761, *d* = 0.05. The groups do not differ by more than chance would produce.\n-   In the density plot, the dashed mean lines should sit where the two means above say they do. If your lines are in different places, you plotted `mh_clean` instead of your filtered object, or the factor labels are swapped.\n:::\n\n### Lab Play 2 ([t-test]{.normal} and [Mann-Whitney U]{.nonnormal}): compare white participants and people of color on stigma, with a violin plot\n\nKeep people with a value on `RACIALIZED_01`, make it a factor (`White` first), draw a violin with a box plot and jittered points, check normality, run the Welch t-test **and** the Mann-Whitney U test, and compare their conclusions.\n\n::: {.callout-tip collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's check: what should you find?\n\n-   **94** people racialized as white and **91** as people of color.\n-   Means: white 2.32 (SD 0.61), people of color 2.55 (SD 0.63). Shapiro-Wilk p = 0.277 and 0.342.\n-   Welch *t*(182.3) = -2.50, *p* = .013, *d* = -0.37; Mann-Whitney U *p* = .022. The two tests agree, which is what you want to see.\n-   Write the result as \"people racialized as …\", never \"white people are …\" ([Transforming Your Data](dplyr.qmd)).\n:::\n\n::: {.callout-note .gray collapse=\"true\"}\n## 👀 See the solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse); library(ggpubr); library(see)\nsource(\"lab_prep.R\")\n\n# Lab Play 1\nlab1 <- mh_clean |>\n  filter(MH_TREATED %in% c(0, 1)) |>\n  mutate(MH_TREATED = factor(MH_TREATED, levels = c(0, 1), labels = c(\"No treatment\", \"Treatment\")))\nlab1 |> count(MH_TREATED)\nggdensity(lab1, x = \"WELLBEING\", color = \"MH_TREATED\", fill = \"MH_TREATED\",\n          add = \"mean\", rug = TRUE, xlab = \"Well-being (1 to 5)\")\nlab1 |> group_by(MH_TREATED) |> summarise(n = n(), mean = mean(WELLBEING), sd = sd(WELLBEING),\n                                           shapiro_p = shapiro.test(WELLBEING)$p.value)\nt.test(WELLBEING ~ MH_TREATED, data = lab1)\ncohens_d(lab1$WELLBEING[lab1$MH_TREATED == \"No treatment\"], lab1$WELLBEING[lab1$MH_TREATED == \"Treatment\"])\n\n# Lab Play 2\nlab2 <- mh_clean |>\n  filter(!is.na(RACIALIZED_01)) |>\n  mutate(RACIALIZED_01 = factor(RACIALIZED_01, levels = c(0, 1), labels = c(\"White\", \"Person of color\")))\nggplot(lab2, aes(x = RACIALIZED_01, y = STIGMA, fill = RACIALIZED_01)) +\n  geom_violin(alpha = 0.6) + geom_boxplot(width = 0.12, outlier.shape = NA) +\n  geom_jitter(width = 0.1, alpha = 0.4) + theme_minimal()\nt.test(STIGMA ~ RACIALIZED_01, data = lab2)\nwilcox.test(STIGMA ~ RACIALIZED_01, data = lab2)\n\n#source: The Quantitative Playbook for R (McCarty, 2026)\n#explanation: the same seven steps as the Play, on two lab comparisons\n```\n:::\n\n:::\n\n::: {.callout-warning collapse=\"true\" icon=\"false\"}\n## ![](images/ref-whistle.svg){.ref-mini fig-alt=\"Ref the raccoon blowing his whistle\"} Ref's call: fouls to check if your numbers do not match\n\n-   **`grouping factor must have exactly 2 levels`** → your group variable still has 3 or more values (or `NA` counted as one). Filter to the two groups first.\n-   **The means are the same as Ref's but t has the opposite sign** → your factor levels are in the other order. `t.test()` reports group 1 minus group 2; put the comparison group first in `levels =`.\n-   **`could not find function \"ggdensity\"`** (or `geom_violinhalf`) → run `library(ggpubr)` (or `library(see)`); if that fails, source `install.R`.\n-   **`object 'WELLBEING' not found`** → run `source(\"lab_prep.R\")`.\n-   **A third violin labeled `NA`** → you forgot the `filter()` on the group variable.\n-   **The plot shows but `ggsave()` errors** → there is no `plots` folder in your project. Make it once in the Files tab.\n:::\n\n:::::: {.ref .ref-tip}\n::: ref-face\n![](images/ref-whistle.svg){fig-alt=\"Ref the raccoon blowing his whistle\"}\n:::\n\n::: ref-say\n**Ref's final whistle.** Two plots, two tests, two sentences in your coding journal. Save, render, back up to your ELN.\n:::\n::::::\n\n::: {.callout-important .required}\n## Required: a two-group comparison in your report\n\nFor every two-group comparison in your *RD Report* and *Final Report*: the plot (density, violin, or raincloud), saved with `ggsave()` and captioned with the n of each group; the assumption check you ran and what it showed; the test that matches the outcome, the Welch t-test with Cohen's *d* for a normal composite or continuous score (Play 1, Step 7) or the Mann-Whitney U test with *r* for a skewed outcome or a single rating (Play 3, Step 5); and one sentence in Results in that Play's form. Say in Methods how you defined the two groups and whom you excluded.\n:::\n\n## 🏆 Your Turn {#sec-compare2-yourturn}\n\n::: {.callout-note .gray icon=\"false\"}\n## There is no Ref. It's game time, your turn!\n\nNobody has compared your team's groups before, so there is no answer to check against. Pick the plot style you will use throughout your report, change every word that starts with `SWAP`, and use the checklist.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse); library(ggpubr); library(see)\n\n# 1. two groups, as a labeled factor, comparison group first\nmydata <- cleandata |>\n  filter(SWAPGROUP_01 %in% c(0, 1)) |>                                        # SWAP: your group variable (a _01 or _01CAT variable)\n  mutate(SWAPGROUP_01 = factor(SWAPGROUP_01, levels = c(0, 1), labels = c(\"SWAPLABEL1\", \"SWAPLABEL2\")))   # SWAP: the labels\nmydata |> count(SWAPGROUP_01)                                                 # both groups big enough?\n\n# 2. look\nggdensity(mydata, x = \"SWAPOUTCOME\", color = \"SWAPGROUP_01\", fill = \"SWAPGROUP_01\",   # SWAP: your outcome (a score)\n          add = \"mean\", rug = TRUE)\n# or:\n# ggplot(mydata, aes(x = SWAPGROUP_01, y = SWAPOUTCOME, fill = SWAPGROUP_01)) +\n#   geom_violin(alpha = 0.6) + geom_boxplot(width = 0.12, outlier.shape = NA) + geom_jitter(width = 0.1, alpha = 0.4)\n\n# 3. assumptions\nmydata |> group_by(SWAPGROUP_01) |> summarise(n = n(), mean = mean(SWAPOUTCOME, na.rm = TRUE), sd = sd(SWAPOUTCOME, na.rm = TRUE),\n                                          shapiro_p = shapiro.test(SWAPOUTCOME)$p.value)\n\n# 4a. normal outcome (parametric): t-test and Cohen's d\n# ttestmodel1: SWAP: one line that says what this test compares\nttestmodel1 <- t.test(SWAPOUTCOME ~ SWAPGROUP_01, data = mydata)\nttestmodel1\ncohens_d <- function(x, y) (mean(x, na.rm = TRUE) - mean(y, na.rm = TRUE)) / sqrt((var(x, na.rm = TRUE) + var(y, na.rm = TRUE)) / 2)\ncohens_d(mydata$SWAPOUTCOME[mydata$SWAPGROUP_01 == \"SWAPLABEL1\"], mydata$SWAPOUTCOME[mydata$SWAPGROUP_01 == \"SWAPLABEL2\"])\n\n# 4b. outcome not normal, or a single rating (non-parametric): Mann-Whitney U and r\nmydata |> group_by(SWAPGROUP_01) |> summarise(n = n(), median = median(SWAPOUTCOME, na.rm = TRUE))\n# mannmodel1: SWAP: one line that says what this test compares\nmannmodel1 <- wilcox.test(SWAPOUTCOME ~ SWAPGROUP_01, data = mydata)\nmannmodel1\nabs(qnorm(mannmodel1$p.value / 2)) / sqrt(sum(!is.na(mydata$SWAPOUTCOME)))          # r: .1 small, .3 medium, .5 large\n\n# 5. save the plot for the poster\n# ggsave(\"plots/plot1_SWAPNAME.png\", width = 8, height = 5, dpi = 300)                       # SWAP: the variables and plot type, e.g. plot1_wellbeing_treated_barplot\n```\n:::\n\n\n| Criteria | Ask yourself |\n|----|----|\n| **Design** | Are the two groups different people? (Same people twice is [Compare 1 Group, Pre/Post](violin.qmd).) |\n| **Two levels** | Does `count()` show exactly two groups, no `NA` row, and at least 20 people in each? |\n| **Outcome** | Is the outcome a score (composite or continuous), not a category? |\n| **Which test** | Did you check normality per group and say which line of the Analysis Map box you are on: t-test (normal composite or continuous score) or Mann-Whitney U (skewed, small group, or a single rating)? |\n| **Effect size** | Did you report Cohen's *d* (t-test) or *r* (Mann-Whitney U), and say whether it is small, medium, or large? |\n| **Plot** | Does the caption give the n of each group, and is the plot saved with `ggsave()`? |\n| **Sentence** | Does your Results sentence have *M*, *SD*, *n*, *t*(df), *p*, *d* (t-test) or *Mdn*, *n*, *U*, *p*, *r* (Mann-Whitney U) for both groups, and name the direction? |\n| **Exclusions** | Does Methods say who was left out of the comparison and why? |\n\n<!-- Single source for the collapsed final-whistle reminder at the END of every coding chapter (7 onward). Edit here only. The full routine lives in find-the-ref.qmd (Ref's Quick Checklist). -->\n\n::: {.callout-note .gray collapse=\"true\" icon=\"false\"}\n## ![](images/ref-whistle.svg){.ref-mini fig-alt=\"Ref the raccoon blowing his whistle\"} Ref's final whistle: before you quit RStudio\n\n**Save → Render → Back up to ELN → Quit, Don't Save workspace.** Details: [Ref's Quick Checklist](find-the-ref.qmd#sec-ref-checklist).\n:::\n\n",
    "supporting": [
      "compare2groups_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}