{
  "hash": "f7bb53f140c2f63fd199d6c14acc7581",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Compare 1 Group, Pre/Post\"\nsubtitle: \"Paired-samples t-test (normal) and Wilcoxon signed-rank (non-normal)\"\nauthor:\n  - Yoomin (Ashley) Kim\n  - Erica Sava\nabstract: |\n  This chapter is the Analysis Map's \"compare 1 group, pre/post\" row: the same people measured twice, before and after something, and one continuous outcome. Researchers learn why a pre/post design is a one-group comparison of differences rather than a two-group comparison, how to link each person's two scores and keep only the matched people, how to draw a paired violin or raincloud plot that shows every person's change, how to check the assumption that the differences are roughly normal and then choose the paired-samples t-test or the Wilcoxon signed-rank test, and how to report each with an effect size. The Play uses the synthetic food security dataset from a cooking workshop; the Lab runs the same tests on the long-format lab dataset with Ref's checks; Your Turn gives the template for Teams 3 and 5.\nkeywords:\n  - paired t-test\n  - Wilcoxon signed-rank\n  - pre/post\n  - violin plot\n  - raincloud plot\n  - within-person\ndate: 10.04.2026\ndate-format: \"MM.DD.YYYY\"\nformat:\n  html:\n    css: custom.css\neditor: visual\nexecute:\n  cache: false\n  warning: false\n  message: false\n---\n\n<!-- Single source for the collapsed kickoff reminder at the START of every coding chapter (7 onward). Edit here only. The full routine lives in find-the-ref.qmd (Ref's Quick Checklist). -->\n\n::: {.callout-note .gray collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's kickoff: find the Ref before you code\n\n**Open Project → Open `.qmd` → Run load-library chunk → Run All Chunks Above → code.** If anything looks wrong, use [Ref's Quick Checklist](find-the-ref.qmd#sec-ref-checklist).\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Resources: paired tests and paired plots\n\n-   [Paired t-test in R](https://www.datacamp.com/tutorial/t-tests-r-tutorial) (DataCamp; the paired section)\n-   [Wilcoxon signed-rank test in R](https://www.sthda.com/english/wiki/paired-samples-wilcoxon-test-in-r) (STHDA)\n-   [Raincloud plots with ggplot2](https://z3tt.github.io/Rainclouds/) and [`geom_paired_raincloud()`](https://yjunechoe.github.io/posts/2020-07-13-geom-paired-raincloud/)\n-   [`see::geom_violinhalf()`](https://easystats.github.io/see/reference/geom_violinhalf.html)\n-   [Pre/Post Data](prepost.qmd): how to get from one or two survey exports to the wide and long tables this chapter needs\n:::\n\n## When is this the right test?\n\nThe **same people** answered the same questions **twice**: before and after a workshop, a video, a semester. On [The Analysis Map](analysis-map.qmd) that is the *compare 1 group, pre/post* row, and the test is the **paired-samples t-test**. The word *paired* is the whole idea: each person's posttest score is paired with their own pretest score, so the thing being tested is the **difference within each person**, and the question is whether those differences average to something other than zero.\n\nThis is why it is a *one-group* comparison, not two. The pretest and posttest rows are not two groups of people; they are one group of people seen twice. Running an independent-samples test ([Compare 2 Groups](compare2groups.qmd)) on pre/post data is the most common wrong turn on the map: it throws away the pairing, and with it most of the power of the design. If you cannot link a person's two rows, you cannot be on this row.\n\nAs in every box on the map, the shape of the outcome picks the test, but here the shape that matters is the shape of the **differences**:\n\n| Test | Use it when | R function | Report |\n|----|----|----|----|\n| [**Paired-samples t-test** (parametric)]{.normal} | the within-person differences are roughly normal, or there are 30 or more matched people | `t.test(POST, PRE, paired = TRUE)` | *M* pre and post, *t*(df), *p*, Cohen's *d~z~* |\n| [**Wilcoxon signed-rank test** (non-parametric)]{.nonnormal} | the differences are skewed, few people are matched, or the outcome is a single rating with a few levels or a count | `wilcox.test(POST, PRE, paired = TRUE)` | *Mdn* pre and post, *V*, *p*, *r* |\n\nPlay 1 is the [parametric]{.normal} case; Play 2 is the [non-parametric]{.nonnormal} case.\n\n::: callout-tip\n## Go: do this first\n\n[Pre/Post Data](prepost.qmd) gets the data into shape: `PASSWORD` cleaned, duplicates removed, `TIME` as a factor, and one **wide** table (one row per person, `SWAPSCORE_PRE` and `SWAPSCORE_POST`) plus one **long** table (two rows per person). This chapter tests the wide table and plots the long one.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)   # dplyr, tidyr, ggplot2\nlibrary(readxl)\nlibrary(see)         # geom_violinhalf() for the raincloud\nlibrary(knitr)\n```\n:::\n\n\n::: callout-important\n## Important: one package to install once\n\n`see` is on the `install.R` list ([R Packages](library.qmd)). If `library(see)` says `there is no package called 'see'`, source `install.R` again.\n:::\n\n## 📋 The Play\n\n::: {.callout-note collapse=\"true\"}\n## About the dataset: `foodsecurity_SYNTHETIC.xlsx`\n\nIn fall 2025 an FRI Public Health team studied cooking skills and food security among Binghamton students: a pretest survey, a hands-on cooking workshop, and the same survey two weeks later, linked by a self-made `PASSWORD`. The file here is **synthetic**, generated by a seeded script, so it can be public. It keeps the real survey's variables and response scales, the pretest means, the share of -99 and -50 codes, and the long pre/post layout; the real export had only 45 responses and almost no one could be linked from pretest to posttest, so the synthetic file has 72 pretest and 60 posttest rows with 59 people matched, a few dropouts, one duplicate, and two mistyped passwords, which is exactly the mess [Pre/Post Data](prepost.qmd) teaches you to clean. [Compare 2 Groups](compare2groups.qmd) uses the pretest rows of the same file.\n:::\n\nThe research question is the team's: **did cooking self-efficacy change from before the workshop to after it?** Two outcomes, one for each line of the box: food-safety self-efficacy (`EFF_SAFE`, the mean of four 1-to-6 items), a composite; and the number of five basic cooking skills a person says they know (`COOKKNOW`, 0 to 5), a count.\n\n### Play 1 ([paired-samples t-test]{.normal}): compare pretest and posttest on food-safety self-efficacy\n\n#### Step 1: Import, clean the link, and score\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoodsecuritydata_long <- read_excel(\"data/foodsecurity_SYNTHETIC.xlsx\") |>\n  mutate(PASSWORD = tolower(trimws(PASSWORD)),                              # the link must match exactly\n         TIME = factor(TIME, levels = c(0, 1), labels = c(\"PRE\", \"POST\"))) |>\n  distinct(PASSWORD, TIME, .keep_all = TRUE) |>                             # one row per person per time\n  mutate(across(where(is.numeric), ~ replace(.x, .x %in% c(-99, -50), NA))) |>\n  mutate(EFF_SAFE = rowMeans(across(EFFSAFE1:EFFSAFE4), na.rm = TRUE),\n         COOKKNOW = rowSums(across(COOKKNOW1:COOKKNOW5)))                   # count of skills known (0 to 5)\n\nfoodsecuritydata_long |> count(TIME)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  TIME      n\n  <fct> <int>\n1 PRE      72\n2 POST     60\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: Pre/Post Data (Situation 1); Create Composite Variables\n#explanation: tolower() and trimws() fix the two most common password mismatches; distinct() drops the duplicate; the composites are scored in long format so pre and post are scored the same way\n```\n:::\n\n\n#### Step 2: Wide for the test, and keep the matched people\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoodsecuritydata_wide <- foodsecuritydata_long |>\n  select(PASSWORD, TIME, EFF_SAFE, COOKKNOW) |>\n  pivot_wider(names_from = TIME, values_from = c(EFF_SAFE, COOKKNOW), names_glue = \"{.value}_{TIME}\")\n\nnrow(foodsecuritydata_wide)                                                   # people who appear at least once\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 73\n```\n\n\n:::\n\n```{.r .cell-code}\nfoodsecuritydata_matched <- foodsecuritydata_wide |> filter(!is.na(EFF_SAFE_PRE), !is.na(EFF_SAFE_POST))\nnrow(foodsecuritydata_matched)                                                # people with both scores: the n for the test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 59\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: Pre/Post Data (Situation 1, Step 4)\n#explanation: names_glue builds EFF_SAFE_PRE / EFF_SAFE_POST; a paired test can only use people who have both\n```\n:::\n\n\n::: callout-warning\n## Caution: your n is the matched people, not the rows\n\n132 rows became 73 people, of whom 59 have both a pretest and a posttest. The test uses 59. Report all three numbers in Methods (how many started, how many finished, how many could be linked), because the people who dropped out may differ from the people who stayed.\n:::\n\n#### Step 3: Look at the change, person by person\n\nA paired plot should show the pairing. The long table of the matched people, with a line from each person's pretest to their posttest, does that: the violins show the two distributions, and the lines show that most people moved up.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoodsecuritydata_matched_long <- foodsecuritydata_matched |>\n  select(PASSWORD, EFF_SAFE_PRE, EFF_SAFE_POST) |>\n  pivot_longer(cols = -PASSWORD, names_to = \"TIME\", values_to = \"EFF_SAFE\", names_prefix = \"EFF_SAFE_\") |>\n  mutate(TIME = factor(TIME, levels = c(\"PRE\", \"POST\")))\n\nplot1_effsafe_prepost_paired <- ggplot(foodsecuritydata_matched_long, aes(x = TIME, y = EFF_SAFE)) +\n  geom_line(aes(group = PASSWORD), color = \"gray60\", alpha = 0.5) +            # one line per person\n  geom_violin(aes(fill = TIME), alpha = 0.5, show.legend = FALSE) +\n  geom_boxplot(width = 0.12, outlier.shape = NA) +\n  geom_point(alpha = 0.4, size = 1.2) +\n  scale_y_continuous(breaks = 1:6, limits = c(1, 6)) +\n  scale_fill_manual(values = c(\"PRE\" = \"#8d14c1\", \"POST\" = \"#f4b400\")) +\n  labs(x = NULL, y = \"Food-safety self-efficacy (1 to 6)\",\n       title = \"Food-safety self-efficacy before and after the workshop\") +\n  theme_bw(base_size = 13)\n\nplot1_effsafe_prepost_paired\n```\n\n::: {.cell-output-display}\n![Figure 1. Food-safety self-efficacy before and after the cooking workshop (synthetic data, n = 59 matched). Each gray line is one person; violins show the distribution at each time, boxes the median and quartiles.](violin_files/figure-html/plot1-effsafe-prepost-paired-1.png){fig-alt='Two violins, PRE in purple and POST in yellow, with thin gray lines connecting each person\\'s two points. Most lines slope upward; the POST violin sits higher and is narrower at the top of the scale.' width=672}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot1_effsafe_prepost_paired.png\", plot = plot1_effsafe_prepost_paired, width = 8, height = 5, dpi = 300)\n\n#source: https://ggplot2.tidyverse.org/reference/geom_path.html\n#explanation: geom_line(aes(group = PASSWORD)) draws one segment per person, which is the layer that makes the plot paired; the other layers are the violin from Compare 2 Groups\n```\n:::\n\n\n::: callout-tip\n## Go: reading a paired violin\n\nThe violin is a box plot and a density curve in one shape: wide where many people scored, narrow where few did. Two violins side by side compare the two distributions, which is what [Compare 2 Groups](compare2groups.qmd) needs. For a pre/post design the lines matter more than the violins: if most lines go up, the change is consistent across people; if lines cross in every direction, the average change is hiding a lot of individual variation, and the test's p-value will say so. (Erica Sava)\n:::\n\n#### Step 4: The raincloud version\n\nA raincloud puts the half-violin (the cloud), the box, and the raw points (the rain) side by side so that none hides another. The paired lines still connect each person.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot2_effsafe_prepost_raincloud <- ggplot(foodsecuritydata_matched_long, aes(x = TIME, y = EFF_SAFE, fill = TIME)) +\n  geom_line(aes(group = PASSWORD), color = \"gray60\", alpha = 0.4, position = position_nudge(x = -0.15)) +\n  geom_violinhalf(alpha = 0.6, position = position_nudge(x = 0.15), show.legend = FALSE) +\n  geom_boxplot(width = 0.1, outlier.shape = NA, show.legend = FALSE) +\n  geom_point(alpha = 0.4, size = 1.2, position = position_nudge(x = -0.15), show.legend = FALSE) +\n  scale_y_continuous(breaks = 1:6, limits = c(1, 6)) +\n  scale_fill_manual(values = c(\"PRE\" = \"#8d14c1\", \"POST\" = \"#f4b400\")) +\n  labs(x = NULL, y = \"Food-safety self-efficacy (1 to 6)\",\n       title = \"Before and after the workshop (raincloud)\") +\n  theme_bw(base_size = 13)\n\nplot2_effsafe_prepost_raincloud\n```\n\n::: {.cell-output-display}\n![Figure 2. The same data as Figure 1 as a paired raincloud plot: half-violins to the right, boxes in the middle, individual points to the left, one gray line per person.](violin_files/figure-html/plot2-effsafe-prepost-raincloud-1.png){fig-alt='For PRE and POST, a half-violin is nudged to the right, a narrow box plot sits at the center, and jittered points are nudged to the left, with gray lines joining each person\\'s PRE and POST points.' width=672}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot2_effsafe_prepost_raincloud.png\", plot = plot2_effsafe_prepost_raincloud, width = 8, height = 5, dpi = 300)\n\n#source: https://easystats.github.io/see/reference/geom_violinhalf.html\n#explanation: position_nudge() moves each layer sideways so the cloud, the box, and the rain do not overlap\n```\n:::\n\n\n#### Step 5: Check the assumption: are the differences normal?\n\nThe paired t-test does not care whether the pretest or the posttest scores are normal. It cares whether the **differences** are. Compute them and check.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoodsecuritydata_matched <- foodsecuritydata_matched |> mutate(EFF_SAFE_DIFF = EFF_SAFE_POST - EFF_SAFE_PRE)\n\nfoodsecuritydata_matched |>\n  summarise(n = n(), mean_diff = mean(EFF_SAFE_DIFF), sd_diff = sd(EFF_SAFE_DIFF),\n            shapiro_p = shapiro.test(EFF_SAFE_DIFF)$p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      n mean_diff sd_diff shapiro_p\n  <int>     <dbl>   <dbl>     <dbl>\n1    59     0.431   0.743     0.593\n```\n\n\n:::\n\n```{.r .cell-code}\n#explanation: post minus pre, so a positive difference is an increase; Shapiro-Wilk on the differences, not on the two columns\n```\n:::\n\n\nThe Shapiro-Wilk p-value is above .05 and there are 59 matched people, so the paired t-test is the right line of the box.\n\n#### Step 6: The paired-samples t-test and its effect size\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ptestmodel1: EFF_SAFE, posttest vs pretest, matched people\nptestmodel1 <- t.test(foodsecuritydata_matched$EFF_SAFE_POST, foodsecuritydata_matched$EFF_SAFE_PRE, paired = TRUE)\nptestmodel1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  foodsecuritydata_matched$EFF_SAFE_POST and foodsecuritydata_matched$EFF_SAFE_PRE\nt = 4.4518, df = 58, p-value = 3.929e-05\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.2370887 0.6244932\nsample estimates:\nmean difference \n       0.430791 \n```\n\n\n:::\n\n```{.r .cell-code}\n# effect size for a paired design: Cohen's d_z = mean difference / SD of the differences\ndz_effsafe <- mean(foodsecuritydata_matched$EFF_SAFE_DIFF) / sd(foodsecuritydata_matched$EFF_SAFE_DIFF)\ndz_effsafe\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5795737\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: https://www.datacamp.com/tutorial/t-tests-r-tutorial; Lakens (2013) for d_z\n#explanation: paired = TRUE is what makes it a one-group test of the differences; post first so the mean difference is post minus pre; d_z: .2 small, .5 medium, .8 large\n```\n:::\n\n\n::: callout-warning\n## Caution: `paired = TRUE` is not optional\n\n`t.test(POST, PRE)` without `paired = TRUE` runs the independent-samples test from [Compare 2 Groups](compare2groups.qmd), treats the same 59 people as 118 different ones, and usually gives a larger p-value. The output's first line tells you which test ran: *Paired t-test* is what you want to see.\n:::\n\n#### Step 7: Report it\n\n\n\nA paired sentence reports both means, the n of matched people, *t*(df), *p*, *d~z~*, and the direction:\n\n> Food-safety self-efficacy increased from before the workshop (*M* = 4.51, *SD* = 0.87) to two weeks after it (*M* = 4.94, *SD* = 0.77), paired *t*(58) = 4.45, *p* < .001, *d~z~* = 0.58, a medium effect (*n* = 59 matched participants; Figure 1).\n\n### Play 2 ([Wilcoxon signed-rank test]{.nonnormal}): compare pretest and posttest on the number of cooking skills known\n\n`COOKKNOW` is a count from 0 to 5, so the differences can only be whole numbers, most of them 0 or 1. That is not a normal distribution and never will be, so this is the non-parametric line of the box. The Wilcoxon signed-rank test ranks the sizes of the differences, keeps their signs, and asks whether the positive differences outweigh the negative ones. It is the Mann-Whitney U's paired cousin.\n\n#### Step 1: Look at the differences\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfoodsecuritydata_matched <- foodsecuritydata_matched |> mutate(COOKKNOW_DIFF = COOKKNOW_POST - COOKKNOW_PRE)\n\nfoodsecuritydata_matched |> count(COOKKNOW_DIFF)                                            # how many people changed by how much\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  COOKKNOW_DIFF     n\n          <dbl> <int>\n1            -2     1\n2            -1     5\n3             0    21\n4             1    21\n5             2     8\n6             3     3\n```\n\n\n:::\n\n```{.r .cell-code}\nfoodsecuritydata_matched |>\n  summarise(n = n(), median_pre = median(COOKKNOW_PRE), median_post = median(COOKKNOW_POST),\n            shapiro_p = shapiro.test(COOKKNOW_DIFF)$p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      n median_pre median_post shapiro_p\n  <int>      <dbl>       <dbl>     <dbl>\n1    59          4           5  0.000641\n```\n\n\n:::\n\n```{.r .cell-code}\n#explanation: a count() of the differences is the best picture of a change in a count; Shapiro-Wilk far below .05 confirms what the count shows\n```\n:::\n\n\nMost people gained one skill, a third stayed the same, a few lost one. Medians, not means, are the summary to report.\n\n#### Step 2: The Wilcoxon signed-rank test and its effect size\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# wilcomodel1: COOKKNOW, posttest vs pretest (Wilcoxon signed-rank)\nwilcomodel1 <- wilcox.test(foodsecuritydata_matched$COOKKNOW_POST, foodsecuritydata_matched$COOKKNOW_PRE, paired = TRUE)\nwilcomodel1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  foodsecuritydata_matched$COOKKNOW_POST and foodsecuritydata_matched$COOKKNOW_PRE\nV = 642.5, p-value = 4.037e-05\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# effect size r from the normal approximation, as in Compare 2 Groups\nn_changed <- sum(foodsecuritydata_matched$COOKKNOW_DIFF != 0)                 # people with a zero difference are dropped by the test\nz_cook <- qnorm(wilcomodel1$p.value / 2)\nr_cook <- abs(z_cook) / sqrt(n_changed)\nr_cook\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.665974\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: R documentation ?wilcox.test; Fritz, Morris, & Richler (2012) for r\n#explanation: paired = TRUE makes it the signed-rank test (statistic V), not the rank-sum test (W); r = |Z| / sqrt(n), using the n the test used; .1 small, .3 medium, .5 large\n```\n:::\n\n\nTwo things to know about the output. With `paired = TRUE` the statistic is `V`, and R's warnings about ties and zeroes are expected with a count: people whose difference is exactly 0 carry no information about direction, so the test sets them aside, which is why `r` uses the number of people who changed. And the first line of the output, *Wilcoxon signed rank test*, is how you confirm the paired version ran.\n\n#### Step 3: Report it\n\n\n\n> The number of basic cooking skills participants said they knew increased from before the workshop (*Mdn* = 4 of 5) to after it (*Mdn* = 5), Wilcoxon signed-rank *V* = 642.5, *p* < .001, *r* = 0.67, a large effect; 32 of 59 matched participants gained at least one skill, 21 reported no change, and 6 reported fewer.\n\n::: callout-warning\n## Caution: a change is not an effect of the workshop\n\nBoth results say that scores went up between the two surveys. They do not say the workshop caused it: the same people might have gained confidence from two more weeks of cooking for themselves, or the people who came back may be the ones who liked the workshop. Write \"increased from pretest to posttest\", not \"the workshop improved\". A control group would be needed to say more, and your Discussion should say so.\n:::\n\n## 🏈 The Lab {#sec-prepost-lab}\n\n:::::: {.ref .ref-tip}\n::: ref-row\n![](images/ref.svg){.ref-img fig-alt=\"Ref the raccoon\"}\n\n**Ref's kickoff.** The lab survey was given twice, six weeks apart, and exported once as `ANTH306_LayConceptionsMH_SYNTHETIC_LONG.xlsx`, the file you cleaned in [Pre/Post Data](prepost.qmd). It has the eight stigma items and one help-seeking question (`HELPSEEK`, 1 to 5) at both times. Two questions, one for each line of the box: did **stigma** (the 8-item composite `STIGMA`) change? Did willingness to **seek help** (`HELPSEEK`, a single rating) change? Run each the way the Play did, then open my check.\n:::\n::::::\n\n\n\n**Before you start.** The file is in the class Google Drive, next to the lab data; put it in your `data` folder. Clean it as in [Pre/Post Data](prepost.qmd) (lowercase and trim `PASSWORD`, `TIME` as a factor, `distinct()`, -99/-50 to `NA`), then score `STIGMA` in long format exactly as `lab_prep.R` does (reverse the four `_R` items with `6 - x`, then the mean of all eight). Pivot `STIGMA` and `HELPSEEK` wide together.\n\n### Lab Play 1 ([paired t-test]{.normal}): compare pretest and posttest on stigma\n\nKeep the people with both stigma scores, draw the paired violin, compute the differences, check their shape, run the paired t-test and *d~z~*.\n\n::: {.callout-tip collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's check: what should you find?\n\n-   323 rows after `distinct()`, 202 people, **121 matched** on `STIGMA`.\n-   Means: pre 2.44, post 2.12; mean difference -0.32 (SD 0.53), Shapiro-Wilk p = 0.322.\n-   Paired *t*(120) = -6.59, *p* < .001, *d~z~* = -0.60. Stigma went **down**: a negative difference and a negative *t* mean post is lower than pre.\n:::\n\n### Lab Play 2 ([Wilcoxon signed-rank]{.nonnormal}): compare pretest and posttest on willingness to seek help\n\n`HELPSEEK` is one 1-to-5 question. Keep the people with both answers, `count()` the differences, run the Wilcoxon signed-rank test and *r*.\n\n::: {.callout-tip collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's check: what should you find?\n\n-   **114 matched** on `HELPSEEK` (fewer than on `STIGMA`: some people skipped the question at one time).\n-   Differences: 11 went down, 65 no change, 38 went up. Medians: pre 4, post 4. The medians are the same, and the test is still significant: a signed-rank test is about the differences, and 38 up against 11 down is lopsided. Report the counts of up / same / down alongside the medians.\n-   Wilcoxon signed-rank *V* = 950, *p* < .001, *r* = 0.55 (using the 49 people who changed).\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\"}\n## 👀 See the solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse); library(readxl); library(see)\n\nlab_long <- read_excel(\"data/ANTH306_LayConceptionsMH_SYNTHETIC_LONG.xlsx\") |>\n  mutate(PASSWORD = tolower(trimws(PASSWORD)),\n         TIME = factor(TIME, levels = c(0, 1), labels = c(\"PRE\", \"POST\"))) |>\n  distinct(PASSWORD, TIME, .keep_all = TRUE) |>\n  mutate(across(where(is.numeric), ~ replace(.x, .x %in% c(-99, -50), NA))) |>\n  mutate(across(ends_with(\"_R\"), ~ 6 - .x, .names = \"{.col}ev\"),\n         STIGMA = rowMeans(across(c(STIGMA_PUB1, STIGMA_PUB2, STIGMA_PUB3, STIGMA_PUB4_Rev,\n                                    STIGMA_SELF1_Rev, STIGMA_SELF2, STIGMA_SELF3, STIGMA_SELF4_Rev)), na.rm = TRUE))\n\nlab_wide <- lab_long |>\n  select(PASSWORD, TIME, STIGMA, HELPSEEK) |>\n  pivot_wider(names_from = TIME, values_from = c(STIGMA, HELPSEEK), names_glue = \"{.value}_{TIME}\")\n\n# Lab Play 1\nlab_st <- lab_wide |> filter(!is.na(STIGMA_PRE), !is.na(STIGMA_POST)) |> mutate(DIFF = STIGMA_POST - STIGMA_PRE)\nnrow(lab_st)\nlab_st |> select(PASSWORD, STIGMA_PRE, STIGMA_POST) |>\n  pivot_longer(-PASSWORD, names_to = \"TIME\", values_to = \"STIGMA\", names_prefix = \"STIGMA_\") |>\n  mutate(TIME = factor(TIME, levels = c(\"PRE\", \"POST\"))) |>\n  ggplot(aes(x = TIME, y = STIGMA)) +\n  geom_line(aes(group = PASSWORD), color = \"gray60\", alpha = 0.4) +\n  geom_violin(aes(fill = TIME), alpha = 0.5, show.legend = FALSE) +\n  geom_boxplot(width = 0.12, outlier.shape = NA) + theme_bw()\nlab_st |> summarise(n = n(), mean_diff = mean(DIFF), sd_diff = sd(DIFF), shapiro_p = shapiro.test(DIFF)$p.value)\nt.test(lab_st$STIGMA_POST, lab_st$STIGMA_PRE, paired = TRUE)\nmean(lab_st$DIFF) / sd(lab_st$DIFF)                                  # d_z\n\n# Lab Play 2\nlab_hs <- lab_wide |> filter(!is.na(HELPSEEK_PRE), !is.na(HELPSEEK_POST)) |> mutate(DIFF = HELPSEEK_POST - HELPSEEK_PRE)\nlab_hs |> count(DIFF)\n# wilcomodel2: HELPSEEK, posttest vs pretest, matched people\nwilcomodel2 <- wilcox.test(lab_hs$HELPSEEK_POST, lab_hs$HELPSEEK_PRE, paired = TRUE)\nwilcomodel2\nabs(qnorm(wilcomodel2$p.value / 2)) / sqrt(sum(lab_hs$DIFF != 0))              # r\n```\n:::\n\n:::\n\n::: {.callout-warning collapse=\"true\" icon=\"false\"}\n## ![](images/ref-whistle.svg){.ref-mini fig-alt=\"Ref the raccoon blowing his whistle\"} Ref's call: fouls to check if your numbers do not match\n\n-   **Fewer matched people than Ref** → `PASSWORD` was not lowercased and trimmed before the pivot, so one person became two.\n-   **`pivot_wider()` complains about values not being uniquely identified** → the duplicate row is still there. `distinct(PASSWORD, TIME, .keep_all = TRUE)` first.\n-   **Your *t* has the opposite sign** → you put `PRE` first. The order is `t.test(POST, PRE, paired = TRUE)` so that the difference is post minus pre.\n-   **The output says *Welch Two Sample t-test*** → `paired = TRUE` is missing.\n-   **Your stigma mean is different** → the `_R` items were not reversed, or `6 - x` was applied to the wrong items. Compare with `lab_prep.R`.\n-   **Your *r* is a little different** → you divided by all matched people instead of the people whose difference is not 0.\n:::\n\n::: {.callout-important .required}\n## Required: a pre/post comparison in your report (Teams 3 and 5)\n\nFor every pre/post comparison in your *RD Report* and *Final Report*: the three n's (started, finished, matched) in Methods; the paired violin or raincloud with lines per person, saved with `ggsave()` and captioned with the matched n; the check on the differences and what it showed; the test that matches the outcome, the paired t-test with *d~z~* for a composite whose differences are roughly normal (Play 1, Step 7) or the Wilcoxon signed-rank test with *r* for a count, a single rating, or skewed differences (Play 2, Step 3); and one sentence in Results in that Play's form, written as \"increased/decreased from pretest to posttest\", not as an effect of the program.\n:::\n\n## 🏆 Your Turn {#sec-prepost-yourturn}\n\n::: {.callout-note .gray icon=\"false\"}\n## There is no Ref. It's game time, your turn!\n\nStart from the `wide_data` and `long_data` you built in [Pre/Post Data](prepost.qmd). Change every word that starts with `SWAP`, pick the line of the box that matches your outcome, and use the checklist.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse); library(see)\n\n# 1. mydata people only (wide_data from Pre/Post Data has SWAPSCORE_PRE and SWAPSCORE_POST)\nmydata <- wide_data |>\n  filter(!is.na(SWAPSCORE_PRE), !is.na(SWAPSCORE_POST)) |>          # SWAP: your composite or outcome\n  mutate(DIFF = SWAPSCORE_POST - SWAPSCORE_PRE)\nnrow(mydata)                                                        # the n for the test; report started / finished / mydata\n\n# 2. look: paired violin with one line per person\nmydata |> select(PASSWORD, SWAPSCORE_PRE, SWAPSCORE_POST) |>\n  pivot_longer(-PASSWORD, names_to = \"TIME\", values_to = \"SCORE\", names_prefix = \"SCORE_\") |>\n  mutate(TIME = factor(TIME, levels = c(\"PRE\", \"POST\"))) |>\n  ggplot(aes(x = TIME, y = SCORE)) +\n  geom_line(aes(group = PASSWORD), color = \"gray60\", alpha = 0.4) +\n  geom_violin(aes(fill = TIME), alpha = 0.5, show.legend = FALSE) +\n  geom_boxplot(width = 0.12, outlier.shape = NA) +\n  labs(x = NULL, y = \"SWAP: outcome (scale)\", title = \"SWAP: title\") + theme_bw()\n# ggsave(\"plots/plot1_SWAPNAME.png\", width = 8, height = 5, dpi = 300)                      # SWAP: the variables and plot type, e.g. plot1_wellbeing_treated_barplot\n\n# 3. the differences\nmydata |> summarise(n = n(), mean_diff = mean(DIFF), sd_diff = sd(DIFF), shapiro_p = shapiro.test(DIFF)$p.value)\nmydata |> count(DIFF)                                               # for a count or a single rating\n\n# 4a. differences roughly normal (parametric): paired t-test and d_z\n# ptestmodel1: SWAP: one line that says what this test compares\nptestmodel1 <- t.test(mydata$SWAPSCORE_POST, mydata$SWAPSCORE_PRE, paired = TRUE)\nptestmodel1\nmean(mydata$DIFF) / sd(mydata$DIFF)                                # d_z: .2 small, .5 medium, .8 large\n\n# 4b. differences not normal, a count, or a single rating (non-parametric): Wilcoxon signed-rank and r\n# wilcomodel1: SWAP: one line that says what this test compares\nwilcomodel1 <- wilcox.test(mydata$SWAPSCORE_POST, mydata$SWAPSCORE_PRE, paired = TRUE)\nwilcomodel1\nabs(qnorm(wilcomodel1$p.value / 2)) / sqrt(sum(mydata$DIFF != 0))              # r: .1 small, .3 medium, .5 large\n```\n:::\n\n\n| Criteria | Ask yourself |\n|----|----|\n| **Design** | Are these the same people measured twice, linked by `PASSWORD`? (Different people in two groups is [Compare 2 Groups](compare2groups.qmd).) |\n| **Matched n** | Did you report how many started, how many finished, and how many were matched, and run the test on the matched people only? |\n| **Which test** | Did you check the shape of the **differences** and say which line of the Analysis Map box you are on: paired t-test (composite, normal differences) or Wilcoxon signed-rank (count, single rating, or skewed differences)? |\n| **Paired** | Does the output's first line say *Paired t-test* or *Wilcoxon signed rank test*? |\n| **Effect size** | Did you report *d~z~* (paired t-test) or *r* (signed-rank), and say whether it is small, medium, or large? |\n| **Plot** | Does the plot show one line per person, and does the caption give the matched n? |\n| **Sentence** | Does your Results sentence have both means (or medians), the matched n, the statistic, *p*, the effect size, and say \"increased\" or \"decreased from pretest to posttest\"? |\n| **Claim** | Does Discussion say the change cannot be attributed to the program without a control group? |\n\n<!-- Single source for the collapsed final-whistle reminder at the END of every coding chapter (7 onward). Edit here only. The full routine lives in find-the-ref.qmd (Ref's Quick Checklist). -->\n\n::: {.callout-note .gray collapse=\"true\" icon=\"false\"}\n## ![](images/ref-whistle.svg){.ref-mini fig-alt=\"Ref the raccoon blowing his whistle\"} Ref's final whistle: before you quit RStudio\n\n**Save → Render → Back up to ELN → Quit, Don't Save workspace.** Details: [Ref's Quick Checklist](find-the-ref.qmd#sec-ref-checklist).\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}