<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Allison Anemone">
<meta name="author" content="Andrew Silhavy">
<meta name="author" content="Vivian Raposo">
<meta name="author" content="Serena Suchdeve">
<meta name="author" content="Shane McCarty">
<meta name="keywords" content="linear regression, multiple regression, lm, predictors, residuals, relationship">

<title>26&nbsp; Relate 3+ Variables – The Quantitative Playbook for R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./start-rdreport.html" rel="next">
<link href="./correlation.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-3960f907883494f1151aa7142734774f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./visualize-relationship.html">Examine Relationships (Lab 5)</a></li><li class="breadcrumb-item"><a href="./regression.html"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Relate 3+ Variables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">The Quantitative Playbook for R</a> 
        <div class="sidebar-tools-main">
    <a href="https://shanemccarty.github.io/FRIplaybook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-git"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Get Started (Lab 1)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./example.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Reproducible Reports</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./layers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Coding a Plot</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RStudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R Software</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./library.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">R Packages</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./codechunks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Start a Report</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./find-the-ref.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Find the Ref</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab1-checklist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Lab 1 Checklist</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Clean Data (Lab 2)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./qualtrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Name &amp; Recode Vars</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./export.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Export Survey Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./import-once.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Import Data Once</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prepost.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Pre/Post Data (#1,3)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vignette.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Vignette Data (#4)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Mutate Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./composite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Creating Composites</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab2-checklist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Lab 2 Checklist</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Map Your Analysis (Lab 3)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis-map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">The Analysis Map</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./describe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Describe Your Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Frequentist Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab3-checklist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Lab 3 Checklist</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Compare Groups (Lab 4)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visualize-comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Visualize a Comparison</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./compare2groups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Compare 2 Groups</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./violin.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">1 Group, Pre/Post</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Compare 3+ Groups</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Examine Relationships (Lab 5)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visualize-relationship.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Visualize a Relationship</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Relate 2 Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Relate 3+ Variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Write Your Report (Lab 6)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./start-rdreport.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Start My Report</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./readme.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Read Me</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./write-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Results</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./citations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Citations &amp; Refs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./quartopub.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Publish in Quarto Pub</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Plays</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-equity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Data Equity</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./import-live.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Import Data Live</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./write-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Write Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Peer Review</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./shiny.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Shiny Data Viz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./website.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Academic Website</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#how-this-chapter-works" id="toc-how-this-chapter-works" class="nav-link active" data-scroll-target="#how-this-chapter-works"><span class="header-section-number">26.1</span> How This Chapter Works</a></li>
  <li><a href="#the-play" id="toc-the-play" class="nav-link" data-scroll-target="#the-play"><span class="header-section-number">26.2</span> 📋 The Play</a>
  <ul class="collapse">
  <li><a href="#play-1-simple-and-multiple-linear-regression-relate-three-predictors-to-perceived-barriers" id="toc-play-1-simple-and-multiple-linear-regression-relate-three-predictors-to-perceived-barriers" class="nav-link" data-scroll-target="#play-1-simple-and-multiple-linear-regression-relate-three-predictors-to-perceived-barriers"><span class="header-section-number">26.2.1</span> Play 1 (simple and multiple linear regression): relate three predictors to perceived barriers</a></li>
  <li><a href="#play-2-multiple-linear-regression-relate-growth-mindset-to-care-based-support-with-gender-as-a-third-variable" id="toc-play-2-multiple-linear-regression-relate-growth-mindset-to-care-based-support-with-gender-as-a-third-variable" class="nav-link" data-scroll-target="#play-2-multiple-linear-regression-relate-growth-mindset-to-care-based-support-with-gender-as-a-third-variable"><span class="header-section-number">26.2.2</span> Play 2 (multiple linear regression): relate growth mindset to care-based support, with gender as a third variable</a></li>
  </ul></li>
  <li><a href="#sec-regression-lab" id="toc-sec-regression-lab" class="nav-link" data-scroll-target="#sec-regression-lab"><span class="header-section-number">26.3</span> 🏈 The Lab</a>
  <ul class="collapse">
  <li><a href="#lab-play-1-simple-regression-draw-left-relate-social-support-to-well-being" id="toc-lab-play-1-simple-regression-draw-left-relate-social-support-to-well-being" class="nav-link" data-scroll-target="#lab-play-1-simple-regression-draw-left-relate-social-support-to-well-being"><span class="header-section-number">26.3.1</span> Lab Play 1 (simple regression): Draw Left, relate social support to well-being</a></li>
  <li><a href="#lab-play-2-multiple-regression-draw-right-add-racialized-identity-as-a-binary-predictor" id="toc-lab-play-2-multiple-regression-draw-right-add-racialized-identity-as-a-binary-predictor" class="nav-link" data-scroll-target="#lab-play-2-multiple-regression-draw-right-add-racialized-identity-as-a-binary-predictor"><span class="header-section-number">26.3.2</span> Lab Play 2 (multiple regression): Draw Right, add racialized identity as a binary predictor</a></li>
  <li><a href="#lab-play-3-multiple-regression-draw-middle-add-racialized-identity-as-a-six-group-predictor" id="toc-lab-play-3-multiple-regression-draw-middle-add-racialized-identity-as-a-six-group-predictor" class="nav-link" data-scroll-target="#lab-play-3-multiple-regression-draw-middle-add-racialized-identity-as-a-six-group-predictor"><span class="header-section-number">26.3.3</span> Lab Play 3 (multiple regression): Draw Middle, add racialized identity as a six-group predictor</a></li>
  </ul></li>
  <li><a href="#sec-regression-yourturn" id="toc-sec-regression-yourturn" class="nav-link" data-scroll-target="#sec-regression-yourturn"><span class="header-section-number">26.4</span> 🏆 Your Turn</a>
  <ul class="collapse">
  <li><a href="#checklist-for-your-rd-report-and-final-report" id="toc-checklist-for-your-rd-report-and-final-report" class="nav-link" data-scroll-target="#checklist-for-your-rd-report-and-final-report"><span class="header-section-number">26.4.1</span> Checklist for your RD Report and Final Report</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://shanemccarty.github.io/FRIplaybook/edit/main/regression.qmd" class="toc-action"><i class="bi bi-git"></i>Edit this page</a></li><li><a href="https://shanemccarty.github.io/FRIplaybook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./visualize-relationship.html">Examine Relationships (Lab 5)</a></li><li class="breadcrumb-item"><a href="./regression.html"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Relate 3+ Variables</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Relate 3+ Variables</span></h1>
<p class="subtitle lead">Linear regression: how to run it and report it</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Allison Anemone </p>
             <p>Andrew Silhavy </p>
             <p>Vivian Raposo </p>
             <p>Serena Suchdeve </p>
             <p>Shane McCarty </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">10.05.2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>This chapter teaches researchers to examine a relationship question with a linear regression in R. Researchers start with a simple regression (one predictor and one outcome), learn to read the intercept, the slope, the p-value, and R-squared, and then add more predictors to build a multiple linear regression, including a categorical predictor such as gender. The chapter shows how to check the residuals (the outcome itself need not be normal), how to report a regression in a sentence and in a table, and which common shortcuts to avoid (leaving a category as a number, and cutting a score into two groups). A second Play re-runs a published FRI result, growth mindset predicting support for care-based violence prevention, with gender added as a third variable. In The Lab, researchers run three models with the lab dataset (one predictor, a binary predictor, and a dummy-coded predictor) and check their own answers. In Your Turn, researchers use a copy-ready template and a checklist for their own research question.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>linear regression, multiple regression, lm, predictors, residuals, relationship</p>
  </div>
</div>

</header>


<!-- Single source for the collapsed kickoff reminder at the START of every coding chapter (7 onward). Edit here only. The full routine lives in find-the-ref.qmd (Ref's Quick Checklist). -->
<div class="gray callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Resources</span><img src="images/ref.svg" class="ref-mini img-fluid" alt="Ref the raccoon"> Ref’s kickoff: find the Ref before you code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Open Project → Open <code>.qmd</code> → Run load-library chunk → Run All Chunks Above → code.</strong> If anything looks wrong, use <a href="./find-the-ref.html#sec-ref-checklist">Ref’s Quick Checklist</a>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Resources</span>Resources: regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><a href="https://moderndive.com/v2/regression.html">ModernDive Ch. 5: Basic Regression</a></li>
<li><a href="https://moderndive.com/v2/multiple-regression.html">ModernDive Ch. 6: Multiple Regression</a></li>
<li><a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html">Documentation for <code>lm()</code></a></li>
</ul>
</div>
</div>
</div>
<section id="how-this-chapter-works" class="level2" data-number="26.1">
<h2 data-number="26.1" class="anchored" data-anchor-id="how-this-chapter-works"><span class="header-section-number">26.1</span> How This Chapter Works</h2>
<p>You will go through this chapter three times, with three different datasets.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Pass</th>
<th>Section</th>
<th>Dataset</th>
<th>What you do</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><a href="#the-play">The Play</a></td>
<td><code>pregnancydata</code> (example, simulated)</td>
<td><strong>Watch the play.</strong> Read the code and the output, step by step.</td>
</tr>
<tr class="even">
<td>2</td>
<td><a href="#sec-regression-lab">The Lab</a></td>
<td>lab dataset</td>
<td><strong>Run the play.</strong> Run two regressions yourself during the R Lab, then check your own work. Labs are not graded.</td>
</tr>
<tr class="odd">
<td>3</td>
<td><a href="#sec-regression-yourturn">Your Turn</a></td>
<td>your team’s dataset</td>
<td><strong>Call your own play.</strong> After you finish all of the R Labs, come back and run the regression for your own research question.</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Go</span>Go: Know your route first
</div>
</div>
<div class="callout-body-container callout-body">
<p>This chapter is the last step on <a href="./analysis-map.html">The Analysis Map</a> for a <strong>relationship</strong> question with <strong>three or more variables</strong>: one outcome that is a score, and two or more predictors. Make your scatterplot first in <a href="./visualize-relationship.html">Visualize a Relationship</a>.</p>
</div>
</div>
</section>
<section id="the-play" class="level2" data-number="26.2">
<h2 data-number="26.2" class="anchored" data-anchor-id="the-play"><span class="header-section-number">26.2</span> 📋 The Play</h2>
<section id="play-1-simple-and-multiple-linear-regression-relate-three-predictors-to-perceived-barriers" class="level3" data-number="26.2.1">
<h3 data-number="26.2.1" class="anchored" data-anchor-id="play-1-simple-and-multiple-linear-regression-relate-three-predictors-to-perceived-barriers"><span class="header-section-number">26.2.1</span> Play 1 (simple and multiple linear regression): relate three predictors to perceived barriers</h3>
<section id="example-data-pregnancydata" class="level4">
<h4 class="anchored" data-anchor-id="example-data-pregnancydata">Example Data: <code>pregnancydata</code></h4>
<p>The example comes from an FRI Public Health team that surveyed people about health beliefs during pregnancy. One of their questions was: <strong>do people with lower social status perceive more barriers to following health advice during pregnancy, after we account for their age and gender?</strong></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Caution: This example dataset is simulated
</div>
</div>
<div class="callout-body-container callout-body">
<p>To protect the people who took the team’s survey, the file used in this chapter does <strong>not</strong> contain their answers. It is a <em>simulated</em> dataset: a computer generated every row so that the variables and their averages look like the team’s data. Use it to learn the play. Do not cite its results.</p>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 48%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>What it is</th>
<th>Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>BARRIERS</code></td>
<td>the <strong>outcome</strong>: perceived barriers (the mean of 9 survey items)</td>
<td>1 = low to 5 = high</td>
</tr>
<tr class="even">
<td><code>SSS</code></td>
<td>subjective social status (a ladder with 10 rungs)</td>
<td>1 = bottom to 10 = top</td>
</tr>
<tr class="odd">
<td><code>AGE</code></td>
<td>age in years</td>
<td>18 and up</td>
</tr>
<tr class="even">
<td><code>GENDER</code></td>
<td>gender</td>
<td>1 = Woman, 2 = Man</td>
</tr>
</tbody>
</table>
</section>
<section id="load-and-import" class="level4">
<h4 class="anchored" data-anchor-id="load-and-import">Load and Import</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>pregnancydata <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/pregnancy_beliefs_SIMULATED.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pregnancydata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      ID                 AGE            GENDER             SSS        
 Length:160         Min.   :18.00   Min.   :-99.000   Min.   :-99.00  
 Class :character   1st Qu.:19.00   1st Qu.:  1.000   1st Qu.:  5.00  
 Mode  :character   Median :22.00   Median :  1.000   Median :  6.00  
                    Mean   :28.53   Mean   : -0.675   Mean   :  2.35  
                    3rd Qu.:34.25   3rd Qu.:  1.000   3rd Qu.:  7.00  
                    Max.   :63.00   Max.   :  2.000   Max.   : 10.00  
                    NA's   :4                                         
    BARRIERS    
 Min.   :1.000  
 1st Qu.:1.670  
 Median :2.220  
 Mean   :2.226  
 3rd Qu.:2.697  
 Max.   :4.000  
                </code></pre>
</div>
</div>
<p>Look at the minimum of <code>SSS</code> and <code>GENDER</code>. A value of -99 is not a real answer. It is the code for “Prefer not to answer”, and it has to become missing (<code>NA</code>) before you analyze anything.</p>
</section>
<section id="step-1-get-the-data-ready" class="level4">
<h4 class="anchored" data-anchor-id="step-1-get-the-data-ready">Step 1: Get the data ready</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>pregnancydata <span class="ot">&lt;-</span> pregnancydata <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">SSS    =</span> <span class="fu">na_if</span>(SSS, <span class="sc">-</span><span class="dv">99</span>),                       <span class="co"># -99 becomes NA (missing)</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">GENDER =</span> <span class="fu">na_if</span>(GENDER, <span class="sc">-</span><span class="dv">99</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">GENDER =</span> <span class="fu">factor</span>(GENDER,                         <span class="co"># tell R that GENDER is a category</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Woman"</span>, <span class="st">"Man"</span>)))</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pregnancydata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      ID                 AGE          GENDER         SSS        
 Length:160         Min.   :18.00   Woman:125   Min.   : 2.000  
 Class :character   1st Qu.:19.00   Man  : 32   1st Qu.: 5.000  
 Mode  :character   Median :22.00   NA's :  3   Median : 6.000  
                    Mean   :28.53               Mean   : 6.299  
                    3rd Qu.:34.25               3rd Qu.: 7.750  
                    Max.   :63.00               Max.   :10.000  
                    NA's   :4                   NA's   :6       
    BARRIERS    
 Min.   :1.000  
 1st Qu.:1.670  
 Median :2.220  
 Mean   :2.226  
 3rd Qu.:2.697  
 Max.   :4.000  
                </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Caution: Don’t leave a category as a number
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the data file, <code>GENDER</code> is stored as the numbers 1 and 2. If you leave it that way, R treats gender as a <em>score</em>, as if a man were “one unit more” than a woman. <code>factor()</code> tells R that the numbers are labels for groups. Do this for <strong>every</strong> categorical predictor before you run a regression.</p>
</div>
</div>
</section>
<section id="step-2-look-before-you-test" class="level4">
<h4 class="anchored" data-anchor-id="step-2-look-before-you-test">Step 2: Look before you test</h4>
<p>Always make the plot first (see <a href="./visualize-relationship.html">Visualize a Relationship</a>). <code>BARRIERS</code> is a mean of survey items, so points can stack. Jitter them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>plot1_barriers_sss_scatter <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> pregnancydata,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mapping =</span> <span class="fu">aes</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> SSS,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> BARRIERS)) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.15</span>, <span class="at">height =</span> <span class="fl">0.05</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">1</span>, <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">1</span>, <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Social Status and Perceived Barriers"</span>) <span class="sc">+</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Subjective social status (1 = bottom rung, 10 = top rung)"</span>) <span class="sc">+</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Perceived barriers (1 = low, 5 = high)"</span>) <span class="sc">+</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>plot1_barriers_sss_scatter</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/plot1-barriers-sss-scatter-1.png" class="img-fluid figure-img" alt="A scatterplot with subjective social status on the x axis and perceived barriers on the y axis. The line of best fit slopes downward." width="672"></p>
<figcaption>Figure 1. Subjective social status and perceived barriers in the simulated pregnancydata dataset. Points are jittered; the line is a linear line of best fit.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"plots/plot1_barriers_sss_scatter.png"</span>, <span class="at">plot =</span> plot1_barriers_sss_scatter, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The line slopes downward: people who place themselves higher on the ladder report fewer barriers. A regression puts a number on that line and tests it.</p>
</section>
<section id="step-3-one-predictor-simple-regression" class="level4">
<h4 class="anchored" data-anchor-id="step-3-one-predictor-simple-regression">Step 3: One predictor (simple regression)</h4>
<p>The function is <code>lm()</code>, which stands for <em>linear model</em>. Read the formula <code>BARRIERS ~ SSS</code> as “<strong><code>BARRIERS</code> is predicted by <code>SSS</code></strong>”. The outcome always goes on the left of the <code>~</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regmodel1: BARRIERS predicted by SSS alone (simple regression)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>regmodel1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BARRIERS <span class="sc">~</span> SSS, <span class="at">data =</span> pregnancydata)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regmodel1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BARRIERS ~ SSS, data = pregnancydata)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.39107 -0.50107 -0.05018  0.49349  1.67425 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.04994    0.22107  13.796  &lt; 2e-16 ***
SSS         -0.13177    0.03392  -3.884 0.000153 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7037 on 152 degrees of freedom
  (6 observations deleted due to missingness)
Multiple R-squared:  0.0903,    Adjusted R-squared:  0.08432 
F-statistic: 15.09 on 1 and 152 DF,  p-value: 0.0001527</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Go</span>Go: name every test <code>ttestmodel1</code>, <code>regmodel1</code>, and say what each number means
</div>
</div>
<div class="callout-body-container callout-body">
<p>Do not call a model <code>model</code>. By the end of a report you will have several, and <code>model</code> tells nobody which one a table came from. Name each one with the test and a number, nothing else: the number is the order you ran them in, the same order papers use in a regression table (Model 1, Model 2). Then, on the line above every test, write a comment that says what that number means, because <code>regmodel2</code> on its own does not:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regmodel1: BARRIERS predicted by SSS alone (simple regression)</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>regmodel1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BARRIERS <span class="sc">~</span> SSS, <span class="at">data =</span> pregnancydata)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># regmodel2: regmodel1 + AGE + GENDER (multiple regression)</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>regmodel2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BARRIERS <span class="sc">~</span> SSS <span class="sc">+</span> AGE <span class="sc">+</span> GENDER, <span class="at">data =</span> pregnancydata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>One name for each test in this playbook:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Independent-samples t-test</td>
<td><code>ttestmodel1</code></td>
</tr>
<tr class="even">
<td>Mann-Whitney U</td>
<td><code>mannmodel1</code></td>
</tr>
<tr class="odd">
<td>Paired-samples t-test</td>
<td><code>ptestmodel1</code></td>
</tr>
<tr class="even">
<td>Wilcoxon signed-rank</td>
<td><code>wilcomodel1</code></td>
</tr>
<tr class="odd">
<td>ANOVA, Kruskal-Wallis, ANCOVA</td>
<td><code>anovamodel1</code>, <code>kruskalmodel1</code>, <code>ancovamodel1</code></td>
</tr>
<tr class="even">
<td>Pearson, Spearman</td>
<td><code>pearsonmodel1</code>, <code>spearmanmodel1</code></td>
</tr>
<tr class="odd">
<td>Linear regression</td>
<td><code>regmodel1</code>, <code>regmodel2</code>, …</td>
</tr>
</tbody>
</table>
<p>Lowercase, like every object in this playbook; the uppercase names are variables.</p>
</div>
</div>
<p>How to read the output:</p>
<ul>
<li><strong><code>(Intercept)</code>, Estimate = 3.05.</strong> This is where the line starts: the predicted <code>BARRIERS</code> score for a person whose <code>SSS</code> is 0. It is rarely interesting by itself.</li>
<li><strong><code>SSS</code>, Estimate = -0.13.</strong> This is the <strong>slope</strong>, and it is the number you care about. For every one rung higher on the ladder, the predicted <code>BARRIERS</code> score goes <em>down</em> by 0.13 points. A negative slope is a line that goes down. A positive slope is a line that goes up.</li>
<li><strong><code>Pr(&gt;|t|)</code></strong> is the <strong>p-value</strong> for that slope. Here it is less than .001, which is smaller than .05, so the relationship is statistically significant.</li>
<li><strong><code>Multiple R-squared</code> = 0.09.</strong> <code>SSS</code> explains about 9% of the differences between people in <code>BARRIERS</code>. In survey research, small values like this are common.</li>
<li>At the bottom, R tells you how many people were left out because of missing answers. Report the number of people who were <em>in</em> the model: <code>nobs(regmodel1)</code> = 154.</li>
</ul>
</section>
<section id="step-4-three-predictors-multiple-regression" class="level4">
<h4 class="anchored" data-anchor-id="step-4-three-predictors-multiple-regression">Step 4: Three predictors (multiple regression)</h4>
<p>To add predictors, add them to the formula with <code>+</code>. This answers the team’s real question: is social status still related to barriers <strong>after we account for</strong> age and gender?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regmodel2: regmodel1 + AGE + GENDER (multiple regression)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>regmodel2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(BARRIERS <span class="sc">~</span> SSS <span class="sc">+</span> AGE <span class="sc">+</span> GENDER, <span class="at">data =</span> pregnancydata)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regmodel2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = BARRIERS ~ SSS + AGE + GENDER, data = pregnancydata)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.50023 -0.48651 -0.02719  0.52032  1.71508 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.050186   0.235938  12.928  &lt; 2e-16 ***
SSS         -0.126588   0.034820  -3.636 0.000385 ***
AGE         -0.002173   0.004318  -0.503 0.615577    
GENDERMan    0.130783   0.142325   0.919 0.359684    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6986 on 144 degrees of freedom
  (12 observations deleted due to missingness)
Multiple R-squared:  0.09423,   Adjusted R-squared:  0.07536 
F-statistic: 4.993 on 3 and 144 DF,  p-value: 0.002524</code></pre>
</div>
</div>
<p>Each slope now means “the change in <code>BARRIERS</code> for one more unit of this predictor, <strong>when the other predictors stay the same</strong>.”</p>
<ul>
<li><strong><code>SSS</code></strong> (b = -0.13, p &lt; .001): still negative and still significant. Social status is related to barriers even when you compare people of the same age and gender.</li>
<li><strong><code>AGE</code></strong> (b = -0.002, p = .616): the slope is almost zero and the p-value is larger than .05. Age is not related to barriers in this sample.</li>
<li><strong><code>GENDERMan</code></strong> (b = 0.13, p = .360): for a category, R picks the first group (<code>Woman</code>) as the comparison group and reports how different the <em>other</em> group is. Men scored 0.13 points higher than women, and that difference is not significant.</li>
<li><strong>n = 148.</strong> A person is dropped if they are missing <strong>any</strong> variable in the model, so the more predictors you add, the fewer people you keep.</li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Caution: Related does not mean caused
</div>
</div>
<div class="callout-body-container callout-body">
<p>A regression on survey data tells you that two things go together. It does not tell you that one <em>causes</em> the other. Write “is related to”, “is associated with”, or “predicts”. Do not write “leads to”, “affects”, or “causes”.</p>
</div>
</div>
</section>
<section id="step-5-check-the-residuals" class="level4">
<h4 class="anchored" data-anchor-id="step-5-check-the-residuals">Step 5: Check the residuals</h4>
<p>A <strong>residual</strong> is how far each person is from the line. A linear regression works best when the residuals are roughly bell-shaped (normal). This is the “is it normal?” question from the Analysis Map, asked about the residuals and not about the raw scores.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>plot2_barriers_residuals_histogram <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">residual =</span> <span class="fu">resid</span>(regmodel2)),</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> residual)) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">"#005a43"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Residual (actual score minus predicted score)"</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Number of people"</span>) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>plot2_barriers_residuals_histogram</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/plot2-barriers-residuals-histogram-1.png" class="img-fluid figure-img" alt="A histogram of regression residuals centered on zero with a roughly symmetric bell shape." width="576"></p>
<figcaption>Figure 2. Histogram of the residuals from the multiple regression. The shape is roughly bell-shaped.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"plots/plot2_barriers_residuals_histogram.png"</span>, <span class="at">plot =</span> plot2_barriers_residuals_histogram, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If your histogram has one long tail or two humps, talk to your peer mentor and/or Dr.&nbsp;Shane before you report the model.</p>
</section>
<section id="step-6-report-it" class="level4">
<h4 class="anchored" data-anchor-id="step-6-report-it">Step 6: Report it</h4>
<p>Report the slope (b), the p-value, and the number of people for each predictor, and R-squared for the whole model.</p>
<blockquote class="blockquote">
<p>A multiple linear regression (n = 148) showed that subjective social status was negatively associated with perceived barriers (b = -0.13, p &lt; .001), after accounting for age and gender. Age (b = -0.002, p = .616) and gender (b = 0.13, p = .360) were not significantly associated with perceived barriers. Together, the three predictors explained 9% of the variance in perceived barriers (R² = .09).</p>
</blockquote>
<p>You can also print the coefficients as a table:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">summary</span>(regmodel2)<span class="sc">$</span>coefficients,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Table 1. Multiple linear regression predicting perceived barriers."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1. Multiple linear regression predicting perceived barriers.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3.050</td>
<td style="text-align: right;">0.236</td>
<td style="text-align: right;">12.928</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">SSS</td>
<td style="text-align: right;">-0.127</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">-3.636</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AGE</td>
<td style="text-align: right;">-0.002</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">-0.503</td>
<td style="text-align: right;">0.616</td>
</tr>
<tr class="even">
<td style="text-align: left;">GENDERMan</td>
<td style="text-align: right;">0.131</td>
<td style="text-align: right;">0.142</td>
<td style="text-align: right;">0.919</td>
<td style="text-align: right;">0.360</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="play-2-multiple-linear-regression-relate-growth-mindset-to-care-based-support-with-gender-as-a-third-variable" class="level3" data-number="26.2.2">
<h3 data-number="26.2.2" class="anchored" data-anchor-id="play-2-multiple-linear-regression-relate-growth-mindset-to-care-based-support-with-gender-as-a-third-variable"><span class="header-section-number">26.2.2</span> Play 2 (multiple linear regression): relate growth mindset to care-based support, with gender as a third variable</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Resources</span>About the dataset: <code>safety_data.csv</code> (an FRI Public Health team’s data, Cohort 11)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In fall 2025 an FRI Public Health team (Serena Suchdeve, Vivian Raposo, Caitlin Ngo, Kayla Vo, and Rowen Smith) surveyed Binghamton University students and Broome County residents about community safety: how safe and connected they feel in their neighborhood, how effective they believe different violence-prevention approaches are (care-based approaches such as community programs, education, and mental-health resources; fear-based approaches such as policing and deportation), and whether they hold a growth or a fixed mindset about whether people can change (Dweck’s Kind of Person Implicit Theory scale). Their report, <a href="https://vraposo.quarto.pub/mixed-methods-analysis-of-preferences-for-community-based-violence-prevention-and-intervention-approaches/"><em>Mixed-Methods Analysis of Preferences for Community-Based Violence Prevention and Intervention Approaches</em></a>, found that a growth mindset predicted support for care-based community interventions (<em>b</em> = .57, <em>p</em> = .001, <em>R</em>² = .23) but not for fear-based policing. This chapter re-runs part of that analysis so you can see a published FRI result come out of the same code you are learning.</p>
<p>This is <strong>real data</strong>, de-identified for the playbook: the 75 consenting respondents who completed at least half of the survey, with response IDs, dates, ZIP codes, free-text answers, and the open-ended questions removed. The coded values are exactly as exported, so <code>-99</code> (prefer not to say) and <code>-50</code> (don’t know) are still there for you to recode. Variables used in the chapters:</p>
<ul>
<li><code>FIXEDPERSON1_BASIC</code> … <code>FIXEDPERSON_ALL_R</code>: the eight mindset items, on a 1 = Strongly agree to 6 = Strongly disagree scale (note the direction). Items without <code>_R</code> state a <strong>fixed</strong> mindset (“Everyone is a certain kind of person, and there is not much that can be done to really change that”), so a higher number means more growth mindset; items with <code>_R</code> state a <strong>growth</strong> mindset and are reversed. The mean of all eight is the composite <code>GROWTH</code> (higher = more growth mindset).</li>
<li><code>COMM_FEEL</code>, <code>COMM_HELP</code>, <code>COMM_NEIGHBORS</code>, <code>NOTCOMM_UNSAFE</code>, <code>NOTCOMM_RELY</code>, <code>NOTCOMM_DISTRUST</code>: six neighborhood items (1 = Strongly disagree to 6 = Strongly agree); the three <code>NOTCOMM</code> items are reversed for the composite <code>COMMUNITY</code>.</li>
<li><code>EFFECT_CARE_COMM</code>: “Community-based interventions are the most effective way to achieve community safety” (1 to 6), a single item; <code>EFFECT_FEAR_POLICE</code>: the same for policing.</li>
<li><code>GENDER</code>: the class coding, 0 = Girl or woman, 1 = Boy or man, 2 = Nonbinary, genderfluid, or genderqueer; <code>AGE</code>; <code>SOCIALSTATUS</code> (1 to 10).</li>
</ul>
<p>Cite the team’s report when you use this dataset: Suchdeve, S., Raposo, V., Ngo, C., Vo, K., &amp; Smith, R. (2025). <em>Mixed-methods analysis of preferences for community-based violence prevention and intervention approaches</em>. FRI Public Health, Binghamton University. <a href="https://vraposo.quarto.pub/mixed-methods-analysis-of-preferences-for-community-based-violence-prevention-and-intervention-approaches/" class="uri">https://vraposo.quarto.pub/mixed-methods-analysis-of-preferences-for-community-based-violence-prevention-and-intervention-approaches/</a></p>
</div>
</div>
</div>
<p><a href="./correlation.html">Relate 2 Variables</a> Play 3 showed that growth mindset and support for care-based community interventions go together (<em>ρ</em> = .42). The team’s report went one step further with a regression, and this play goes one step further still by adding <strong>gender</strong> as a third variable, the way their Figure 3 did: one line for women and one for men. The question becomes: does growth mindset predict support for care-based interventions, and is that relationship the same for women and men?</p>
<section id="step-1-import-score-and-make-gender-a-factor" class="level4">
<h4 class="anchored" data-anchor-id="step-1-import-score-and-make-gender-a-factor">Step 1: Import, score, and make gender a factor</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>safetydata <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/safety_data.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">replace</span>(.x, .x <span class="sc">%in%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">99</span>, <span class="sc">-</span><span class="dv">50</span>), <span class="cn">NA</span>))) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GROWTH =</span> <span class="fu">rowMeans</span>(<span class="fu">cbind</span>(FIXEDPERSON1_BASIC, FIXEDPERSON2_DIFF, FIXEDPERSON4_OLD, FIXEDPERSON_CERTAIN,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                                 <span class="dv">7</span> <span class="sc">-</span> FIXEDPERSON3_CHANGE_R, <span class="dv">7</span> <span class="sc">-</span> FIXEDPERSON_ALL_R,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>                                 <span class="dv">7</span> <span class="sc">-</span> FIXEDPERSON_ALWAYS_R, <span class="dv">7</span> <span class="sc">-</span> FIXEDPERSON_MATTER_R), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(GENDER <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">|&gt;</span>                                             <span class="co"># two gender groups for the third variable</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GENDER =</span> <span class="fu">factor</span>(GENDER, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Women"</span>, <span class="st">"Men"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(GROWTH), <span class="sc">!</span><span class="fu">is.na</span>(EFFECT_CARE_COMM))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(safetydata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 68</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>safetydata <span class="sc">|&gt;</span> <span class="fu">count</span>(GENDER)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  GENDER  n
1  Women 44
2    Men 24</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#source: Suchdeve et al. (2025); Relate 2 Variables (Play 3)</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co">#explanation: the same composite as the correlation chapter; GENDER becomes a labeled factor with women first, so the regression's gender slope reads "men compared with women"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="step-2-look-one-line-per-gender" class="level4">
<h4 class="anchored" data-anchor-id="step-2-look-one-line-per-gender">Step 2: Look: one line per gender</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>plot3_care_growth_gender_scatter <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(safetydata, <span class="fu">aes</span>(<span class="at">x =</span> GROWTH, <span class="at">y =</span> EFFECT_CARE_COMM, <span class="at">color =</span> GENDER, <span class="at">fill =</span> GENDER)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.05</span>, <span class="at">height =</span> <span class="fl">0.15</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">alpha =</span> <span class="fl">0.15</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">6</span>)) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">0.7</span>, <span class="fl">6.3</span>),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Strongly</span><span class="sc">\n</span><span class="st">disagree"</span>, <span class="st">"Disagree"</span>, <span class="st">"Slightly</span><span class="sc">\n</span><span class="st">disagree"</span>, <span class="st">"Slightly</span><span class="sc">\n</span><span class="st">agree"</span>, <span class="st">"Agree"</span>, <span class="st">"Strongly</span><span class="sc">\n</span><span class="st">agree"</span>)) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Women"</span> <span class="ot">=</span> <span class="st">"#8d14c1"</span>, <span class="st">"Men"</span> <span class="ot">=</span> <span class="st">"#f4b400"</span>)) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Women"</span> <span class="ot">=</span> <span class="st">"#8d14c1"</span>, <span class="st">"Men"</span> <span class="ot">=</span> <span class="st">"#f4b400"</span>)) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Growth mindset (1 = fixed, 6 = growth)"</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Community-based interventions are</span><span class="sc">\n</span><span class="st">the most effective way to achieve safetydata"</span>,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Gender"</span>, <span class="at">fill =</span> <span class="st">"Gender"</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Growth mindset and care-based support, by gender"</span>) <span class="sc">+</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>plot3_care_growth_gender_scatter</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/plot3-care-growth-gender-scatter-1.png" class="img-fluid figure-img" alt="A scatterplot with growth mindset on the x axis and agreement that community-based interventions are the most effective way to achieve safetydata on the y axis. Points and two rising lines of best fit, purple for women and gold for men, with overlapping confidence bands; both lines slope upward at a similar angle." width="672"></p>
<figcaption>Figure 3. Support for care-based community interventions against growth mindset, by gender (Cohort 11 community safetydata data, n = 68). Points are jittered; each line is the line of best fit for that gender, with its 95% confidence band.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"plots/plot3_care_growth_gender_scatter.png"</span>, <span class="at">plot =</span> plot3_care_growth_gender_scatter, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co">#source: Visualize a Relationship (Play 2)</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co">#explanation: color = GENDER inside aes() gives each gender its own points and its own geom_smooth() line; the two lines rising together is what "the relationship is the same for women and men" looks like</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The two lines rise at almost the same angle and their bands overlap along their whole length. That picture predicts what the regression will say: a growth-mindset slope that matters, and a gender difference that does not.</p>
</section>
<section id="step-3-the-regression-with-two-predictors" class="level4">
<h4 class="anchored" data-anchor-id="step-3-the-regression-with-two-predictors">Step 3: The regression with two predictors</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regmodel3: support for care-based interventions predicted by GROWTH and GENDER</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>regmodel3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(EFFECT_CARE_COMM <span class="sc">~</span> GROWTH <span class="sc">+</span> GENDER, <span class="at">data =</span> safetydata)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regmodel3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = EFFECT_CARE_COMM ~ GROWTH + GENDER, data = safetydata)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.7663 -0.6097  0.1350  0.6319  1.6987 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.0848     0.6133   3.399  0.00116 ** 
GROWTH        0.6114     0.1365   4.479  3.1e-05 ***
GENDERMen     0.2867     0.2583   1.110  0.27123    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9863 on 65 degrees of freedom
Multiple R-squared:  0.2359,    Adjusted R-squared:  0.2123 
F-statistic: 10.03 on 2 and 65 DF,  p-value: 0.0001596</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#source: https://www.datacamp.com/tutorial/multiple-linear-regression-r-tutorial</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co">#explanation: one continuous predictor and one factor; the GENDERMen row is the difference between men and women at the same level of growth mindset</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Read the two predictor rows. <code>GROWTH</code> is the slope: for each one-point increase in growth mindset, support for care-based interventions rises by about half a point on the 1-to-6 scale, holding gender constant. <code>GENDERMen</code> is the gender difference <em>at the same growth mindset</em>: positive means men a little higher, but its p-value says the difference could easily be zero. <code>Multiple R-squared</code> is the share of the variation in support that the two predictors explain together.</p>
</section>
<section id="step-4-check-the-residuals-not-the-outcome" class="level4">
<h4 class="anchored" data-anchor-id="step-4-check-the-residuals-not-the-outcome">Step 4: Check the residuals, not the outcome</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>plot4_care_residuals_histogram <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">residual =</span> <span class="fu">resid</span>(regmodel3)), <span class="fu">aes</span>(<span class="at">x =</span> residual)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">15</span>, <span class="at">fill =</span> <span class="st">"#005a43"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Residual (actual score minus predicted score)"</span>, <span class="at">y =</span> <span class="st">"Number of people"</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>plot4_care_residuals_histogram</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/plot4-care-residuals-histogram-1.png" class="img-fluid figure-img" alt="A histogram of regression residuals centered on zero, roughly symmetric, with a few more values on the negative side." width="576"></p>
<figcaption>Figure 4. Histogram of the residuals from the two-predictor model. Roughly bell-shaped, with a slightly longer left tail.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"plots/plot4_care_residuals_histogram.png"</span>, <span class="at">plot =</span> plot4_care_residuals_histogram, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">dpi =</span> <span class="dv">300</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">resid</span>(regmodel3))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  resid(regmodel3)
W = 0.96869, p-value = 0.08486</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#explanation: the outcome is a single 1-to-6 item and is not normal; the regression does not need it to be. What it needs is roughly normal residuals, and these pass</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This is the point the Analysis Map’s regression box makes: <code>EFFECT_CARE_COMM</code> is one Likert item, and its own histogram is nothing like a bell, yet the residuals are acceptable, so the model stands. Had the residual histogram shown a long tail or two humps, the fix would be a different model, not a different outcome.</p>
</section>
<section id="step-5-report-it-and-compare-with-the-published-result" class="level4">
<h4 class="anchored" data-anchor-id="step-5-report-it-and-compare-with-the-published-result">Step 5: Report it, and compare with the published result</h4>
<blockquote class="blockquote">
<p>A multiple linear regression (n = 68) showed that growth mindset was positively associated with the belief that community-based interventions are the most effective way to achieve community safety (<em>b</em> = 0.61, <em>p</em> &lt; .001), after accounting for gender. Men and women did not differ at the same level of growth mindset (<em>b</em> = 0.29, <em>p</em> = .271). The model explained 24% of the variation in support (<em>R</em>² = .24) (Figure 3).</p>
</blockquote>
<p>Suchdeve et al.&nbsp;(2025) reported <em>b</em> = .57 for growth mindset with perceived community safety as the second predictor, in a sample of 54; here the slope is 0.61 with gender as the second predictor, in a sample of 68. Same data, same direction, same size of effect, with a different second predictor and slightly different exclusion rules: that is what a result that holds up looks like, and the small difference is a reminder to say in Methods exactly whom you excluded and why.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Go</span>Go: a slope for each group is an interaction, and that is a different model
</div>
</div>
<div class="callout-body-container callout-body">
<p>Figure 3 draws a separate line for women and men, but the model in Step 3 fits <strong>one</strong> slope for growth mindset and shifts the line up or down by gender. That is the right model when the lines are parallel, as they are here. If the lines had crossed or fanned apart, the question would be whether the <em>slope</em> differs by gender, which is an <strong>interaction</strong> (<code>GROWTH * GENDER</code> in the formula). Interactions are beyond this playbook; if your plot shows clearly non-parallel lines, bring it to your peer mentor and/or Dr.&nbsp;Shane.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Caution: Don’t cut your score into two groups
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is tempting to turn a score into “high” and “low” (or 0 and 1) and then run a regression on the 0s and 1s. Don’t. You throw away most of the information in your score, the cut point is arbitrary, and small groups give unstable results. Keep your outcome as a score and use <code>lm()</code>. If your outcome really <em>is</em> a category (yes or no), <code>lm()</code> is the wrong tool: you need a logistic regression, which is not covered in this playbook. Talk to your peer mentor and/or Dr.&nbsp;Shane.</p>
</div>
</div>
</section>
</section>
</section>
<section id="sec-regression-lab" class="level2" data-number="26.3">
<h2 data-number="26.3" class="anchored" data-anchor-id="sec-regression-lab"><span class="header-section-number">26.3</span> 🏈 The Lab</h2>
<p>You watched the play above with the simulated <code>pregnancydata</code> dataset (Pass 1). Now run three plays yourself with the <strong>lab dataset</strong>, a survey about what people believe about mental health.</p>
<div class="ref ref-tip">
<div class="ref-face">
<p><img src="images/ref.svg" class="img-fluid" alt="Ref the raccoon"></p>
</div>
<div class="ref-say">
<p><strong>Ref’s kickoff.</strong> This lab is not graded, so I am here to help you check your own work. Try each play <strong>before</strong> you open my check or the solution. If your answer does not match, that is not a penalty. It is how you find out what to fix.</p>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Lab play</th>
<th>What is new</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Draw Left</td>
<td>one predictor: read a slope, a p-value, and R-squared</td>
</tr>
<tr class="even">
<td>Draw Right</td>
<td>add a <strong>binary</strong> predictor (two groups)</td>
</tr>
<tr class="odd">
<td>Draw Middle</td>
<td>add a <strong>dummy-coded</strong> predictor (five groups)</td>
</tr>
</tbody>
</table>
<p>All three plays use the same outcome: positive mental well-being (<code>WELLBEING</code>, the average of 8 items, 1 to 5). The first predictor is always perceived social support (<code>SUPPORT</code>, the average of 8 items, 1 to 5).</p>
<p><strong>Before you start</strong></p>
<ol type="1">
<li>Open your RStudio Project and your lab <code>.qmd</code> file.</li>
<li>Load the clean lab data by running this chunk. It runs the cleaning script you built in the earlier labs.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"lab_prep.R"</span>)   <span class="co"># creates mh_clean</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(mh_clean)         <span class="co"># how many people are in the clean dataset?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Go</span><img src="images/ref.svg" class="ref-mini img-fluid" alt="Ref the raccoon"> Ref’s check: how many rows?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>nrow(mh_clean)</code> should be <strong>188</strong>.</p>
</div>
</div>
</div>
<section id="lab-play-1-simple-regression-draw-left-relate-social-support-to-well-being" class="level3" data-number="26.3.1">
<h3 data-number="26.3.1" class="anchored" data-anchor-id="lab-play-1-simple-regression-draw-left-relate-social-support-to-well-being"><span class="header-section-number">26.3.1</span> Lab Play 1 (simple regression): Draw Left, relate social support to well-being</h3>
<p><strong>Research question:</strong> Do people with more social support (<code>SUPPORT</code>) report higher well-being (<code>WELLBEING</code>)?</p>
<p><strong>Your task:</strong> Make a scatterplot with <code>SUPPORT</code> on the x axis and <code>WELLBEING</code> on the y axis, with a line of best fit. Then run the simple regression with <code>lm()</code> and <code>summary()</code>. Write down the slope for <code>SUPPORT</code>, its p-value, R-squared, and the number of people in the model.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Go</span><img src="images/ref.svg" class="ref-mini img-fluid" alt="Ref the raccoon"> Ref’s check: what should you get?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Your line of best fit should go <strong>up</strong>: more support, higher well-being.</li>
<li>Slope for <code>SUPPORT</code>: <strong>b = 0.40</strong>. For every one point higher in social support, predicted well-being is 0.40 points higher.</li>
<li>p-value: <strong>p &lt; .001</strong>, so the relationship is statistically significant.</li>
<li>R-squared: <strong>0.16</strong>. Social support explains about 16% of the differences in well-being.</li>
<li>People in the model: <strong>n = 188</strong>.</li>
</ul>
</div>
</div>
</div>
<div class="gray callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Resources</span>👀 See the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mh_clean,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> SUPPORT, <span class="at">y =</span> WELLBEING)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Perceived social support (1 to 5)"</span>) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Positive mental well-being (1 to 5)"</span>) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/lab-solution-play1-1.png" class="img-fluid figure-img" alt="A scatterplot with social support on the x axis and well-being on the y axis. The line of best fit slopes upward." width="672"></p>
<figcaption>Figure 5. Social support and well-being in the lab dataset. The line is a linear line of best fit.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regmodel4: WELLBEING predicted by SUPPORT alone</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>regmodel4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(WELLBEING <span class="sc">~</span> SUPPORT, <span class="at">data =</span> mh_clean)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regmodel4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = WELLBEING ~ SUPPORT, data = mh_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.63903 -0.39229  0.01805  0.43951  1.69087 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.92051    0.22781    8.43 9.33e-15 ***
SUPPORT      0.40436    0.06717    6.02 9.13e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6194 on 186 degrees of freedom
Multiple R-squared:  0.163, Adjusted R-squared:  0.1585 
F-statistic: 36.24 on 1 and 186 DF,  p-value: 9.129e-09</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nobs</span>(regmodel4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 188</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="lab-play-2-multiple-regression-draw-right-add-racialized-identity-as-a-binary-predictor" class="level3" data-number="26.3.2">
<h3 data-number="26.3.2" class="anchored" data-anchor-id="lab-play-2-multiple-regression-draw-right-add-racialized-identity-as-a-binary-predictor"><span class="header-section-number">26.3.2</span> Lab Play 2 (multiple regression): Draw Right, add racialized identity as a binary predictor</h3>
<p><strong>Research question:</strong> After we account for social support, does well-being differ between People of Color and White respondents?</p>
<p>The survey asked one select-all question about racial/ethnic identity. In <a href="./dplyr.html">Transforming Your Data</a> you combined its checkbox columns (<code>RACIALIZED_1</code> to <code>RACIALIZED_99</code>) into two variables, and <code>lab_prep.R</code> now carries both:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Groups</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>RACIALIZED_6CAT</code></td>
<td>White, Asian, Black, Hispanic or Latine, Another identity, Two or more (a factor)</td>
</tr>
<tr class="even">
<td><code>RACIALIZED_01</code></td>
<td>0 = racialized as white, 1 = racialized as a person of color (everyone who checked any other box, including “Two or more”)</td>
</tr>
</tbody>
</table>
<p>The name is <code>RACIALIZED</code>, not <code>RACE</code>, on purpose: the survey did not measure a trait inside the person, it recorded how people are sorted and sort themselves within a system of racial classification (<a href="./data-equity.html">Data Equity</a>). Read every coefficient below that way: “people racialized as Black,” not “being Black.”</p>
<p>A <strong>binary</strong> predictor has two groups, coded 0 and 1. <strong>Your task:</strong></p>
<ol type="1">
<li>Check the variable before you use it: <code>count(RACIALIZED_6CAT, RACIALIZED_01)</code>. Every White row should have a 0, every other row a 1, and Prefer not to say should be <code>NA</code>.</li>
<li>Run <code>lm(WELLBEING ~ SUPPORT + RACIALIZED_01)</code>.</li>
<li>Read the <code>RACIALIZED_01</code> row. Because the variable is 0/1, its slope is the difference between the group coded 1 and the group coded 0, at the same level of social support.</li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Go</span><img src="images/ref.svg" class="ref-mini img-fluid" alt="Ref the raccoon"> Ref’s check: what should you get?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">RACIALIZED_01</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">94</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">91</td>
</tr>
<tr class="odd">
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">2.095</td>
<td style="text-align: right;">0.228</td>
<td style="text-align: right;">9.205</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">SUPPORT</td>
<td style="text-align: right;">0.399</td>
<td style="text-align: right;">0.066</td>
<td style="text-align: right;">6.056</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACIALIZED_01</td>
<td style="text-align: right;">-0.305</td>
<td style="text-align: right;">0.089</td>
<td style="text-align: right;">-3.429</td>
<td style="text-align: right;">0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>The row is named <code>RACIALIZED_01</code>, and there is only one row for it, because a 0/1 variable needs only one slope. The group coded 0 (White) is the comparison group.</li>
<li><strong>b = -0.30, p &lt; .001</strong>: at the same level of social support, People of Color scored 0.30 points lower in well-being than White respondents.</li>
<li><code>SUPPORT</code> is still positive and significant (b = 0.40, p &lt; .001).</li>
<li>People in the model: <strong>n = 185</strong>. That is 3 fewer than in Lab Play 1, because 3 people chose “Prefer Not To Say”.</li>
</ul>
</div>
</div>
</div>
<div class="gray callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Resources</span>👀 See the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>mh_clean <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(RACIALIZED_6CAT, RACIALIZED_01)   <span class="co"># ALWAYS check a variable before you model it</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 3
  RACIALIZED_6CAT    RACIALIZED_01     n
  &lt;fct&gt;                      &lt;dbl&gt; &lt;int&gt;
1 White                          0    94
2 Asian                          1    19
3 Black                          1    31
4 Hispanic or Latine             1    17
5 Another identity               1     5
6 Two or more                    1    19
7 &lt;NA&gt;                          NA     3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regmodel5: regmodel4 + RACIALIZED_01 (two groups)</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>regmodel5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(WELLBEING <span class="sc">~</span> SUPPORT <span class="sc">+</span> RACIALIZED_01, <span class="at">data =</span> mh_clean)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regmodel5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = WELLBEING ~ SUPPORT + RACIALIZED_01, data = mh_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.78946 -0.41134  0.03634  0.45888  1.53404 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    2.09510    0.22760   9.205  &lt; 2e-16 ***
SUPPORT        0.39867    0.06583   6.056 7.82e-09 ***
RACIALIZED_01 -0.30462    0.08883  -3.429 0.000749 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.604 on 182 degrees of freedom
  (3 observations deleted due to missingness)
Multiple R-squared:  0.2106,    Adjusted R-squared:  0.2019 
F-statistic: 24.27 on 2 and 182 DF,  p-value: 4.53e-10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nobs</span>(regmodel5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 185</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Caution: A group difference is not an explanation
</div>
</div>
<div class="callout-body-container callout-body">
<p>This model tells you that two groups differ. It does not tell you why. In public health, differences between racial and ethnic groups point to differences in people’s conditions and experiences (for example, discrimination or access to care). They are not caused by the identity itself. Write “scored lower than”, and use your literature review to discuss why. To see more on who is counted, who decides, and who benefits when we compare groups, read <a href="./data-equity.html">Data Equity</a>.</p>
</div>
</div>
</section>
<section id="lab-play-3-multiple-regression-draw-middle-add-racialized-identity-as-a-six-group-predictor" class="level3" data-number="26.3.3">
<h3 data-number="26.3.3" class="anchored" data-anchor-id="lab-play-3-multiple-regression-draw-middle-add-racialized-identity-as-a-six-group-predictor"><span class="header-section-number">26.3.3</span> Lab Play 3 (multiple regression): Draw Middle, add racialized identity as a six-group predictor</h3>
<p><strong>Research question:</strong> Two groups hide a lot. Does the difference in well-being look the same for every racial/ethnic group?</p>
<p>A predictor with three or more groups has to be <strong>dummy coded</strong>: one 0/1 column for every group except the comparison group. You do not need to make those columns. When the predictor is a <code>factor()</code>, <code>lm()</code> makes them for you, and you get one row in the output for each group (compared with the first level).</p>
<p><strong>Your task:</strong></p>
<ol type="1">
<li>Count the people in each <code>RACIALIZED_6CAT</code> group with <code>count()</code>. Notice which groups are small.</li>
<li>Check that <code>RACIALIZED_6CAT</code> is a factor whose first level is <code>"White"</code>: <code>levels(mh_clean$RACIALIZED_6CAT)</code>. The first level is the comparison group.</li>
<li>Run <code>lm(WELLBEING ~ SUPPORT + RACIALIZED_6CAT)</code>, make a histogram of the residuals, and write one sentence that reports the result.</li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Go</span><img src="images/ref.svg" class="ref-mini img-fluid" alt="Ref the raccoon"> Ref’s check: what should you get?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">RACIALIZED_6CAT</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">White</td>
<td style="text-align: right;">94</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asian</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Black</td>
<td style="text-align: right;">31</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hispanic or Latine</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Another identity</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Two or more</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 41%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">2.062</td>
<td style="text-align: right;">0.234</td>
<td style="text-align: right;">8.800</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">SUPPORT</td>
<td style="text-align: right;">0.409</td>
<td style="text-align: right;">0.068</td>
<td style="text-align: right;">6.019</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACIALIZED_6CATAsian</td>
<td style="text-align: right;">-0.348</td>
<td style="text-align: right;">0.153</td>
<td style="text-align: right;">-2.273</td>
<td style="text-align: right;">0.024</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACIALIZED_6CATBlack</td>
<td style="text-align: right;">-0.314</td>
<td style="text-align: right;">0.127</td>
<td style="text-align: right;">-2.484</td>
<td style="text-align: right;">0.014</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACIALIZED_6CATHispanic or Latine</td>
<td style="text-align: right;">-0.174</td>
<td style="text-align: right;">0.160</td>
<td style="text-align: right;">-1.084</td>
<td style="text-align: right;">0.280</td>
</tr>
<tr class="even">
<td style="text-align: left;">RACIALIZED_6CATAnother identity</td>
<td style="text-align: right;">-0.180</td>
<td style="text-align: right;">0.280</td>
<td style="text-align: right;">-0.644</td>
<td style="text-align: right;">0.520</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RACIALIZED_6CATTwo or more</td>
<td style="text-align: right;">-0.395</td>
<td style="text-align: right;">0.155</td>
<td style="text-align: right;">-2.551</td>
<td style="text-align: right;">0.012</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>You should see <strong>five</strong> <code>RACIALIZED_6CAT</code> rows, one for every group except White. R adds the group name to the variable name (<code>RACIALIZED_6CATAsian</code>). Each row compares that group with White respondents, at the same level of social support. That is dummy coding, and R did it for you because the variable is a factor.</li>
<li>Asian (b = -0.35, p = .024) and Black (b = -0.31, p = .014) respondents scored significantly lower than White respondents. Hispanic or Latine respondents did not differ significantly (b = -0.17, p = .280). The binary variable in Lab Play 2 hid this.</li>
<li>“Another identity” (b = -0.18, p = .520) has only 5 people. With a group this small, a real difference is hard to detect. Report the count, and do not read much into this row.</li>
<li>People in the model: <strong>n = 185</strong>. R-squared: <strong>0.22</strong>.</li>
<li>Your residual histogram should be roughly bell-shaped and centered on zero.</li>
</ul>
</div>
</div>
</div>
<div class="gray callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Resources</span>👀 See the solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>mh_clean <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(RACIALIZED_6CAT)             <span class="co"># which groups are small?</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  RACIALIZED_6CAT        n
  &lt;fct&gt;              &lt;int&gt;
1 White                 94
2 Asian                 19
3 Black                 31
4 Hispanic or Latine    17
5 Another identity       5
6 Two or more           19
7 &lt;NA&gt;                   3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(mh_clean<span class="sc">$</span>RACIALIZED_6CAT)     <span class="co"># "White" must be first: it is the comparison group</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "White"              "Asian"              "Black"             
[4] "Hispanic or Latine" "Another identity"   "Two or more"       </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># regmodel6: regmodel4 + RACIALIZED_6CAT (six groups, dummy coded by R)</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>regmodel6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(WELLBEING <span class="sc">~</span> SUPPORT <span class="sc">+</span> RACIALIZED_6CAT, <span class="at">data =</span> mh_clean)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regmodel6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = WELLBEING ~ SUPPORT + RACIALIZED_6CAT, data = mh_clean)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.79868 -0.45608  0.01717  0.43928  1.53604 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                         2.0620     0.2343   8.800 1.17e-15 ***
SUPPORT                             0.4086     0.0679   6.019 9.79e-09 ***
RACIALIZED_6CATAsian               -0.3477     0.1530  -2.273   0.0242 *  
RACIALIZED_6CATBlack               -0.3144     0.1266  -2.484   0.0139 *  
RACIALIZED_6CATHispanic or Latine  -0.1738     0.1603  -1.084   0.2797    
RACIALIZED_6CATAnother identity    -0.1802     0.2799  -0.644   0.5204    
RACIALIZED_6CATTwo or more         -0.3952     0.1549  -2.551   0.0116 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6082 on 178 degrees of freedom
  (3 observations deleted due to missingness)
Multiple R-squared:  0.2171,    Adjusted R-squared:  0.1908 
F-statistic: 8.229 on 6 and 178 DF,  p-value: 7.214e-08</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nobs</span>(regmodel6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 185</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">residual =</span> <span class="fu">resid</span>(regmodel6)),</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> residual)) <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">"#005a43"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Residual (actual score minus predicted score)"</span>) <span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Number of people"</span>) <span class="sc">+</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="regression_files/figure-html/lab-solution-play3-1.png" class="img-fluid figure-img" alt="A histogram of regression residuals from the lab dataset, centered on zero and roughly bell-shaped." width="576"></p>
<figcaption>Figure 6. Histogram of the residuals from the lab regression.</figcaption>
</figure>
</div>
</div>
</div>
<p>A multiple linear regression (n = 185) showed that perceived social support was positively associated with well-being (b = 0.41, p &lt; .001), after accounting for racial/ethnic identity. Compared with White respondents, Asian (b = -0.35, p = .024) and Black (b = -0.31, p = .014) respondents reported lower well-being; Hispanic or Latine respondents (p = .280) and respondents with another identity (n = 5; p = .520) did not differ significantly (R² = .22).</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span><img src="images/ref-whistle.svg" class="ref-mini img-fluid" alt="Ref the raccoon blowing his whistle"> Ref’s call: fouls to check if your numbers do not match
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>Your slope is for the wrong variable</strong> → the outcome goes on the <strong>left</strong> of the <code>~</code>. <code>WELLBEING ~ SUPPORT</code>, not <code>SUPPORT ~ WELLBEING</code>.</li>
<li><strong>One row named <code>RACIALIZED_6CAT</code> with a single slope</strong> → the variable is not a factor. R treated the groups as a score. Rebuild it with <code>factor()</code> as in <a href="./dplyr.html">Transforming Your Data</a>. This gives you a wrong answer without any error message.</li>
<li><strong>Your comparison group is not White</strong> → R uses the <strong>first</strong> level as the comparison group. If you leave out <code>levels =</code>, R sorts the groups by the alphabet.</li>
<li><strong>A group is missing from <code>count()</code></strong> → look for a typo in <code>case_when()</code>. Any answer you do not list becomes <code>NA</code>.</li>
<li><strong>Your n is 188</strong> → that is the number of rows in the dataset, not the number of people in the model. Use <code>nobs()</code>.</li>
<li><strong><code>object 'WELLBEING' not found</code></strong> → <code>WELLBEING</code> and <code>SUPPORT</code> are created in <code>lab_prep.R</code>. Run <code>source("lab_prep.R")</code> first.</li>
<li><strong><code>could not find function "ggplot"</code></strong> → run your load-library chunk.</li>
</ul>
</div>
</div>
</div>
<div class="ref ref-tip">
<div class="ref-face">
<p><img src="images/ref.svg" class="img-fluid" alt="Ref the raccoon"></p>
</div>
<div class="ref-say">
<p><strong>Ref’s final whistle.</strong> That is the end of the lab. Save your <code>.qmd</code>, render it, and back up your <code>.qmd</code> and <code>.R</code> files to the <strong>R Labs</strong> folder in your ELN before you quit RStudio.</p>
</div>
</div>
</section>
</section>
<section id="sec-regression-yourturn" class="level2" data-number="26.4">
<h2 data-number="26.4" class="anchored" data-anchor-id="sec-regression-yourturn"><span class="header-section-number">26.4</span> 🏆 Your Turn</h2>
<div class="gray callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Resources</span>There is no Ref. It’s game time, your turn!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nobody has analyzed your team’s data before, so there is no answer to check against. Copy the play, change every word that starts with <code>SWAP</code>, and use the checklist at the end of this section to check your own work. It is the same checklist your peer mentor and Dr.&nbsp;Shane use.</p>
</div>
</div>
<p>Once you finish all of the R Labs, come back here with <strong>your team’s dataset</strong> and run the regression for your relationship research question.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. every categorical predictor must be a factor (skip this if you have none)</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>mydata <span class="ot">&lt;-</span> cleandata <span class="sc">|&gt;</span>                         <span class="co"># cleandata = your cleaned data (Import Data Once); mydata = this analysis</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SWAPGROUP =</span> <span class="fu">factor</span>(SWAPGROUP,           <span class="co"># SWAP: your categorical predictor</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>),               <span class="co"># SWAP: its codes</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"SWAPLABEL1"</span>, <span class="st">"SWAPLABEL2"</span>)))  <span class="co"># SWAP: its labels; the FIRST one is the comparison group</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. run the model: SWAPOUTCOME ~ SWAPPREDICTOR1 + SWAPPREDICTOR2 + ...</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a><span class="co"># regmodel1: SWAP: one line that says what this model predicts and from what</span></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>regmodel1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SWAPOUTCOME <span class="sc">~</span> SWAPPREDICTOR1 <span class="sc">+</span> SWAPPREDICTOR2 <span class="sc">+</span> SWAPGROUP,   <span class="co"># SWAP every name; regmodel2 for your next model</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> mydata)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(regmodel1)      <span class="co"># slopes (Estimate), p-values (Pr(&gt;|t|)), and R-squared</span></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a><span class="fu">nobs</span>(regmodel1)         <span class="co"># the number of people in the model</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. check the residuals</span></span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">residual =</span> <span class="fu">resid</span>(regmodel1)),</span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> residual)) <span class="sc">+</span></span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. a table for your report</span></span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">summary</span>(regmodel1)<span class="sc">$</span>coefficients, <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Table 1. SWAP: a caption that can stand alone."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then write your results sentence. Use this pattern, and say whether your hypothesis was supported.</p>
<blockquote class="blockquote">
<p>A multiple linear regression (n = ___) showed that ______ was ______ (positively / negatively / not significantly) associated with ______ (b = ___, p = ___), after accounting for ______. The predictors explained ___% of the variance in ______ (R² = ___).</p>
</blockquote>
<section id="checklist-for-your-rd-report-and-final-report" class="level3" data-number="26.4.1">
<h3 data-number="26.4.1" class="anchored" data-anchor-id="checklist-for-your-rd-report-and-final-report"><span class="header-section-number">26.4.1</span> Checklist for your RD Report and Final Report</h3>
<div class="gray callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Resources</span>Open the regression checklist
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<!-- Single source for the regression checklist. Included in Relate 3+ Variables ("Your Turn"), and later in the Final Report Checklist page. Edit it here once; every place updates. -->
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 82%">
</colgroup>
<thead>
<tr class="header">
<th>Criteria</th>
<th>Ask yourself</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Right test</strong></td>
<td>Does the Analysis Map lead here (one continuous outcome, two or more predictors)?</td>
</tr>
<tr class="even">
<td><strong>Missing codes</strong></td>
<td>Were codes such as -99 and -50 changed to <code>NA</code> before the model was run?</td>
</tr>
<tr class="odd">
<td><strong>Categorical predictors</strong></td>
<td>Is every categorical predictor a <code>factor()</code> with labels, not a number? Does your text name the comparison group?</td>
</tr>
<tr class="even">
<td><strong>Outcome kept whole</strong></td>
<td>Is the outcome the full score (not cut into “high” and “low”)?</td>
</tr>
<tr class="odd">
<td><strong>Plot first</strong></td>
<td>Is there a scatterplot of the outcome and your main predictor before the model?</td>
</tr>
<tr class="even">
<td><strong>Model statement</strong></td>
<td>Does the text say which test was run, the outcome, and every predictor?</td>
</tr>
<tr class="odd">
<td><strong>Each predictor</strong></td>
<td>Do you report <em>b</em> and <em>p</em> for every predictor, including the ones that were not significant?</td>
</tr>
<tr class="even">
<td><strong>Sample size</strong></td>
<td>Is <em>n</em> reported from <code>nobs()</code>, not from the number of rows in the dataset?</td>
</tr>
<tr class="odd">
<td><strong>R-squared</strong></td>
<td>Is R-squared reported and explained in plain words (percent of the differences in the outcome)?</td>
</tr>
<tr class="even">
<td><strong>Residuals</strong></td>
<td>Is there a histogram of the residuals, and one sentence on its shape?</td>
</tr>
<tr class="odd">
<td><strong>Interpretation</strong></td>
<td>Does the text connect the result to your hypothesis, with “holding the other predictors constant”?</td>
</tr>
<tr class="even">
<td><strong>No causal words</strong></td>
<td>Did you avoid “causes”, “leads to”, “impacts”, and “effect of”?</td>
</tr>
<tr class="odd">
<td><strong>Table</strong></td>
<td>Is there a regression table made with <code>kable()</code>, with a caption starting “Table 1.”?</td>
</tr>
<tr class="even">
<td><strong>Inline numbers</strong></td>
<td>Do the numbers in your sentences come from inline R code, not typed by hand?</td>
</tr>
<tr class="odd">
<td><strong>Referenced in text</strong></td>
<td>Does your results paragraph point to the table and the figure?</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<!-- Single source for the collapsed final-whistle reminder at the END of every coding chapter (7 onward). Edit here only. The full routine lives in find-the-ref.qmd (Ref's Quick Checklist). -->
<div class="gray callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Resources</span><img src="images/ref-whistle.svg" class="ref-mini img-fluid" alt="Ref the raccoon blowing his whistle"> Ref’s final whistle: before you quit RStudio
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Save → Render → Back up to ELN → Quit, Don’t Save workspace.</strong> Details: <a href="./find-the-ref.html#sec-ref-checklist">Ref’s Quick Checklist</a>.</p>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/shanemccarty\.github\.io\/FRIplaybook");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./correlation.html" class="pagination-link" aria-label="Relate 2 Variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Relate 2 Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./start-rdreport.html" class="pagination-link" aria-label="Start My Report">
        <span class="nav-page-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Start My Report</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://shanemccarty.github.io/FRIplaybook/edit/main/regression.qmd" class="toc-action"><i class="bi bi-git"></i>Edit this page</a></li><li><a href="https://shanemccarty.github.io/FRIplaybook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>