{
  "hash": "7867ce645f7c28b7e66f3b39058af11e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Compare 3+ Groups\"\nsubtitle: \"ANOVA (normal), Kruskal-Wallis (non-normal), and ANCOVA\"\nauthor:\n  - Shane McCarty\nabstract: |\n  This chapter is the Analysis Map's \"compare 3+ groups\" row: three or more groups of different people and one continuous outcome. Researchers learn when the one-way ANOVA is the right test and when the Kruskal-Wallis test is, how to run each with its follow-up test (Tukey; pairwise Wilcoxon) and effect size, how to add a covariate with an ANCOVA, and how to report each result. The Play uses the Cohort 10 health status data to compare subjective social status and self-rated health across three perceived-income groups. The Lab runs the same tests on the lab dataset with Ref's checks, and Your Turn gives the template for the team dataset.\nkeywords:\n  - ANOVA\n  - Tukey\n  - eta squared\n  - Kruskal-Wallis\n  - ANCOVA\n  - covariate\n  - comparison\ndate: 10.04.2026\ndate-format: \"MM.DD.YYYY\"\nformat:\n  html:\n    css: custom.css\neditor: visual\nexecute:\n  cache: false   # this chapter reads lab_prep.R and the lab dataset; a cache would keep OLD data after they change\n  warning: false\n  message: false\n---\n\n<!-- Single source for the collapsed kickoff reminder at the START of every coding chapter (7 onward). Edit here only. The full routine lives in find-the-ref.qmd (Ref's Quick Checklist). -->\n\n::: {.callout-note .gray collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's kickoff: find the Ref before you code\n\n**Open Project → Open `.qmd` → Run load-library chunk → Run All Chunks Above → code.** If anything looks wrong, use [Ref's Quick Checklist](find-the-ref.qmd#sec-ref-checklist).\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Resources: ANOVA, Kruskal-Wallis, and ANCOVA\n\n-   [One-way ANOVA in R](https://www.datacamp.com/tutorial/anova-in-r) (DataCamp tutorial)\n-   [Kruskal-Wallis test in R](https://www.sthda.com/english/wiki/kruskal-wallis-test-in-r) (STHDA)\n-   R documentation: `?aov`, `?TukeyHSD`, `?kruskal.test`, `?pairwise.wilcox.test`\n-   [Compare 2 Groups](compare2groups.qmd): the two-group version of every idea here, including why a rating is not a normal outcome\n:::\n\n## When is this the right test?\n\nYour research question is a **comparison**, you have **three or more groups of different people**, and **one continuous outcome**. On [The Analysis Map](analysis-map.qmd) that is the *compare 3+ groups* row. Exactly two groups is the row above, [Compare 2 Groups](compare2groups.qmd); the same people measured three times is a repeated-measures design, which this playbook does not cover, so talk to your peer mentor and/or Dr. Shane.\n\nAs in every box on the map, the shape of the outcome picks the test:\n\n| Test | Use it when | R function | Follow-up | Report |\n|----|----|----|----|----|\n| [**One-way ANOVA** (parametric)]{.normal} | the outcome is roughly normal within each group, or every group has 30 or more people | `aov()` | `TukeyHSD()` | *M*, *SD*, *F*(df1, df2), *p*, η² |\n| [**Kruskal-Wallis** (non-parametric)]{.nonnormal} | the outcome is skewed, a group is small, or the outcome is a single rating with a few levels | `kruskal.test()` | `pairwise.wilcox.test()` | *Mdn*, *H*(df), *p*, pairwise *p* |\n| **ANCOVA** | an ANOVA plus one continuous variable to account for (a **covariate**), such as age | `aov(OUTCOME ~ COVARIATE + GROUP)` | `TukeyHSD()` is not valid; see the regression chapter | *F*, *p* for the group row, \"after accounting for…\" |\n\n::: callout-tip\n## Go: do these two things first\n\n1.  Check the outcome's shape within each group: [Describe Your Data](describe.qmd), and the Shapiro-Wilk check in [Compare 2 Groups](compare2groups.qmd).\n2.  Draw the plot: the bar chart or violin from [Visualize a Comparison](visualize-comparison.qmd). A test without its plot is a number without a picture.\n:::\n\n## 📋 The Play\n\n::: {.callout-note collapse=\"true\"}\n## About the dataset: `health_status_data.csv` (the Cohort 10 class dataset)\n\nEvery FRI Public Health team in **Cohort 10** asked the same self-rated health question, *Would you say your health in general is excellent, very good, good, fair, or poor?*, along with the class variables of that year (age, sex, racialized identity, perceived income, and the MacArthur ladder of subjective social status). The five team datasets were merged into one file of 343 respondents so that health status could be examined across the whole class. `SAMPLE_ID` says which team's study a person came from.\n\nThis is **real data**, already cleaned and de-identified: no response IDs, passwords, dates, or open-ended answers, and the five team samples differ in whom they recruited (students, families, farmers-market visitors), which is why the chapters filter by age. The variable names predate the class naming rules, so the Play renames them: `HEALTH_STATUS` becomes `HEALTHSTATUS` (1 = Poor … 5 = Excellent); `SSS` is subjective social status (1 to 10); `SEX` is biological sex (0 = male, 1 = female); and `RACIALIZED_IDENTITY` (1 = identified as white only, 0 = any other identity) becomes `MINORITIZED_01` (1 = minoritized, 0 = not), named for the 1 the way a `_01` variable should be. The other columns (`RG_…`, `RI_…`, `PoorFairHealth`, `ExcellentHealth`) are earlier recodes of the same questions and are not used here.\n:::\n\n\nThe Cohort 10 survey asked everyone to rate their household income as much below average, below average, average, above average, or much above average (`PERCEIVED_INCOME`), and the class collapsed that into three groups, `INCOME3`: below average, average, above average. Two questions, one for each line of the box: do the three income groups differ in **subjective social status** (`SSS`, the MacArthur ladder, 1 to 10), a continuous score; and do they differ in **self-rated health** (`HEALTHSTATUS`, 1 = Poor to 5 = Excellent), a single rating?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(knitr)\n```\n:::\n\n\n### Play 1 ([one-way ANOVA]{.normal}): compare three perceived-income groups on subjective social status\n\n#### Step 1: Import, recode, and count the groups\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealthstatusdata <- read.csv(\"data/health_status_data.csv\") |>\n  rename(HEALTHSTATUS = HEALTH_STATUS) |>\n  mutate(INCOME3 = factor(INCOME3, levels = c(1, 2, 3),\n                          labels = c(\"Below average\", \"Average\", \"Above average\"))) |>   # the group must be a factor\n  filter(!is.na(INCOME3), !is.na(SSS), !is.na(HEALTHSTATUS))\n\nhealthstatusdata |> count(INCOME3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        INCOME3   n\n1 Below average  65\n2       Average 149\n3 Above average 129\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: Visualize a Comparison (Play 2)\n#explanation: factor() with levels in a sensible order; filter() drops people missing the group or either outcome, so every test below uses the same people\n```\n:::\n\n\n::: callout-warning\n## Caution: don't leave your group as a number\n\nIf the group is stored as 1, 2, 3, `aov()` treats it as a score and fits a straight line through the group numbers: a wrong answer with no error message. Make it a `factor()` first, every time.\n:::\n\n#### Step 2: Look at the three groups\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealthstatusdata |>\n  group_by(INCOME3) |>\n  summarise(n = n(), mean = mean(SSS), sd = sd(SSS), shapiro_p = shapiro.test(SSS)$p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  INCOME3           n  mean    sd    shapiro_p\n  <fct>         <int> <dbl> <dbl>        <dbl>\n1 Below average    65  4.74 1.57  0.000408    \n2 Average         149  6.23 1.33  0.00000100  \n3 Above average   129  7.41 0.989 0.0000000268\n```\n\n\n:::\n\n```{.r .cell-code}\nplot1_sss_income_violin <- ggplot(healthstatusdata, aes(x = INCOME3, y = SSS, fill = INCOME3)) +\n  geom_violin(alpha = 0.6, show.legend = FALSE) +\n  geom_boxplot(width = 0.12, outlier.shape = NA, show.legend = FALSE) +\n  geom_jitter(width = 0.12, height = 0.15, alpha = 0.3, size = 1.2, show.legend = FALSE) +\n  scale_y_continuous(breaks = 1:10, limits = c(1, 10)) +\n  scale_fill_manual(values = c(\"#8d14c1\", \"#f4b400\", \"#009e73\")) +\n  labs(x = \"Perceived household income\", y = \"Subjective social status (1 = bottom rung, 10 = top rung)\",\n       title = \"Subjective social status by perceived income\") +\n  theme_bw(base_size = 13)\n\nplot1_sss_income_violin\n```\n\n::: {.cell-output-display}\n![Figure 1. Subjective social status by perceived income (Cohort 10 data, n = 343). Violins show the distribution, boxes the median and quartiles, points the individual ratings.](ANOVA_files/figure-html/plot1-sss-income-violin-1.png){fig-alt='Three violin plots, one per income group, rising from left to right. The below-average group is centered near 5 on the ladder, the average group near 6, and the above-average group near 7.5.' width=672}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot1_sss_income_violin.png\", plot = plot1_sss_income_violin, width = 8, height = 5, dpi = 300)\n\n#source: Compare 2 Groups (Play 2)\n#explanation: the same three layers as the two-group violin, with three groups on the x axis\n```\n:::\n\n\nThe Shapiro-Wilk p-values are below .05 (a 1-to-10 ladder with most people on the middle rungs is not quite normal), but every group has 60 or more people, which is the second condition in the table above: with groups this size the ANOVA is robust to this much non-normality. The picture is the point: three distributions that step up from left to right.\n\n#### Step 3: The one-way ANOVA\n\nAn ANOVA asks one question: is **at least one** group mean different from the others?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# anovamodel1: SSS by INCOME3 (one-way ANOVA)\nanovamodel1 <- aov(SSS ~ INCOME3, data = healthstatusdata)\nsummary(anovamodel1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nINCOME3       2  315.6  157.81   98.27 <2e-16 ***\nResiduals   340  546.0    1.61                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: https://www.datacamp.com/tutorial/anova-in-r\n#explanation: outcome ~ group; the INCOME3 row gives the F statistic and p-value; the Residuals row gives the second df\n```\n:::\n\n\nRead the `INCOME3` row: `F value` is the test statistic, `Df` on that row is the first degrees of freedom (groups minus 1), `Df` on the `Residuals` row is the second (people minus groups), and `Pr(>F)` is the p-value.\n\n#### Step 4: Which groups differ? Tukey's follow-up test, and the effect size\n\nA significant ANOVA says the groups are not all the same; it does not say which pairs differ. Tukey's test compares every pair and adjusts the p-values for the number of comparisons. Run it only when the ANOVA is significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(anovamodel1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = SSS ~ INCOME3, data = healthstatusdata)\n\n$INCOME3\n                                diff       lwr      upr p adj\nAverage-Below average       1.489726 1.0462884 1.933164     0\nAbove average-Below average 2.672391 2.2186323 3.126150     0\nAbove average-Average       1.182665 0.8238997 1.541430     0\n```\n\n\n:::\n\n```{.r .cell-code}\n# effect size: eta squared = sum of squares for the group / total sum of squares\nss <- summary(anovamodel1)[[1]]$`Sum Sq`\neta2_sss <- ss[1] / sum(ss)\neta2_sss\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3663086\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: R documentation ?TukeyHSD; Cohen (1988) for eta squared\n#explanation: each Tukey row is one pair, diff is the mean difference, p adj is the adjusted p; eta squared is the share of variance explained by the group: .01 small, .06 medium, .14 large\n```\n:::\n\n\nAll three pairs differ, and η² is large: perceived income and the ladder rating are two views of the same thing, which is why the effect is so big. In your own data an η² of .06 is a respectable medium effect.\n\n#### Step 5: Report it\n\n\n\n> Subjective social status differed across the three perceived-income groups, *F*(2, 340) = 98.27, *p* < .001, η² = 0.37, a large effect. Tukey follow-up tests showed that every pair differed (all *p* < .001): people reporting above-average income placed themselves higher on the ladder (*M* = 7.41, *SD* = 0.99, *n* = 129) than people reporting average income (*M* = 6.23, *SD* = 1.33, *n* = 149), who placed themselves higher than people reporting below-average income (*M* = 4.74, *SD* = 1.57, *n* = 65) (Figure 1).\n\n### Play 2 ([Kruskal-Wallis]{.nonnormal}): compare three perceived-income groups on self-rated health\n\nSelf-rated health is one question with five answers. As [Compare 2 Groups](compare2groups.qmd) Play 3 explains, a rating like that is not normal and its mean describes nobody, so this is the non-parametric line of the box. The Kruskal-Wallis test is the Mann-Whitney U for three or more groups: it ranks everyone's rating and asks whether the groups' ranks differ.\n\n#### Step 1: Look\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealthstatusdata |>\n  group_by(INCOME3) |>\n  summarise(n = n(), median = median(HEALTHSTATUS), mean = mean(HEALTHSTATUS))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  INCOME3           n median  mean\n  <fct>         <int>  <dbl> <dbl>\n1 Below average    65      3  3.32\n2 Average         149      3  3.40\n3 Above average   129      4  3.69\n```\n\n\n:::\n\n```{.r .cell-code}\nhealth_props <- healthstatusdata |>\n  count(INCOME3, HEALTHSTATUS) |>\n  group_by(INCOME3) |>\n  mutate(prop = n / sum(n)) |>\n  ungroup()\n\nplot2_health_income_barplot <- ggplot(health_props, aes(x = factor(HEALTHSTATUS), y = prop, fill = INCOME3)) +\n  geom_col(position = position_dodge(width = 0.8), width = 0.75) +\n  scale_x_discrete(labels = c(\"1\" = \"Poor\", \"2\" = \"Fair\", \"3\" = \"Good\", \"4\" = \"Very good\", \"5\" = \"Excellent\")) +\n  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +\n  scale_fill_manual(values = c(\"#8d14c1\", \"#f4b400\", \"#009e73\")) +\n  labs(x = \"Self-rated health\", y = \"Share of group\", fill = \"Perceived income\",\n       title = \"Self-rated health by perceived income\") +\n  theme_bw(base_size = 13) +\n  theme(legend.position = \"top\")\n\nplot2_health_income_barplot\n```\n\n::: {.cell-output-display}\n![Figure 2. Self-rated health by perceived income (Cohort 10 data, n = 343). Bars are the share of each group choosing each answer.](ANOVA_files/figure-html/plot2-health-income-barplot-1.png){fig-alt='Three sets of five bars, one per income group, for Poor through Excellent. The above-average group has the largest share at Very good and Excellent; the below-average group has the largest share at Fair.' width=672}\n:::\n\n```{.r .cell-code}\nggsave(\"plots/plot2_health_income_barplot.png\", plot = plot2_health_income_barplot, width = 8, height = 5, dpi = 300)\n\n#source: Compare 2 Groups (Play 3)\n#explanation: proportions within each group, so a bigger group does not look healthier\n```\n:::\n\n\n#### Step 2: The Kruskal-Wallis test and its follow-up\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# kruskalmodel1: HEALTHSTATUS by INCOME3 (Kruskal-Wallis)\nkruskalmodel1 <- kruskal.test(HEALTHSTATUS ~ INCOME3, data = healthstatusdata)\nkruskalmodel1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  HEALTHSTATUS by INCOME3\nKruskal-Wallis chi-squared = 10.171, df = 2, p-value = 0.006185\n```\n\n\n:::\n\n```{.r .cell-code}\npairwise.wilcox.test(healthstatusdata$HEALTHSTATUS, healthstatusdata$INCOME3, p.adjust.method = \"holm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using Wilcoxon rank sum test with continuity correction \n\ndata:  healthstatusdata$HEALTHSTATUS and healthstatusdata$INCOME3 \n\n              Below average Average\nAverage       0.58          -      \nAbove average 0.02          0.02   \n\nP value adjustment method: holm \n```\n\n\n:::\n\n```{.r .cell-code}\n#source: R documentation ?kruskal.test, ?pairwise.wilcox.test\n#explanation: the Kruskal-Wallis statistic is reported as H with df = groups minus 1; the follow-up runs a Mann-Whitney U for each pair and adjusts the p-values (Holm)\n```\n:::\n\n\nThe follow-up table reads like a mileage chart: each cell is the adjusted p-value for one pair. Here the above-average group differs from each of the other two, and the below-average and average groups do not differ from each other.\n\n#### Step 3: Report it\n\n\n\n> Self-rated health differed across the three perceived-income groups, Kruskal-Wallis *H*(2) = 10.17, *p* = .006. Pairwise Mann-Whitney U tests with a Holm correction showed that people reporting above-average income rated their health higher (*Mdn* = 4, Very good; *n* = 129) than people reporting average (*Mdn* = 3, Good; *n* = 149) or below-average income (*Mdn* = 3, Good; *n* = 65), both *p* = .02; the latter two groups did not differ (*p* = .58) (Figure 2).\n\n### Play 3 (ANCOVA): compare the same three groups on subjective social status, after accounting for age\n\nThe five team samples differ in age (students in some, families and farmers-market visitors in others), and older people tend to have higher incomes. An ANCOVA asks Play 1's question again **for people of the same age**: the covariate goes **first** in the formula, the group last.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ancovamodel1: SSS by INCOME3, adjusting for AGE (ANCOVA)\nancovamodel1 <- aov(SSS ~ AGE + INCOME3, data = healthstatusdata)\nsummary(ancovamodel1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value   Pr(>F)    \nAGE           1   34.9   34.88   22.85 2.62e-06 ***\nINCOME3       2  309.2  154.62  101.28  < 2e-16 ***\nResiduals   339  517.5    1.53                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(ancovamodel1)   # people missing AGE are dropped: check the n\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 343\n```\n\n\n:::\n\n```{.r .cell-code}\n#source: R documentation ?aov\n#explanation: covariate first, group last; read the INCOME3 row as \"do the groups differ, at the same age?\"\n```\n:::\n\n\nThe `INCOME3` row still has a very small p-value: the income groups differ in subjective social status even after accounting for age. Report it as the Play 1 sentence plus \"after accounting for age\", with the *F* and *p* from this table.\n\n::: callout-warning\n## Caution: three things to know about ANCOVA\n\n-   The order in the formula matters in `aov()`: covariate first, group last. Reversed, the group row answers a different question.\n-   People missing the covariate are dropped, so the n can shrink. Check it with `nobs()`.\n-   `TukeyHSD()` is not valid after an ANCOVA. An ANCOVA is a linear regression with a categorical predictor, and [Relate 3+ Variables](regression.qmd) shows how to read which groups differ from the comparison group.\n:::\n\n::: callout-warning\n## Caution: different does not mean caused\n\nA survey comparison tells you that groups differ. It does not tell you why. Write \"differed\" or \"scored higher\", not \"caused\" or \"led to\".\n:::\n\n## 🏈 The Lab {#sec-anova-lab}\n\n:::::: {.ref .ref-tip}\n::: ref-row\n![](images/ref.svg){.ref-img fig-alt=\"Ref the raccoon\"}\n\n**Ref's kickoff.** The lab dataset has three-group questions of both kinds. Two of them: do people in poor or fair, good, and very good or excellent general health differ in **well-being** (`WELLBEING`, an 8-item composite)? And do people on the political left, in the middle, and on the right differ in how much they believe mental health problems have **social causes** (`SOCIAL`, a 3-item composite that is skewed)? Run each the way the Play did, then open my check.\n:::\n::::::\n\n\n\n**Before you start.** `source(\"lab_prep.R\")` to create `mh_clean`. Both group variables are made from a 1-to-5 question with `case_when()`, exactly as `DISTRESS_4CAT` was in [Transforming Your Data](dplyr.qmd): `HEALTH_3CAT` from `HEALTHSTATUS` (1–2 = Poor or fair, 3 = Good, 4–5 = Very good or excellent) and `POL_3CAT` from `POLITICALBELIEFS` (1–2 = Left, 3 = Moderate, 4–5 = Right). Make both factors with the levels in that order.\n\n### Lab Play 1 ([ANOVA and Tukey]{.normal}): compare three general-health groups on well-being\n\nMake `HEALTH_3CAT`, keep people with a value on it, draw the violin plot, check normality within each group, run the ANOVA, then Tukey, then η².\n\n::: {.callout-tip collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's check: what should you find?\n\n-   Groups: Poor or fair 36, Good 81, Very good or excellent 61 (n = 178 with a well-being score).\n-   Means: 3.03, 3.19, 3.56. Shapiro-Wilk p = 0.374, 0.478, 0.436.\n-   ANOVA: *F*(2, 175) = 9.24, *p* < .001; η² = 0.10.\n-   Tukey: Good vs Poor or fair *p* = .399; Very good or excellent vs Poor or fair *p* < .001; Very good or excellent vs Good *p* = .003.\n:::\n\n### Lab Play 2 ([Kruskal-Wallis]{.nonnormal}): compare three political groups on belief in social causes\n\nMake `POL_3CAT`, keep people with a value on it, check the shape of `SOCIAL` within each group (it is skewed), run the Kruskal-Wallis test and the pairwise follow-up with a Holm correction.\n\n::: {.callout-tip collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's check: what should you find?\n\n-   Groups: Left 90, Moderate 26, Right 47. Medians: 4.33, 4.00, 3.67. Shapiro-Wilk p = 0.000, 0.044, 0.173.\n-   Kruskal-Wallis *H*(2) = 18.74, *p* < .001.\n-   Pairwise (Holm): Moderate vs Left *p* = .499; Right vs Left *p* < .001; Right vs Moderate *p* = .026.\n:::\n\n### Lab Play 3 (ANCOVA): compare the three general-health groups on well-being, after accounting for age\n\nRun Lab Play 1's ANOVA again with `AGE` first in the formula, and check `nobs()`.\n\n::: {.callout-tip collapse=\"true\" icon=\"false\"}\n## ![](images/ref.svg){.ref-mini fig-alt=\"Ref the raccoon\"} Ref's check: what should you find?\n\n-   `HEALTH_3CAT` row: *F*(2, 172) = 8.88, *p* < .001; n = 176 (2 people dropped for a missing age).\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\"}\n## 👀 See the solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"lab_prep.R\")\n\nlab3 <- mh_clean |>\n  mutate(HEALTH_3CAT = factor(case_when(HEALTHSTATUS %in% c(1, 2) ~ \"Poor or fair\",\n                                        HEALTHSTATUS == 3         ~ \"Good\",\n                                        HEALTHSTATUS %in% c(4, 5) ~ \"Very good or excellent\"),\n                              levels = c(\"Poor or fair\", \"Good\", \"Very good or excellent\")),\n         POL_3CAT = factor(case_when(POLITICALBELIEFS %in% c(1, 2) ~ \"Left\",\n                                     POLITICALBELIEFS == 3         ~ \"Moderate\",\n                                     POLITICALBELIEFS %in% c(4, 5) ~ \"Right\"),\n                           levels = c(\"Left\", \"Moderate\", \"Right\")))\n\n# Lab Play 1\nlab_h <- lab3 |> filter(!is.na(HEALTH_3CAT), !is.na(WELLBEING))\nlab_h |> group_by(HEALTH_3CAT) |> summarise(n = n(), mean = mean(WELLBEING), sd = sd(WELLBEING),\n                                            shapiro_p = shapiro.test(WELLBEING)$p.value)\nggplot(lab_h, aes(x = HEALTH_3CAT, y = WELLBEING, fill = HEALTH_3CAT)) +\n  geom_violin(alpha = 0.6, show.legend = FALSE) + geom_boxplot(width = 0.12, outlier.shape = NA, show.legend = FALSE) +\n  geom_jitter(width = 0.12, alpha = 0.3, show.legend = FALSE) + theme_bw()\nanovamodel2 <- aov(WELLBEING ~ HEALTH_3CAT, data = lab_h)\nsummary(anovamodel2)\nTukeyHSD(anovamodel2)\nss <- summary(anovamodel2)[[1]]$`Sum Sq`; ss[1] / sum(ss)\n\n# Lab Play 2\nlab_p <- lab3 |> filter(!is.na(POL_3CAT), !is.na(SOCIAL))\nlab_p |> group_by(POL_3CAT) |> summarise(n = n(), median = median(SOCIAL), shapiro_p = shapiro.test(SOCIAL)$p.value)\nkruskal.test(SOCIAL ~ POL_3CAT, data = lab_p)\npairwise.wilcox.test(lab_p$SOCIAL, lab_p$POL_3CAT, p.adjust.method = \"holm\")\n\n# Lab Play 3\nancovamodel2 <- aov(WELLBEING ~ AGE + HEALTH_3CAT, data = lab_h)\nsummary(ancovamodel2)\nnobs(ancovamodel2)\n```\n:::\n\n:::\n\n::: {.callout-warning collapse=\"true\" icon=\"false\"}\n## ![](images/ref-whistle.svg){.ref-mini fig-alt=\"Ref the raccoon blowing his whistle\"} Ref's call: fouls to check if your numbers do not match\n\n-   **The ANOVA table has one row with `Df` = 1 for the group** → the group is still a number. `factor()` it.\n-   **Your n is different from Ref's** → you did not drop people missing the outcome, or you ran `source(\"lab_prep.R\")` from a different folder. The counts in Ref's check are after `filter(!is.na(...))`.\n-   **Tukey rows are in a different order or the `diff` has the opposite sign** → your factor levels are in a different order. Set `levels = c(...)` as in the solution.\n-   **`pairwise.wilcox.test()` p-values differ slightly** → check `p.adjust.method = \"holm\"`; the default is also Holm, but `\"bonferroni\"` or `\"none\"` give different numbers.\n-   **The ANCOVA `HEALTH_3CAT` row is identical to the ANOVA's** → `AGE` is after the group in the formula. Covariate first.\n:::\n\n::: {.callout-important .required}\n## Required: a three-group comparison in your report\n\nFor every three-or-more-group comparison in your *RD Report* and *Final Report*: the plot (bar chart with error bars, or violin), saved with `ggsave()` and captioned with the n of each group; the shape check you ran and what it showed; the test that matches the outcome, the ANOVA with Tukey and η² for a normal composite or continuous score (Play 1, Step 5) or the Kruskal-Wallis test with pairwise follow-ups for a skewed outcome or a single rating (Play 2, Step 3); and one sentence in Results in that Play's form. Say in Methods how you defined the groups and whom you excluded. Add the ANCOVA only if a covariate is part of your research question.\n:::\n\n## 🏆 Your Turn {#sec-anova-yourturn}\n\n::: {.callout-note .gray icon=\"false\"}\n## There is no Ref. It's game time, your turn!\n\nNobody has compared your team's groups before, so there is no answer to check against. Change every word that starts with `SWAP`, pick the line of the box that matches your outcome, and use the checklist.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\n# 1. three or more groups, as a labeled factor\nmydata <- cleandata |>\n  mutate(SWAPGROUP_3CAT = factor(SWAPGROUP_3CAT, levels = c(1, 2, 3),                     # SWAP: your group variable (a _#CAT variable)\n                             labels = c(\"SWAPLABEL1\", \"SWAPLABEL2\", \"SWAPLABEL3\"))) |>    # SWAP: the labels, comparison group first\n  filter(!is.na(SWAPGROUP_3CAT), !is.na(SWAPOUTCOME))                                    # SWAP: your outcome (a score)\nmydata |> count(SWAPGROUP_3CAT)                                                      # every group big enough?\n\n# 2. look\nmydata |> group_by(SWAPGROUP_3CAT) |> summarise(n = n(), mean = mean(SWAPOUTCOME), sd = sd(SWAPOUTCOME), median = median(SWAPOUTCOME),\n                                            shapiro_p = shapiro.test(SWAPOUTCOME)$p.value)\nggplot(mydata, aes(x = SWAPGROUP_3CAT, y = SWAPOUTCOME, fill = SWAPGROUP_3CAT)) +\n  geom_violin(alpha = 0.6) + geom_boxplot(width = 0.12, outlier.shape = NA) + geom_jitter(width = 0.1, alpha = 0.4) +\n  theme_bw()\n\n# 3a. normal outcome (parametric): ANOVA, Tukey, eta squared\n# anovamodel1: SWAP: one line that says what this model compares\nanovamodel1 <- aov(SWAPOUTCOME ~ SWAPGROUP_3CAT, data = mydata)\nsummary(anovamodel1)\nTukeyHSD(anovamodel1)\nss <- summary(anovamodel1)[[1]]$`Sum Sq`; ss[1] / sum(ss)                               # eta squared: .01 small, .06 medium, .14 large\n\n# 3b. outcome not normal, or a single rating (non-parametric): Kruskal-Wallis and pairwise follow-up\n# kruskalmodel1: SWAP: one line that says what this test compares\nkruskalmodel1 <- kruskal.test(SWAPOUTCOME ~ SWAPGROUP_3CAT, data = mydata)\nkruskalmodel1\npairwise.wilcox.test(mydata$SWAPOUTCOME, mydata$SWAPGROUP_3CAT, p.adjust.method = \"holm\")\n\n# 4. optional: ANCOVA with a covariate (covariate first)\n# ancovamodel1 <- aov(SWAPOUTCOME ~ SWAPCOVARIATE + SWAPGROUP_3CAT, data = mydata); summary(ancovamodel1); nobs(ancovamodel1)   # SWAP: the covariate\n\n# 5. save the plot for the poster\n# ggsave(\"plots/plot1_SWAPNAME.png\", width = 8, height = 5, dpi = 300)                # SWAP: the variables and plot type, e.g. plot1_wellbeing_treated_barplot\n```\n:::\n\n\n| Criteria | Ask yourself |\n|----|----|\n| **Design** | Are the groups different people? (The same people measured three times is a different design: ask your peer mentor and/or Dr. Shane.) |\n| **Groups** | Is the group a factor, with every level named in words and at least 20 people in each? |\n| **Which test** | Did you check the shape within each group and say which line of the Analysis Map box you are on: ANOVA (normal composite or continuous score) or Kruskal-Wallis (skewed, small group, or a single rating)? |\n| **Follow-up** | Did you run the follow-up test only after a significant overall test, and report which pairs differed? |\n| **Effect size** | Did you report η² for an ANOVA, and say whether it is small, medium, or large? |\n| **Plot** | Does the caption give the n of each group, and is the plot saved with `ggsave()`? |\n| **Sentence** | Does your Results sentence have *F*(df1, df2), *p*, η², and the pairs that differed (ANOVA), or *H*(df), *p*, medians, and the pairwise results (Kruskal-Wallis), and name the direction? |\n| **Exclusions** | Does Methods say how the groups were defined and who was left out? |\n\n<!-- Single source for the collapsed final-whistle reminder at the END of every coding chapter (7 onward). Edit here only. The full routine lives in find-the-ref.qmd (Ref's Quick Checklist). -->\n\n::: {.callout-note .gray collapse=\"true\" icon=\"false\"}\n## ![](images/ref-whistle.svg){.ref-mini fig-alt=\"Ref the raccoon blowing his whistle\"} Ref's final whistle: before you quit RStudio\n\n**Save → Render → Back up to ELN → Quit, Don't Save workspace.** Details: [Ref's Quick Checklist](find-the-ref.qmd#sec-ref-checklist).\n:::\n\n",
    "supporting": [
      "ANOVA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}